### ISSUE TITLE
Getting Updating registration token failed

### ISSUE THREAD

**Issue by sing011** [actions-runner-controller/actions-runner-controller#1000]
Describing the pod -

[sing011 (⎈ |aomad-runner-eks:default) runner-eks]$ kubectl describe runner example-org-runner
Name:         example-org-runner
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  actions.summerwind.dev/v1alpha1
Kind:         Runner
Metadata:
  Creation Timestamp:  2021-12-09T22:28:06Z
  Finalizers:
    runner.actions.summerwind.dev
  Generation:  1
  Managed Fields:
    API Version:  actions.summerwind.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:organization:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-12-09T22:28:06Z
    API Version:  actions.summerwind.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"runner.actions.summerwind.dev":
    Manager:         manager
    Operation:       Update
    Time:            2021-12-09T22:28:06Z
  Resource Version:  96698
  UID:               864d84eb-b1be-4e8f-9866-6edadf86e876
Spec:
  Dockerd Container Resources:
  Image:
  Organization:  SME-IAC
  Resources:
Events:
  Type     Reason                         Age   From               Message
  ----     ------                         ----  ----               -------
  Warning  FailedUpdateRegistrationToken  1s    runner-controller  Updating registration token failed

I am using the latest version - 0.20.4
I have checked other similar issues. The PAT has required permissions and there is no clock drift. 
This was working perfectly fine last month on a similar AWS EKS setup.

Manifest-

# runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: example-org-runner
spec:
  organization: SME-IAC

Command used to create secret - 
kubectl create secret generic controller-manager \
    -n actions-runner-system \
    --from-literal=github_token=${GITHUB_TOKEN}  

where ${GITHUB_TOKEN} is replaced by the actual token.

Any suggestions?

**Comment by mumoshu** [comment]
@sing011 Hey! I think there should be no fault on actions-runner-controller side if your token is really valid. All actions-runner-controller does is to call various APIs in behalf of you(and your PAT), and we haven't added/removed variety of APIs the controller calls.

That said, would you mind sharing your logs from controller-manager, rather than runner? It's mainly controller-manager than runners, who calls GitHub APIs on your behalf. So if there's any discrepancy between our expectation and the actual setup(especially around the PAT), it should be logging useful information in the controller-manager log, ratherthan in runner logs.

**Comment by sing011** [comment]
@mumoshu Sure. Please let me know if you have any more questions. 

[sing011 (⎈ |aomad-runner-eks:default) ~]$ kubectl describe deploy controller-manager -n actions-runner-system
Name:                   controller-manager
Namespace:              actions-runner-system
CreationTimestamp:      Thu, 09 Dec 2021 15:04:39 -0500
Labels:                 control-plane=controller-manager
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               control-plane=controller-manager
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  control-plane=controller-manager
  Containers:
   manager:
    Image:      summerwind/actions-runner-controller:v0.20.4
    Port:       9443/TCP
    Host Port:  0/TCP
    Command:
      /manager
    Args:
      --metrics-addr=127.0.0.1:8080
      --enable-leader-election
      --sync-period=10m
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:     100m
      memory:  20Mi
    Environment:
      GITHUB_TOKEN:                <set to the key 'github_token' in secret 'controller-manager'>                Optional: true
      GITHUB_APP_ID:               <set to the key 'github_app_id' in secret 'controller-manager'>               Optional: true
      GITHUB_APP_INSTALLATION_ID:  <set to the key 'github_app_installation_id' in secret 'controller-manager'>  Optional: true
      GITHUB_APP_PRIVATE_KEY:      /etc/actions-runner-controller/github_app_private_key
    Mounts:
      /etc/actions-runner-controller from controller-manager (ro)
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
   kube-rbac-proxy:
    Image:      quay.io/brancz/kube-rbac-proxy:v0.10.0
    Port:       8443/TCP
    Host Port:  0/TCP
    Args:
      --secure-listen-address=0.0.0.0:8443
      --upstream=http://127.0.0.1:8080/
      --logtostderr=true
      --v=10
    Environment:  <none>
    Mounts:       <none>
  Volumes:
   cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  webhook-server-cert
    Optional:    false
   controller-manager:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  controller-manager
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  controller-manager-74fc6b6d5c (1/1 replicas created)
NewReplicaSet:   <none>
Events:          <none>

**Comment by sing011** [comment]
Accidentally closed this. Reopened again. Pasted requested logs above @mumoshu

**Comment by sing011** [comment]
Also, I'm able to curl using the same token.

**Comment by mumoshu** [comment]
@sing011 It would be great if you could share logs from controller-manager rather than the `kubectl-describe` result :)

Also, this is how you could test if your token has the permission for registering runner. Could you confirm?

https://docs.github.com/en/rest/reference/actions#create-a-registration-token-for-a-repository--code-samples

**Comment by sing011** [comment]
@mumoshu  Sorry, here you go-

2021-12-14T15:48:42.071Z        ERROR   actions-runner-controller.runner        Failed to get new registration token    {"runner": "example-org-runner", "error": "failed to create registration token: Post \"https://api.github.com/orgs/SME-IAC/actions/runners/registration-token\": dial tcp 140.82.121.6:443: i/o timeout"}
github.com/actions-runner-controller/actions-runner-controller/controllers.(*RunnerReconciler).Reconcile
        /workspace/controllers/runner_controller.go:189
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214
2021-12-14T15:48:42.071Z        ERROR   controller-runtime.manager.controller.runner-controller Reconciler error        {"reconciler group": "actions.summerwind.dev", "reconciler kind": "Runner", "name": "example-org-runner", "namespace": "default", "error": "failed to create registration token: Post \"https://api.github.com/orgs/SME-IAC/actions/runners/registration-token\": dial tcp 140.82.121.6:443: i/o timeout"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214
2021-12-14T15:48:42.071Z        DEBUG   controller-runtime.manager.events       Warning {"object": {"kind":"Runner","namespace":"default","name":"example-org-runner","uid":"864d84eb-b1be-4e8f-9866-6edadf86e876","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"96698"}, "reason": "FailedUpdateRegistrationToken", "message": "Updating registration token failed"}
I1209 22:27:16.344429       1 main.go:177] Valid token audiences:
I1209 22:27:16.344495       1 main.go:259] Generating self signed cert as no cert is provided
I1209 22:27:16.867419       1 main.go:309] Starting TCP socket on 0.0.0.0:8443
I1209 22:27:16.868106       1 main.go:316] Listening securely on 0.0.0.0:8443

**Comment by sing011** [comment]
I see this in the log - dial tcp 140.82.121.6:443: i/o timeout , but just fyi, the outbound on 443 is open to 0.0.0.0 on the worker node.

**Comment by mumoshu** [comment]
@sing011 Which cloud platform are you running the controller on(e.g. AWS)?

Also, does `curl api.github.com` runs ok on your host/other pod/a runner pod?

I'm now suspecting this is caused by VPC config (like you're missing internet gateway in your VPC or the route table associated to your subnet is missing the route to the IGW) or CNI issue(like your CNI plugin isn't setting up a default gateway correctly)

**Comment by sme-cloudops-github** [comment]
@mumoshu  I re-created EKS cluster with default VPC CNI settings. Working now. But I will test it with the custom VPC settings again because it worked last time with the same. Thanks

**Comment by sing011** [comment]
@mumoshu I re-created EKS cluster with default VPC CNI settings. Working now. But I will test it with the custom VPC settings again because it worked last time with the same. Thanks

**Comment by sing011** [comment]
@mumoshu  Sadly, this issue has re-surfaced. Im using the same EKS after couple of weeks. These are the logs -

2022-01-10T19:50:54.920Z        DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/mutate-actions-summerwind-dev-v1alpha1-runner", "code": 200, "reason": "", "UID": "888da9c5-8b2e-4135-9516-a217db123ba9", "allowed": true}
2022-01-10T19:50:54.921Z        DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/validate-actions-summerwind-dev-v1alpha1-runner", "UID": "eeabd49f-3844-4b8f-9177-06c9552c063b", "kind": "actions.summerwind.dev/v1alpha1, Kind=Runner", "resource": {"group":"actions.summerwind.dev","version":"v1alpha1","resource":"runners"}}
2022-01-10T19:50:54.921Z        INFO    runner-resource validate resource to be created {"name": "example-org-runner"}
2022-01-10T19:50:54.921Z        DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/validate-actions-summerwind-dev-v1alpha1-runner", "code": 200, "reason": "", "UID": "eeabd49f-3844-4b8f-9177-06c9552c063b", "allowed": true}
2022-01-10T19:50:54.948Z        DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/mutate-actions-summerwind-dev-v1alpha1-runner", "UID": "5ae3d522-eccb-4844-b3ef-01608971377c", "kind": "actions.summerwind.dev/v1alpha1, Kind=Runner", "resource": {"group":"actions.summerwind.dev","version":"v1alpha1","resource":"runners"}}
2022-01-10T19:50:54.948Z        DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/mutate-actions-summerwind-dev-v1alpha1-runner", "code": 200, "reason": "", "UID": "5ae3d522-eccb-4844-b3ef-01608971377c", "allowed": true}
2022-01-10T19:50:54.950Z        DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/validate-actions-summerwind-dev-v1alpha1-runner", "UID": "17e84d68-7cee-4983-a598-1ad2a5779413", "kind": "actions.summerwind.dev/v1alpha1, Kind=Runner", "resource": {"group":"actions.summerwind.dev","version":"v1alpha1","resource":"runners"}}
2022-01-10T19:50:54.950Z        INFO    runner-resource validate resource to be updated {"name": "example-org-runner"}
2022-01-10T19:50:54.950Z        DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/validate-actions-summerwind-dev-v1alpha1-runner", "code": 200, "reason": "", "UID": "17e84d68-7cee-4983-a598-1ad2a5779413", "allowed": true}
I1227 05:05:41.385935       1 main.go:177] Valid token audiences:
I1227 05:05:41.392414       1 main.go:259] Generating self signed cert as no cert is provided
I1227 05:05:41.766773       1 main.go:309] Starting TCP socket on 0.0.0.0:8443
I1227 05:05:41.769412       1 main.go:316] Listening securely on 0.0.0.0:8443



Any help would be greatly appreciated. Following is the runner describe-

Name:         example-org-runner
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  actions.summerwind.dev/v1alpha1
Kind:         Runner
Metadata:
  Creation Timestamp:  2022-01-10T19:58:55Z
  Finalizers:
    runner.actions.summerwind.dev
  Generation:  1
  Managed Fields:
    API Version:  actions.summerwind.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:organization:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-01-10T19:58:55Z
    API Version:  actions.summerwind.dev/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"runner.actions.summerwind.dev":
    Manager:         manager
    Operation:       Update
    Time:            2022-01-10T19:58:55Z
  Resource Version:  9634498
  UID:               d2098719-f341-4f1a-9d29-709803f85602
Spec:
  Dockerd Container Resources:
  Image:
  Organization:  SME-IAC
  Resources:
Events:
  Type     Reason                         Age                  From               Message
  ----     ------                         ----                 ----               -------
  Warning  FailedUpdateRegistrationToken  6s (x16 over 2m51s)  runner-controller  Updating registration token failed

**Comment by mumoshu** [comment]
@sing011 Maybe you're just getting rate limited by GitHub API?

**Comment by mumoshu** [comment]
> 2021-12-14T15:48:42.071Z ERROR actions-runner-controller.runner Failed to get new registration token {"runner": "example-org-runner", "error": "failed to create registration token: Post "https://api.github.com/orgs/SME-IAC/actions/runners/registration-token\": dial tcp 140.82.121.6:443: i/o timeout"}

This basically says you have network connectivity issue against GitHub API, which should be caused by your infrastructure,  rather than actions-runner-controller.

**Comment by mumoshu** [comment]
@sing011 Thanks for your confirmation. Gotcha. Regarding the logs shared in your last report, it should contain relevant error messages and their details for the `Updating registration token failed` error recorded in your runner.

Have you somehow decreased the log level of actions-runner-controller's controller-manager in a way that it doesn't print useful error messages in the log?
If so, I'd suggest setting it verbose enough so that it contains more error details for debugging.

**Comment by sing011** [comment]
@mumoshu So I terminated my worker nodes and the auto-scaling group re-launched them with all pods getting re-deployed fresh. Turns out, it works fine now lol. So Im going to close this issue. Thanks for the feedback though.

**Comment by krumware** [comment]
We were getting the same error noticed in the error that the request: `https://api.github.com/app/installations/0/access_tokens` had a 0 instead of the actual app ID, which helped us discover that we had entered an incorrect key name in the secrets object. once we updated the key name from `github_installation_id` to `github_app_installation_id` it corrected itself.
