### ISSUE TITLE
Running pods on the host network

### ISSUE THREAD

**Issue by KairaMiu** [actions-runner-controller/actions-runner-controller#1008]
I would like to know how to set `hostNetwork: true` in the runner pod. The Specs of RunnerDeployment as well as Runner and all other Specs do not seem to provide such a configuration. Nevertheless, I have seen in some issues in which one could suspect that this option can be set. But so far I have unfortunately not been able to determine how.

Can someone help me please?

**Comment by jsotelo** [comment]
See https://github.com/actions-runner-controller/actions-runner-controller/pull/1035

**Comment by KairaMiu** [comment]
Thank you very much, works perfectly.

**Comment by mumoshu** [comment]
Closing this as resolved. Thanks for your contribution @jsotelo ☺️

**Comment by danbopes** [comment]
@jsotelo This appears to just affect the controller pod. In my case, I need hostNetwork on the runner pod, otherwise it's broken. There still doesn't appear to be anyway to set "hostNetwork: true" on the runner pod.

**Comment by mohitreddy1996** [comment]
@danbopes @jsotelo anyway we can set this on the runner pod and not just on the controller pods?

**Comment by AurimasNav** [comment]
was able to configure it with:
```yaml
containerMode:
  type: dind
template:
  spec:
    hostNetwork: true
```
