### ISSUE TITLE
Add Branch property to ScaleUpTriggers's Push Event

### ISSUE THREAD

**Issue by Moser-ss** [actions-runner-controller/actions-runner-controller#1020]
**Is your feature request related to a problem? Please describe.**
In the Github Actions is it possible to define the branch on the push event. It is annoying when I only have Actions that are triggered by push to main but the Webhook scaling is triggered by push in other branches 

**Describe the solution you'd like**
I would like to have the same property in the ScaleUpTriggers' Push Event if we already have it in the PullRequest event I don't see any reason to not have it in the Push Event 

**Additional context**
If the maintainers agree with this feature request I can work in that PR

**Comment by mumoshu** [comment]
@Moser-ss Hey! Just curious, but any reason that you can't use `workflow_job` webhook for autoscaling? That way you can differentiate `runs-on` per branch. That, in combination with matching `RunnerDeployment.Spec.Labels`, you won't need the suggested feature.

**Comment by Moser-ss** [comment]
Hey, first I didn't understand how the `workflow_job` works and could be configured, even the  [ events types](https://github.com/actions-runner-controller/actions-runner-controller/blob/de1f48111acde716bea832eb843d2c42afb170fb/api/v1alpha1/horizontalrunnerautoscaler_types.go#L65-L75) are not clear that kind of event can be used.

The other point means the user of the GHA Workflows needs to know that it is necessary to use a different label if it's running a different trigger. 

In the POV of a team that is developing a service to several teams, that is a piece of unnecessary information the customers need to know to have the job properly configured.

Imagine that I need to inform 300 developers if they want to use the trigger to `push to main` then need also to have a specific runner, that is different `pull_request` trigger.

Another use case is when the job is triggered by `push to main` and `pull_request to main ` I cannot use different labels in the runs-on (unless I use an if stament that will be not very clear)

**Comment by mumoshu** [comment]
@Moser-ss I hear you, but I'd wanted to point out one thing.

You can't use `push` scale-up trigger to "enforce" scheduling of workflow jobs to a certain runner.

Let's say you had two HRA, one that is scaled on each push to `dev` branch and another HRA that is scaled on each push to `main` branch. If there were two concurrent pushes to both `dev` and `main`, actions-runner-controller would indeed add one replica for each HRA/RunnerDeployment.

But GitHub Actions schedules workflow jobs to the available runners at the scheduling time, which implies that the job for `main` can be scheduled on the runner added for `dev` branch. This is unavoidable without labels. I believe GitHub designed runner labels to reliably resolve this issue.

> Imagine that I need to inform 300 developers if they want to use the trigger to push to main then need also to have a specific runner, that is different pull_request trigger.

I understand your problem. I think I have the same sentiment as yours. As this problem stems from how GitHub Actions works, you'd better provide that feedback to GitHub, not us :pray:

P.S. You don't need to configure `workflow_job` like other scale up triggers, as there's nothing to configure at that level.

Just ensure labels in the `runs-on` of your workflow definitions matches to `RunnerDeployment.Spec.Labels`, expose actions-runner-controller's github webhook server, and register the webhook server's external URL to GitHub. After that every webhook event published by GitHub Actions (=`workflow_job` action events of status `queued`, `in_progress`, `completed`, etc) automatically matched to the HRA/RunnerDeployment and scale-in/out happens.

**Comment by mumoshu** [comment]
I believe the PR #900 by @toast-gear is intended to resolve this exact issue. But as I wrote above, it won't resolve your issue fully. You'd better just use `workflow_job` for autoscaling.

**Comment by Moser-ss** [comment]
@mumoshu Thanks a lot for the feedback.
I read twice your comments, and if my use case is, for every time I have a  new workflow, a want a new actions-runner I just need to create the trigger into HRA like this?
```yaml
kind: HorizontalRunnerAutoscaler
spec:
  scaleTargetRef:
    name: example-runners
  scaleUpTriggers:
  - githubEvent: {}
    duration: "30m"
```

**Comment by mumoshu** [comment]
@Moser-ss Hey! Yeah, that shuld be all you need in terms of HRA. Just don't forget to configure your external loadbalaner/ingress/etc to make github webhook server able to receive webhook events from GitHub for autoscaling!

**Comment by Moser-ss** [comment]
Thanks a lot for the help I will close this issue

**Comment by mumoshu** [comment]
@Moser-ss Thanks for your confirmation 👍  Happy holidays!
