### ISSUE TITLE
Refactoring Build pipeline

### ISSUE THREAD

**Issue by pratikbalar** [actions-runner-controller/actions-runner-controller#1040]
Continuing https://github.com/actions-runner-controller/actions-runner-controller/pull/1018 here, now https://github.com/actions-runner-controller/actions-runner-controller/pull/1018 is for `UPX`ed version

### CI
- [x] Use GHA cache for docker buildx cache
- [x] Update Makefile if require 

### Controller container image
- [x] Ues [tonistiigi/xx](https://github.com/tonistiigi/xx) for go build
- [x] Maintain `UPX`ed slim container image
- [x] Use `docker-bake.hcl`

### Others
- [ ] Update docs if require

**Comment by mumoshu** [comment]
@pratikbalar Hey! Thanks for creating this. I'm not yet convinced to maintain `upx` variant of our images so if you'd want #1018 to be more likely to be merged I'd suggest you to separate it.

**Comment by pratikbalar** [comment]
Okay, Will create non `UPX`ed branch separately

**Comment by pratikbalar** [comment]
https://github.com/actions-runner-controller/actions-runner-controller/pull/1041 non upx dockerfile
