### ISSUE TITLE
When SElinux is enabled, the self-hosted runners  fail with permission denied

### ISSUE THREAD

**Issue by achebel** [actions-runner-controller/actions-runner-controller#1043]
**Describe the bug**
When SElinux is enabled, the self-hosted runners (specially the runner container) fail with an error message "permission denied" at the first startup as shown below
Github endpoint URL https://github_url/
cp: error writing '/home/runner/bin/Newtonsoft.Json.dll': Permission denied
cp: cannot create regular file '/home/runner/bin/Runner.Common.deps.json': Permission denied
cp: cannot create regular file '/home/runner/bin/Runner.Common.dll': Permission denied
cp: cannot create regular file '/home/runner/bin/Runner.Listener': Permission denied
cp: cannot create regular file '/home/runner/bin/Runner.Listener.deps.json': Permission denied
cp: cannot create regular file '/home/runner/bin/Runner.Listener.dll': Permission denied
cp: cannot create regular file '/home/runner/bin/Runner.Listener.runtimeconfig.json': Permission denied
cp: cannot create regular file '/home/runner/bin/Runner.PluginHost': Permission denied
cp: cannot create regular file '/home/runner/bin/Runner.PluginHost.deps.json': Permission denied

Then after detecting the failure, kubelet restarted it and the runner container started successfully.
At the first startup, when entered inside the pod, we noticed we were not able to perform any simple shell commands as root user or non-root user such as ls -lrt  and so on..

Quite strange why it worked when Kubelet restart it automatically when it detects the first failure.

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

**Expected behavior**
Normally the runner should start at the first startup.

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.20.2]
 - Deployment Method [Helm and Kustomize ]
 - Helm Chart Version [e.g. 0.13.2, if applicable]

**Additional context**

**Comment by mumoshu** [comment]
@achebel We do nothing special to support or un-support SELinux. You don't get such errors usually so probably those permission errors are triggered by SELinux. In that case, you'd need to configure SELinux appropriately to make it work.

Regarding the kubelet issue, it seems like it's... a kubelet issue. So I'm afraid I can't provide any support for debugging it.

**Comment by achebel** [comment]
After investigating, the issue is due to dind container that start after the runner container.
As dind container (docker) starts in privileged mode and it modifies the SElinux context for all shared folders used as well by runner container, files such as /runner; /home... /etc/hosts.....by updating MCS labels. This prevent the entrypoint of runner container to works at the first start (permissions denied..). 
When Kubelet restart automatically the "runner" container that failed, it will pick a new MCS label that won't be modifie by dind container that is already started.

Have you already tested action-runner-controller with Selinux enabled?
Because for our point of view it cannot work with this default configuration.
 
Possible solutions can be 
1- if we  force the starting order of the runner pod : first start dind container then runner container.
Because for our point of view 
2- if we force runner container to run in privileged mode as dind container (our security does not want specially when it's not required as dind)
3- Disable docker container (dockerEnabled: false. It can be solution shortly but not in midterm/longterm because we need it for certain use cases...)

May be do you any other options?

Thanks in advance

**Comment by mumoshu** [comment]
@achebel Hey. Thanks for reporting back. Just wanted to ensure that we're in-sync- Have you already tried `seLinuxOptions`?
I don't actually now how it can be used in practice as I'm not a selinux user but I remember that it was contributed by a user to use selinux with actions-runner-controller
https://github.com/actions-runner-controller/actions-runner-controller/blob/01301d3ce808b00422f2e78014584929d85470b2/README.md#additional-tweaks
