### ISSUE TITLE
Chart AppVersion does not reflect Newest Version

### ISSUE THREAD

**Issue by jbkc85** [actions-runner-controller/actions-runner-controller#1051]
**Describe the bug**

https://github.com/actions-runner-controller/actions-runner-controller/blob/1c75b207677f9ce418910de4227639d39ac5260b/charts/actions-runner-controller/Chart.yaml#L21

Line in above chart does not reflect the newest Docker image version available (0.20.4).

**Checks**

N/A

**To Reproduce**

N/A

**Expected behavior**

AppVersion should reflect recently available version for actions-runner-controller

**Screenshots**
**Environment (please complete the following information):**
**Additional context**

Just this :-).  Would like to update to 0.20.4 through standard means but AppVersion is still on 0.20.3.

**Comment by toast-gear** [comment]
We're currently testing HEAD and are aiming to do a release soon. If you wish to test out controller version `0.20.4` you can update your `image.tag` in your values.yaml to `v0.20.4`. `v0.20.4` didn't include any CRD changes and so should be safe to run on chart `version: 0.15.1`.

**Comment by jbkc85** [comment]
> We're currently testing HEAD and are aiming to do a release soon. If you wish to test out controller version `0.20.4` you can update your `image.tag` in your values.yaml to `v0.20.4`. `v0.20.4` didn't include any CRD changes and so should be safe to run on chart `version: 0.15.1`.

understood.  Is there a way to determine what the latest release 'is' then?  Because the release is created already, the image is out...will there be a specific CHANGELOG event, or should I assume that whatever is in the chart is the latest version that is not being tested?  Just wanting to know for future reference just in case I missed something else obvious :-)

**Comment by mumoshu** [comment]
@jbkc85 The latest controller release is 0.20.3. It's just that we don't fully synchronize controller releases with helm chart releases.
In other words, because it was a straight-forward patch release and I was too lazy, I had not conducted manual tests against the chart when I made 0.20.4 controller release.
