### ISSUE TITLE
runner sometime crashloop with "mv: inter-device move failed"

### ISSUE THREAD

**Issue by cspargo** [actions-runner-controller/actions-runner-controller#1065]
**Describe the bug**
Sometimes runners crashloop, and have this at the start of the logs.

```
Docker wait check skipped. Either Docker is disabled or the wait is disabled, continuing with entrypoint
Github endpoint URL https://github.com/
mv: inter-device move failed: '/runnertmp/bin' to '/runner/bin'; unable to remove target: Directory not empty
mv: inter-device move failed: '/runnertmp/externalstmp' to '/runner/externalstmp'; unable to remove target: Directory not empty
mv: inter-device move failed: '/runnertmp/patched' to '/runner/patched'; unable to remove target: Directory not empty
Configuring the runner.
```

I see there was a fix for this issue here https://github.com/actions-runner-controller/actions-runner-controller/pull/716
but that seems to have reverted later and changed back to use "mv"  https://github.com/actions-runner-controller/actions-runner-controller/commit/ec0915ce7c55c2ad263b60ba2b1c0a4ff7bec25d#diff-79187d0921cc40dbb8cc87debf9261df16066b0c4dd267dc4329312745ae3a98L70

**To Reproduce**
Just happens sometimes when runners start. I'm not sure what triggers that to happen.

**Expected behavior**
It should not crashloop and should not log those errors

**Environment (please complete the following information):**
 - Controller Version 0.20.0
 - Deployment Method Helm
 - Helm Chart Version 0.13.0
 - Runner 2.286.0

**Comment by mumoshu** [comment]
@cspargo Ah, good catch! Thanks for reporting. Would you mind submitting a PR to change it back to use `cp`?

**Comment by cspargo-apptio** [comment]
will do

**Comment by cspargo** [comment]
will do
