### ISSUE TITLE
Unable to Deploy runner pods, throws up error to specify resource limits, which is already in place.

### ISSUE THREAD

**Issue by shettarocknroll** [actions-runner-controller/actions-runner-controller#1071]
**Describe the bug**
Unable to Deploy runner pods, throws up error to specify resource limits, which is already in place (Pls see attachments).

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [x] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
Deploy the runners via the Runner or RunnerDeployment Kind.

**Expected behavior**
Expect the pods to pick up on the resource limit and request configuration specified and spin up

**Screenshots**
![image](https://user-images.githubusercontent.com/98391732/150961443-810f4cc2-fd3c-4316-9bf0-938532b88720.png)
![image](https://user-images.githubusercontent.com/98391732/150961724-1f247623-c5e6-43d0-8fa0-9ed9626426d5.png)
![image](https://user-images.githubusercontent.com/98391732/150961839-aae1a4af-3e91-41ef-88c8-6cc75e3c66e2.png)

**Environment (please complete the following information):**
 - AWS eks 21
 - Deployed via helm
 - Helm Chart Version - https://github.com/actions-runner-controller/actions-runner-controller/tree/master/charts/actions-runner-controller

**Additional context**
We are presently on GHES 3.1.14 which I believe should not be the culprit.

**Comment by mumoshu** [comment]
@shettarocknroll It seems like you're missing `dockerContainerReosources`
https://github.com/actions-runner-controller/actions-runner-controller/blob/b509eb4388cab249f2d88cad9c21220b86387385/api/v1alpha1/runner_types.go#L79

**Comment by mumoshu** [comment]
Closing this as answered 👍
