### ISSUE TITLE
Question: pass additionalVolumes to helm chart

### ISSUE THREAD

**Issue by exploiz65** [actions-runner-controller/actions-runner-controller#1084]
I saw there is a feature to pass additionalVolumes to the helm chart. I am not sure how to pass an additionalVolume to the helm cli as its not documented. I want to pass this:

- name: ssl-cert
        secret:
          secretName: ssl-cert

What i tried:

--set additionalVolumes='[{"name":"ssl-cert","secret":{"secretName":"ssl-cert"}}]'

But this is not working. Could you please help me :)

**Comment by mumoshu** [comment]
Try `--set additionalVolumes[0].name=ssl-cert --set additionalVolumes[0].secret.secretName=ssl-cert` :)

**Comment by exploiz65** [comment]
thank you so much @mumoshu
