### ISSUE TITLE
Question: Docs about  metrics available for Prometheus

### ISSUE THREAD

**Issue by Moser-ss** [actions-runner-controller/actions-runner-controller#1111]
Do we have any kind of documentation about the metrics that are exposed by the controller?

I saw this metric `controller_runtime_active_workers` but I cannot understand the meaning of this metric, I initially I was think that counting the number of active runners but that doesn't look true

**Comment by mumoshu** [comment]
@Moser-ss It seems like those `controller_runtime_` metrics are emitted automatically by controller-runtime that ARC uses internally as a framework for K8s controllers. You can refer to the API docs of controller-runtime at https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/internal/controller/metrics for explanations on those metrics.

**Comment by Moser-ss** [comment]
Thanks for the info. I need to track the number of active Runners. 

Does it make sense to add to the controller a routine that scraps the total number of runners, the available runners, and the busy runners? 

I was initially trying to add that feature inside of the reconcile loop that we have in the` func (r *HorizontalRunnerAutoscalerReconciler) suggestDesiredReplicas` but then I understood that loop only runs if the `HorizontalRunnerAutoscaler` has the metrics `PercentageRunnersBusy`

If in your opinion could make sense for a controller to keep scrap data about Runners , I will work on that feature
