### ISSUE TITLE
Why two separate release paths? 16.x and 21.x

### ISSUE THREAD

**Issue by chinmaya-n** [actions-runner-controller/actions-runner-controller#1130]
Hi,

I tried to find some documentation or discussion regarding why there are two separate release paths? `16.x` and `> 20.x` . I would appreciate if someone can point me in the right direction.

I am currently using `16.x` and would like to know more before I upgrade to the `21.x`. I am exited about the Stateful Runners!

Thanks,
Chinmaya

**Comment by mumoshu** [comment]
Anything prefixed with `actions-runner-controller-` like 0.16.x is a chart release and releases with only tag names are for controller releases!

Also note that RunnerSet needs https://github.com/actions-runner-controller/actions-runner-controller/pull/1126 to scale down reliably when you use webhook-based scaling.
