### ISSUE TITLE
Chart version 0.16.0 Causing Errors on kubectl Apply When upgrading controller to v0.21.1

### ISSUE THREAD

**Issue by rxa313** [actions-runner-controller/actions-runner-controller#1157]
Doing some testing in my non-production rancher environment and I'm trying to upgrade my controller to `v0.21.1` 

I'll note I was able to successfully upgrade to controller `v0.21.1` following the instructions to the latest controller version using the chart version `0.14.0` -  however, I wanted to do some testing using the latest chart version located in the [Chart.yml](https://github.com/actions-runner-controller/actions-runner-controller/blob/v0.21.1/charts/actions-runner-controller/Chart.yaml#L18) (`0.16.0`) for tag `v0.21.1`

The error I'm seeing when I go to apply the crds is:
```
Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "runners.actions.summerwind.dev", Namespace: ""
for: "crds/actions.summerwind.dev_runners.yaml": CustomResourceDefinition.apiextensions.k8s.io "runners.actions.summerwind.dev" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

When upgrading, should we follow the latest chart version located in the Chart.yml, or what you all are specifying in the [UPGRADING.md](https://github.com/actions-runner-controller/actions-runner-controller/blob/v0.21.1/charts/actions-runner-controller/docs/UPGRADING.md) ?

Thanks!

**Comment by mumoshu** [comment]
@rxa313 Hey! Maybe we missed updating our docs but you'd need to use `kubectl replace` instead. See https://github.com/actions-runner-controller/actions-runner-controller/issues/1102

**Comment by admin-checkpoint** [comment]
Getting a similar issue now 

**kubectl apply -f crds/**  

```
Warning: resource customresourcedefinitions/horizontalrunnerautoscalers.actions.summerwind.dev is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/horizontalrunnerautoscalers.actions.summerwind.dev configured
Warning: resource customresourcedefinitions/runnersets.actions.summerwind.dev is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
customresourcedefinition.apiextensions.k8s.io/runnersets.actions.summerwind.dev configured
Error from server (Invalid): error when creating &quot;crds/actions.summerwind.dev_runnerdeployments.yaml&quot;: CustomResourceDefinition.apiextensions.k8s.io &quot;runnerdeployments.actions.summerwind.dev&quot; is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (Invalid): error when creating &quot;crds/actions.summerwind.dev_runnerreplicasets.yaml&quot;: CustomResourceDefinition.apiextensions.k8s.io &quot;runnerreplicasets.actions.summerwind.dev&quot; is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (Invalid): error when creating &quot;crds/actions.summerwind.dev_runners.yaml&quot;: CustomResourceDefinition.apiextensions.k8s.io &quot;runners.actions.summerwind.dev&quot; is invalid: metadata.annotations: Too long: must have at most 262144 bytes</pre>
```

**kubectl replace -f crds/**

```
customresourcedefinition.apiextensions.k8s.io/horizontalrunnerautoscalers.actions.summerwind.dev replaced
customresourcedefinition.apiextensions.k8s.io/runnersets.actions.summerwind.dev replaced
Error from server (NotFound): error when replacing "crds/actions.summerwind.dev_runnerdeployments.yaml": customresourcedefinitions.apiextensions.k8s.io "runnerdeployments.actions.summerwind.dev" not found
Error from server (NotFound): error when replacing "crds/actions.summerwind.dev_runnerreplicasets.yaml": customresourcedefinitions.apiextensions.k8s.io "runnerreplicasets.actions.summerwind.dev" not found
Error from server (NotFound): error when replacing "crds/actions.summerwind.dev_runners.yaml": customresourcedefinitions.apiextensions.k8s.io "runners.actions.summerwind.dev" not found
```

**Comment by rxa313** [comment]
Hey @mumoshu sorry for the delay, thanks for your response. Using `kubectl replace` worked great for me. 

<img width="753" alt="Screen Shot 2022-03-01 at 9 06 41 AM" src="https://user-images.githubusercontent.com/74605500/156184114-3f593d4e-78c8-426a-9407-eacfdc22fc01.png">

<img width="537" alt="Screen Shot 2022-03-01 at 9 06 22 AM" src="https://user-images.githubusercontent.com/74605500/156184141-f98c5441-1882-4061-8191-ded0877b6120.png">

@admin-checkpoint I'm not sure how you are installing or what your installation is like; make sure you have a controller already installed in your namespace.. it looks like you're missing some crds. I suggest using:
 `kubectl describe crds |grep actions` to gain some insight.

**Comment by mumoshu** [comment]
@admin-checkpoint You'd need to use `kubectl create -f -` if it's the first install.
