### ISSUE TITLE
can't delete runnerSet

### ISSUE THREAD

**Issue by shichengripple001** [actions-runner-controller/actions-runner-controller#1158]
**Describe the bug**
error from controller when delete RunnerSet

2022-02-25T03:20:02.778Z	ERROR	controller-runtime.manager.controller.runnerpod-controller	Reconciler error	{"reconciler group": "", "reconciler kind": "Pod", "name": "self-built-runner-test-3", "namespace": "actions-runner-system", "error": "enterprise, organization and repository are all empty"}

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.18.2]
 - Deployment Method [e.g. Helm and Kustomize ]
 - Helm Chart Version [e.g. 0.11.0, if applicable]

**Additional context**

**Comment by mumoshu** [comment]
Please specify any of enterprise, organization, and repository in your runnerset's template spec, as said in the error message . Thank you!

**Comment by shichengripple001** [comment]
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: self-built-runner-test
spec:
  replicas: 1
  repository: shichengxxxxx001/xxxx-clone-1
  dockerdWithinRunnerContainer: false
  dockerEnabled: true
  workDir: /work-2
  ephemeral: false
  labels:
    - self-hosted
    - self-built-ubuntu
  serviceName: self-built-runner-test
  selector:
    matchLabels:
      app: self-built-runner-test
  template:
    metadata:
      labels:
        app: self-built-runner-test
    spec:
      imagePullSecrets:
      - name: docker
      securityContext:
        fsGroup: 20566
      containers:
      - name: docker
        resources:
          limits:
            cpu: "16.0"
            memory: "32Gi"
          requests:
            cpu: "16.0"
            memory: "32Gi"
      - name: runner
        volumeMounts:
        #- mountPath: /work-2
        #  name: work
        image: registry.gitlab.com/xxxxxx/demo:ubuntu18clang10
        env: []
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "4.0"
            memory: "8Gi"
          requests:
            cpu: "2.0"
            memory: "4Gi"
  volumeClaimTemplates:
  - metadata:
      name: work-2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 50Gi

**Comment by shichengripple001** [comment]
it has been specified

**Comment by mumoshu** [comment]
Tahnks. Your RunnerSet spec does seem to miss those fields so can I consider this as a feature request to add a validating webhook to prevent you from mistakenly creating a RunnerSet doesn't have any of enterprise ,organization, and repository?

**Comment by shichengripple001** [comment]
but i have "repository: shichengxxxxx001/xxxx-clone-1" in the yaml, could you please highlight which field am I missing?

**Comment by mumoshu** [comment]
@shichengripple001 Ah, thanks! I missed that. Well, then this shouldn't happen. Perhaps you missed specifying it when you initially created RunnerSet and then updated it to have `repository` field specified?

**Comment by shichengripple001** [comment]
that is not the case, only thing I have updated is replica, i will update here if I find a way to reproduce

**Comment by mumoshu** [comment]
@shichengripple001 What's your version of actions-runner-controller (image tag) and the chart version?

**Comment by shichengripple001** [comment]
![Screenshot 2022-02-28 at 8 48 10 AM](https://user-images.githubusercontent.com/97218929/155907743-542012b6-537e-4b93-8e17-3dad1db96fc8.png)

summerwind/actions-runner-controller:v0.20.3

here is the chart version and controller image I am using

**Comment by shichengripple001** [comment]
ku get po|grep self-built-runner-test|awk '{print $1}'|xargs kubectl delete po
it is happening again when run the above command

**Comment by mumoshu** [comment]
@shichengripple001 Thanks. Would you mind sharing `kubectl get po -o yaml` output for the runner pod?

**Comment by shichengripple001** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    actions-runner-controller/token-expires-at: "2022-02-28T11:35:29+08:00"
    cni.projectcalico.org/containerID: 5f07ab7fa50bfb972ddb9ad3f7a71f273ee60514a308dca93cbfa4543e80d9ce
    cni.projectcalico.org/podIP: 172.16.89.141/32
    cni.projectcalico.org/podIPs: 172.16.89.141/32
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-02-28T03:03:03Z"
  finalizers:
  - actions.summerwind.dev/runner-pod
  generateName: self-built-runner-test-
  labels:
    actions-runner-controller/inject-registration-token: "true"
    app: self-built-runner-test
    controller-revision-hash: self-built-runner-test-bbb74c7b7
    runner-template-hash: 58674db76b
    runnerset-name: self-built-runner-test
    statefulset.kubernetes.io/pod-name: self-built-runner-test-0
  name: self-built-runner-test-0
  namespace: actions-runner-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: self-built-runner-test
    uid: 6614f882-3b7b-4406-93a7-b82e18570593
  resourceVersion: "5978297"
  uid: 3bd25948-01cb-4873-acd3-d2fafc4cdb50
spec:
  containers:
  - env:
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    image: docker:dind
    imagePullPolicy: IfNotPresent
    name: docker
    resources:
      limits:
        cpu: "16"
        memory: 32Gi
      requests:
        cpu: "16"
        memory: 32Gi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /work-2
      name: work
    - mountPath: /runner
      name: runner
    - mountPath: /certs/client
      name: certs-client
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5ccrp
      readOnly: true
  - env:
    - name: RUNNER_ORG
    - name: RUNNER_REPO
      value: xxxxx/xxxxxxx-clone-1
    - name: RUNNER_ENTERPRISE
    - name: RUNNER_LABELS
      value: self-hosted,self-built-ubuntu
    - name: RUNNER_GROUP
    - name: DOCKERD_IN_RUNNER
      value: "false"
    - name: GITHUB_URL
      value: https://github.com/
    - name: RUNNER_WORKDIR
      value: /work-2
    - name: RUNNER_EPHEMERAL
      value: "false"
    - name: DOCKER_HOST
      value: tcp://localhost:2376
    - name: DOCKER_TLS_VERIFY
      value: "1"
    - name: DOCKER_CERT_PATH
      value: /certs/client
    - name: RUNNER_NAME
      value: self-built-runner-test-0
    - name: RUNNER_TOKEN
      value: AXFXC4LAJ5QT65PGOQQVVMLCDRBQC
    image: xxxxxxxx:ubuntu18clang10
    imagePullPolicy: Always
    name: runner
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi
    securityContext:
      privileged: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /runner
      name: runner
    - mountPath: /work-2
      name: work
    - mountPath: /certs/client
      name: certs-client
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5ccrp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: self-built-runner-test-0
  imagePullSecrets:
  - name: docker
  nodeName: ip-192-168-82-202.ap-southeast-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 20566
  serviceAccount: default
  serviceAccountName: default
  subdomain: self-built-runner-test
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: work-2
    persistentVolumeClaim:
      claimName: work-2-self-built-runner-test-0
  - emptyDir: {}
    name: runner
  - emptyDir: {}
    name: work
  - emptyDir: {}
    name: certs-client
  - name: kube-api-access-5ccrp
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

**Comment by mumoshu** [comment]
@shichengripple001 Thanks! Could you swap the runner and the docker containers in the runnerset.spec.template.containers`? `runner` container needs to be at index 0 but you seem to have `docker` there instead.

**Comment by shichengripple001** [comment]
@mumoshu thanks! the issue is gone after moved runner container to first container.

**Comment by mumoshu** [comment]
@shichengripple001 glad to hear it worked! thanks for reporting.
