### ISSUE TITLE
Containers stuck at ContainerCreating

### ISSUE THREAD

**Issue by kdi-sag** [actions-runner-controller/actions-runner-controller#1165]
**Describe the bug**
On Azure EKS, we used to have a kubectl-installed actions-runner-controller which worked perfectly. Then we needed to use the helm installer with the chart's data. After installation, the container gets stuck at ContainerCreating.

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Install actions-runner-controller using `kubectl apply -f https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.20.2/actions-runner-controller.yaml`
2. Uninstall it using `kubectl delete -f https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.20.2/actions-runner-controller.yaml`
3. Install using the `helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
helm upgrade --install --namespace actions-runner-system --create-namespace \
             --wait actions-runner-controller actions-runner-controller/actions-runner-controller`.
4. Controller gets stuck at ControllerCreating.
5. See error of `kubectl describe pod`:
```
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  41m (x12 over 166m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[secret], unattached volumes=[kube-api-access-q6phx secret tmp cert]: timed out waiting for the condition
  Warning  FailedMount  20m (x36 over 170m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[secret], unattached volumes=[secret tmp cert kube-api-access-q6phx]: timed out waiting for the condition
  Warning  FailedMount  11m (x14 over 175m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[secret], unattached volumes=[tmp cert kube-api-access-q6phx secret]: timed out waiting for the condition
  Warning  FailedMount  7m8s (x9 over 172m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[secret], unattached volumes=[cert kube-api-access-q6phx secret tmp]: timed out waiting for the condition
  Warning  FailedMount  2m14s (x94 over 177m)  kubelet  MountVolume.SetUp failed for volume "secret" : secret "controller-manager" not found
```

**Expected behavior**
Expected to create a pod.

**Screenshots**
// No screenshots

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.18.2] - v0.20.2
 - Deployment Method [e.g. Helm and Kustomize ] = Kustomize and Helm
 - Helm Chart Version [e.g. 0.11.0, if applicable]

**Additional context**
// No additional context

**Comment by kdi-sag** [comment]
Hello,

The issue was caused because of missing secrets related to App information. After adding the and then deleting the pod, everything started working.

**Comment by kichik** [comment]
For anyone else seeing the same issue, this is the missing command:

```
$ kubectl create secret generic controller-manager \
    -n actions-runner-system \
    --from-literal=github_app_id=${APP_ID} \
    --from-literal=github_app_installation_id=${INSTALLATION_ID} \
    --from-file=github_app_private_key=${PRIVATE_KEY_FILE_PATH}
```

When using Helm, you can use `--set authSecret.github_app_id=xxx --set authSecret.github_app_installation_id=yyy --set authSecret.github_app_private_key=zzz`.

When using GitHub PAT, use `--set authSecret.github_token=xxx`.

The relevant part of the documentation comes right after the commands to install the chart.

https://github.com/actions-runner-controller/actions-runner-controller#deploying-using-github-app-authentication

If any maintainer is reading this, can we maybe add a note in the documentation about required parameters or the fact that the chart is not ready until this is done?

**Comment by mumoshu** [comment]
@kichik Thanks for reporting! Would you mind contributing the doc update?

**Comment by joshjohanning** [comment]
Or if using the `values.yaml` file, need to set `create: true` in order to actually create the secret

```yml
authSecret:
  enabled: true
  create: true
  name: "controller-manager"
  annotations: {}
  github_token: "xxx"
```

Describing the pod helped me figure out the secret was missing and that it needs to create. Thanks

**Comment by JLHasson** [comment]
I received this error when the controller hadn't fully started up yet. I also saw the `FailedMount` error, but after confirming that the secret was set and giving the service a few more mins it started successfully after which I was able to launch the runner deployment 👌

**Comment by sehz** [comment]
Ran into same issue.  This should be described in the doc or troubshooting guide

**Comment by Link-** [comment]
@joshjohanning - you leaked a personal access token in this thread. Please make sure it's revoked and taken out of rotation!

**Comment by joshjohanning** [comment]
> @joshjohanning - you leaked a personal access token in this thread. Please make sure it's revoked and taken out of rotation!

💯
