### ISSUE TITLE
Support Specifying Registration Token Directly

### ISSUE THREAD

**Issue by mcalhoun** [actions-runner-controller/actions-runner-controller#1172]
### Problem Statement

Currently, the project supports providing a Github Personal Access Token (PAT) and uses that token to call the Github API to request a Runner registration token. Using this method requires users to create and store a privileged (Admin scoped) token that has more permissions than it requires.

### Requested Feature

Github now supports obtaining a scoped (Organization or Repository) registration token directly through the UI, which would eliminate the need for any kind of long-lived credentials to be stored. It would be great if we could specify the registration token rather than a PAT and the `actions-runner-controller` could just use the registration token directly rather than using the API to obtain one.

#### How to Obtain the Registration Token

1. Browse to [https://github.com/organizations/{Org}/settings/actions/runners](https://github.com/organizations/%7BOrg%7D/settings/actions/runners) (Organization) or [https://github.com/{Org}/{Repo}/settings/actions/runners](https://github.com/%7BOrg%7D/%7BRepo%7D/settings/actions/runners) (Repository)
1. Click the New Runner button (Organization) or New Self Hosted Runner button (Repository)
1. Copy the Github Runner token from the next screen. Note that this is the only time you will see this token. Note that if you exit the New {Self Hosted} Runner screen and then later return by clicking the New {Self Hosted} Runner button again, the registration token will be invalidated and a new token will be generated. 

![image](https://user-images.githubusercontent.com/930247/156398724-586eca7b-0612-49a9-97d7-a2f6bcb5de8a.png)

**Comment by mumoshu** [comment]
@mcalhoun Hey! You'd still need a PAT or App for other important API calls like made by ARC, like DeleteRunner, ListRunners, ListWorkflowJobs, etc. so this doesn’t much make sense.

**Comment by mcalhoun** [comment]
Ahh...this actually makes sense since you are operating externally on the runners rather than calling the following within the runner itself:

```bash
./config.sh --unattended --url https://github.com/${github_org} --token $registration_token
./config.sh remove --unattended --token $registration_token
```

In the scenario above (calling register/deregister) within the container, it's possible to handle registration/deregistration without a PAT/Github App.

I'm wondering if the approach of the ARC could be altered to handle the registration and deregistration within the entrypoint script (by trapping SIGINT and SIGTERM) and therefore eliminating the need to call the Github APIs directly? 

I'm not familiar enough with the internal workings to know if this is a possibility, but eliminating the need to have permanent credentials for the ARC would go a long way towards more of our customers adopting its use. Thanks!

**Comment by mumoshu** [comment]
> calling the following within the runner itself:

@mcalhoun Hey! That is 50% correct. We do handle runner removal externally but for registration, we use vanilla `config.sh`.

Additionally, and you may already know, but when you use ephemeral runners, you don't need to explicitly remove the runner- it de-registers itself after the job run. So I'm still unsure how making it handle SIGTERM to de-register makes much difference.

I believe ARC's values reside in autoscaling and runner replicas management, which requires either PAT or GitHub App to call other GitHub Actions APIs. So just moving the de-registration process to a SIGTERM handler within the runner pod doesn't automatically remove the necessity of PAT and GitHub App as you originally wanted.

If you definitely don't need autoscaling or replicas management, that means you can just deploy your own runner pod by wrapping the upstream [actions/runner](https://github.com/actions/runner) into a container image, without ARC. I'm unsure how ARC can help that use-case 🤔

Maybe I'm missing something? Would you mind confirming?

**Comment by mumoshu** [comment]
Closing this as answered. But please feel free to reopen if I’m still missing something!

**Comment by mumoshu** [comment]
@Nuru The registration token eventually expires so it won't work in long run. Also, webhook delivery isn't guaranteed having an option to combine webhook-based autoscaling with metrics-based autoscaling might be useful for some folks(although not required).

**Comment by Nuru** [comment]
@mumoshu I had heard that the token lasted longer, but now I found [official documentation](https://docs.github.com/en/rest/actions/self-hosted-runners#create-a-registration-token-for-a-repository) that says the token generated on the web page is only valid for 1 hour, so you are right, it is not a solution. Thank you for the explanation.

**Comment by mumoshu** [comment]
@Nuru Thanks for confirming! Let's ask GitHub to add more granular permission for that so that we no longer need admin access.
