### ISSUE TITLE
Arm64 Canary docker images include wrong architecture for github-webhook-server

### ISSUE THREAD

**Issue by msessa** [actions-runner-controller/actions-runner-controller#1184]
**Describe the bug**
While attempting to run `canary` docker images on a Arm64 cluster, the `github-webhook-server` pods fail to start with the following error:
`standard_init_linux.go:228: exec user process caused: exec format error`

Meanwhile, the `manager` binary works correctly.

I suspect an issue with env var scoping on this line which fails to produce Arm64 targets:
https://github.com/actions-runner-controller/actions-runner-controller/blob/bed927052dab1cfaa229ac6878a3a614f92b6750/Dockerfile#L40

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [x] I'm using an unreleased version of the controller I built from HEAD of the default branch

**Environment (please complete the following information):**
 - Controller Version: bed9270
 - Deployment Method: helm
 - Helm Chart Version: 0.16.1

**Comment by mumoshu** [comment]
Thanks for reporting! I think I had to `export` these go-related envvars to the githubwebhookserver build.

https://github.com/actions-runner-controller/actions-runner-controller/blob/b57e885a7317268516d5729cdb491aa1c97134c2/Dockerfile#L39

**Comment by mumoshu** [comment]
@msessa Fixed. Would you mind giving it a shot once again? Thanks!

**Comment by msessa** [comment]
@mumoshu, works great now thanks for fixing it.

I'll run canary for a few days and I'll report any issue I may encounter
