### ISSUE TITLE
Use the `--ephemeral` flag by default

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#1189]
**Context**
The flag `--ephemeral` has been the standard flag for a while and we should migrate to using it by default now that GHES 3.3 has been out for over 3 months.

Currently, a runner is configured with the `--once` flag unless the runner has the environment variable `RUNNER_FEATURE_FLAG_EPHEMERAL: "true"` set. This env var should be changed to be `ENABLE_LEGACY_EPHEMERAL: "true"` which results in the runner being configured with the `--once` flag instead of the default `--ephemeral` flag.

The bulk of the work has been done on PR https://github.com/actions-runner-controller/actions-runner-controller/pull/831, it just needs updating to use the desired env var name and the docs need updating:

1. the new flag needs adding in https://github.com/actions-runner-controller/actions-runner-controller#runner-entrypoint-features
2. The `Ephemeral Runner` section needs turning into `Static Runners` as by default our runners are ephemeral. The configuration option is `ephemeral: false` and so that's what needs documenting.

EDIT edited to reflect ethmoson's comment

**Comment by ethomson** [comment]
> The Ephemeral Runner section needs turning into Long-Lived Runners (or something like that) as by default our runners are ephemeral. The configuration option is ephemeral: false and so that's what needs documenting.

The Actions team uses the term _static runners_ as the opposing notion to ephemeral runners.

**Comment by toast-gear** [comment]
OK new-ish plan. We are going to remove the `--once` flag entirely in the subsequent release to this issue being released (due to be part of the next milestone to be released).

Tasks:
 - Update controller to set `RUNNER_FEATURE_FLAG_EPHEMERAL` to `true` as part of a runner creation
 - Update docs to highlight this change as well as highlight `--once` is being removed
 - Update runner entrypoint to highlight --once is deprecated
