### ISSUE TITLE
Remove the ability to use the `--once` flag entirely only allowing `--ephemeral` to be set

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#1196]
At the moment you can pick between where your ephemeral runners will be configured witwh the legacy `--once` flag or the supported new `--ephemeral` flag. We are not aware of any reason to use the `--once` flag, the only discussion we've seen on it is here https://github.com/actions/runner/issues/1339 and it is centred around rate limiting which we don't think will be an issue. 

We also state in the docs that ARC requires => 3.3 which supports the `--ephemeral` flag.

If you are running a GHES environment you **need** to upgrade your GHES instance to => version 3.3 if you wish to maintain an ARC upgrade path and not have down time. In order to remove the --once flag we will need to remove the logic from our runner container [[1]](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/entrypoint.sh#L166-L170) [[2]](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/entrypoint.sh#L90-L93), this will be done at the point of the linked milestone being released and so if you are using the latest tag or build a custom container from ours you will be impacted effectively at a random time. Migration notes:

1. Just upgrade to GHES => 3.3 and everything will continue to work (it was released on 07-12-2021)
2. If you won't / can't you will need to move to persistent runners via setting the attribute `ephemeral: false`, this will create a significant change in behaviour and so has impacts you may not desire.
3. Provde your own image from scratch not built from ARC's allowing you to set the `--once` flag as part of your images entrypoint (don't expect tonnes of help from ARC if you go this direction)

This issue is to be done in the subsequent release to https://github.com/actions-runner-controller/actions-runner-controller/issues/1189

**Comment by mumoshu** [comment]
We ended by making `--ephemeral` the default and adding the new option to stick with `--once` instead.
We'll probably leave the new option for a while, but don't expect it to work forever. GitHub Actions and actions/runner may eventually remove the support for `--once`.
Before they remove it, upgrade to a newer version of GHES, ASAP!

**Comment by mumoshu** [comment]
Let's keep this open until we completely remove the support for `--once`.
