### ISSUE TITLE
helm chart -> DO ClusterLint Error

### ISSUE THREAD

**Issue by thehungrycoder** [actions-runner-controller/actions-runner-controller#1205]
I use the helm chart in DOKS. I get this error by their ClusterLint
![Screen Shot 2022-03-11 at 8 32 26 AM](https://user-images.githubusercontent.com/79018/157877951-affa3bcc-5970-4529-8357-c3d071c44e94.png)

In [their guide it is mentioned](https://docs.digitalocean.com/products/kubernetes/resources/clusterlint-errors/#admission-controller-webhook-replacement), it's possible to get this error if `FailurePolicy: Fail` which is the value I see set in [the chart.](https://github.com/actions-runner-controller/actions-runner-controller/blob/3de4e7e9c650156f35f295f01158d901316d91bf/charts/actions-runner-controller/templates/webhook_configs.yaml#L151). 

Also for sometime cluster (nodes) doesn't automatically scale (down) correctly. While I'm not 100% whether this is the cause but the rough timeline matches from when I installed this controller.

**Comment by mumoshu** [comment]
> FailurePolicy: Fail

This is required by our `RunnerSet` to function at all, as it injects runner tokens into runner pods via mutating webhook.
If that's a real issue, try deleting mutatingwebhookconfiguration from your cluster and only use `RunnerDeployment`.

> Also for sometime cluster (nodes) doesn't automatically scale (down) correctly

If you use cluster-autoscaler, `kubeclt logs` output for the CA pod would help debug this kind of issue. If it doesnt' help, try increasing the verbosity level of CA.
