### ISSUE TITLE
[Question] `no matches for kind "Issuer" in version "cert-manager.io/v1`

### ISSUE THREAD

**Issue by hitech95** [actions-runner-controller/actions-runner-controller#121]
Hi, I have cert manager installed CRDS are present but the deployment fails.

````
$kubectl apply -f https://github.com/summerwind/actions-runner-controller/releases/latest/download/actions-runner-controller.yaml  
namespace/actions-runner-system created
customresourcedefinition.apiextensions.k8s.io/horizontalrunnerautoscalers.actions.summerwind.dev created
customresourcedefinition.apiextensions.k8s.io/runnerdeployments.actions.summerwind.dev created
customresourcedefinition.apiextensions.k8s.io/runnerreplicasets.actions.summerwind.dev created
customresourcedefinition.apiextensions.k8s.io/runners.actions.summerwind.dev created
role.rbac.authorization.k8s.io/leader-election-role created
clusterrole.rbac.authorization.k8s.io/manager-role created
clusterrole.rbac.authorization.k8s.io/proxy-role created
rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/proxy-rolebinding created
service/controller-manager-metrics-service created
service/webhook-service created
deployment.apps/controller-manager created
mutatingwebhookconfiguration.admissionregistration.k8s.io/mutating-webhook-configuration created
validatingwebhookconfiguration.admissionregistration.k8s.io/validating-webhook-configuration created
unable to recognize "https://github.com/summerwind/actions-runner-controller/releases/latest/download/actions-runner-controller.yaml": no matches for kind "Certificate" in version "cert-manager.io/v1"
unable to recognize "https://github.com/summerwind/actions-runner-controller/releases/latest/download/actions-runner-controller.yaml": no matches for kind "Issuer" in version "cert-manager.io/v1"     
$
```

I'm a bit new with k8s, any idea on what the issue could be?

**Comment by BrendanGalloway** [comment]
Hi - I hit the same issue.  Are the Issuer and Certificate provided by your cert-manager actually v1?  To check this you can use `kubectl get crd issuers` and look at the Spec.Versions.Name field.  If they are not, you can either change the resource definition in the CRD to set the apiVersion to what your cluster provides (this seems to be working for us so far with cert-manager.io/v1alpha2), or upgrade your cert-manager to a version that provides the v1 API.

**Comment by hitech95** [comment]
> 
> 
> Hi - I hit the same issue. Are the Issuer and Certificate provided by your cert-manager actually v1? To check this you can use `kubectl get crd issuers` and look at the Spec.Versions.Name field. If they are not, you can either change the resource definition in the CRD to set the apiVersion to what your cluster provides (this seems to be working for us so far with cert-manager.io/v1alpha2), or upgrade your cert-manager to a version that provides the v1 API.

I'll take a look, cert manasger is provided by the k8s infrastructure itself, (its a "half managed" system).
I'll take a look and I'll see if I can update the cert manager

**Comment by Nuru** [comment]
[`cert-manager`](https://github.com/jetstack/cert-manager) only recently graduated to a stable public API, version 1.0.0, so your cluster may be using an older version. The recent 0.x versions used API `cert-manager.io/v1alpha2` while the 1.0.0 and later versions use `cert-manager.io/v1`. The current action-runner-controller requires cert-manager 1.x.

**Comment by kaykhancheckpoint** [comment]
@hitech95 i ran into the same problem, what did you do to fix this?

**Comment by jeffj254** [comment]
I fixed this by installing the latest version of cert-manager

**Comment by callum-tait-pbx** [comment]
cert-manager went 1.0 and the repo was updated to use the new API end points. Are you sure you are runing a compatible cert-manager to actions-runner-controller combination?

PR where actions-runner-controller started expected cert-manager 1.0 to be deployed https://github.com/summerwind/actions-runner-controller/pull/94 this was part of the v0.8.0 release
