### ISSUE TITLE
Attempting to reclaim ephemeral-storage

### ISSUE THREAD

**Issue by kaykhancheckpoint** [actions-runner-controller/actions-runner-controller#1215]
I have a K8s cluster via AWS EKS. I have a set of nodes which are m5.xlarge backed by an EBS volume (100gb)

I have self hosted runner that is doing some database backup and restore. However during the process, k8s reports the following error:

```
v1/nodes error
Error Occurred in Node: ip-10-0-1-54.us-east-2.compute.internal in prod-k8s cluster
Attempting to reclaim ephemeral-storage

v1/pods error
Error Occurred in Pod: actions-runner-system/github-runner-jnp9m-2rwsr in prod-k8s cluster
The node was low on resource: ephemeral-storage. Container docker was using 80Ki, which exceeds its request of 0. Container runner was using 84096Ki, which exceeds its request of 0. 

Error Occurred in Node: ip-10-0-1-54.us-east-2.compute.internal in prod-k8s cluster
failed to garbage collect required amount of images. Wanted to free 11069618585 bytes, but freed 0 bytes
```

I have narrowed down the error, it occurs when i do a sed command. data.sql is maybe 20gb~ in size.

```
sed -i 's/original_db_name/new_db_name/g' data.sql
```

Is there anything i can do to configure the runner that might help with this issue?

**Comment by mumoshu** [comment]
@kaykhancheckpoint It seems like you need to set proper request/limit on ephemeral-storage https://github.com/kubernetes/kubernetes/issues/91600#issuecomment-1055325257

**Comment by kaykhancheckpoint** [comment]
@mumoshu thanks i will look into this later, although i think i managed to solve my problem by not having to use this sed command in the first place.
