### ISSUE TITLE
The webhook driven deployment part in README seems out of date.

### ISSUE THREAD

**Issue by siyuan0322** [actions-runner-controller/actions-runner-controller#1239]
**Describe the bug**
Hi everyone, I'm trying to autoscaling my CI runners, and I was following the README. In the README, the helm command to install webhook driven deployment is
```bash
$ helm upgrade --install --namespace actions-runner-system --create-namespace \
             --wait actions-runner-controller actions-runner-controller/actions-runner-controller \
             --set "githubWebhookServer.enabled=true,githubWebhookServer.ports[0].nodePort=33080"
```
But it seems the [Service](https://github.com/actions-runner-controller/actions-runner-controller/blob/c06a806d759f0a83b8b5b03942dd9dc42b521f7e/charts/actions-runner-controller/values.yaml#L206) type in `values.yaml` is `ClusterIP`, and the `Ingress` has been added.
I'm wondering has the recommended way to expose the port been changed from `NodePort` to `Ingress`?

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [x] I'm using an unreleased version of the controller I built from HEAD of the default branch

**Expected behavior**
The command in README will create a `ClusterIP` service, the expected service should be a `NodePort`.

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.22.0]
 - Deployment Method [e.g. Helm ]
 - Helm Chart Version [e.g. 0.17.0]

**Additional context**

**Comment by toast-gear** [comment]
>  I'm wondering has the recommended way to expose the port been changed from NodePort to Ingress?

this is entirely environmental, there isn't a "best way" to expose the wbhook server
