### ISSUE TITLE
Just want to ask, if ARC's webhook scaling can scale to zero work nodes? 

### ISSUE THREAD

**Issue by yourmoonlight** [actions-runner-controller/actions-runner-controller#1254]
Since our CI node's instanceType is large and expensive, 
So just wonder if we use webhook scaling feature，is it possible to reduce the expensive cost by scaling down to zero worker nodes during the idle time。

**Comment by mumoshu** [comment]
You should be able to. Try cluster-autoscaler or karpenter(AWS). But that's out of the scope of ARC itself.
