### ISSUE TITLE
Get Renovate to bump all RUNNER_VERSION references when bumping the version

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#1278]
We declare the runner version in a few spots but only bump the pipeline reference currently. It would be great if our Renovate setup could patch all references when raising a runner version bump, current locations:

* https://github.com/actions-runner-controller/actions-runner-controller/blob/master/.github/workflows/runners.yml#L18
* https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Makefile#L7
* https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Dockerfile#L4
* https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Dockerfile.dindrunner#L4

**Comment by danxmoran** [comment]
I'd be interested in taking this one
