### ISSUE TITLE
Error creating RunnerDeployment

### ISSUE THREAD

**Issue by shankarRaman** [actions-runner-controller/actions-runner-controller#1281]
**Describe the bug**
When trying to create RunnerDeployment object, we are encountering the following error
```
horizontalrunnerautoscaler.actions.summerwind.dev/krogertechnology-runner-deployment-autoscaler unchanged
Error from server (InternalError): error when applying patch:
{"spec":{"template":{"spec":{"resources":{"requests":{"cpu":"0.0"}}}}}}
to:
Resource: "actions.summerwind.dev/v1alpha1, Resource=runnerdeployments", GroupVersionKind: "actions.summerwind.dev/v1alpha1, Kind=RunnerDeployment"
Name: "krogertechnology-runner-deployment", Namespace: "almrunner"
for: "runner-deployment-cdc.yaml": Internal error occurred: failed calling webhook "mutate.runnerdeployment.actions.summerwind.dev": Post "https://webhook-service.actions-runner-system.svc:443/mutate-actions-summerwind-dev-v1alpha1-runnerdeployment?timeout=30s": x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "serial:56726364899828905982415242427572306586"
```
All the resources have been running for the last 1 year without issues. The CA cert is valid and the CA Bundle value matches the secret used. 
**Checks**

- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**Expected behavior**
Successfully  deploy  the manifest and see the runners spawned

**Environment (please complete the following information):**
 - Controller Version v0.3.0
 - Deployment Method - kubectl

**Comment by toast-gear** [comment]
> Controller Version v0.3.0

Is this your actual controller version? https://github.com/actions-runner-controller/actions-runner-controller/releases/tag/v0.3.0

**Comment by shankarRaman** [comment]
Okay,  just curious to know what could have caused the issue.

**Comment by mumoshu** [comment]
> x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "serial:56726364899828905982415242427572306586"

@shankarRaman This makes me wonder if your `cert-manager` deployment is working correctly. If `cert-manager` recently stopped working correctly in your environment, it might explain your issue 🤔  Would you mind checking logs of `cert-manager` pods that might be found in `cert-manager` namespace?

**Comment by shankarRaman** [comment]
@mumoshu `cert-manager` has been running without issues for over 50  days. Logs don't show any  red flags.

**Comment by mumoshu** [comment]
@shankarRaman Thanks! Then this might be a bug in either cert-manager or the framework ARC's using `controller-runtime`, that is unable to obtain the CA cert for unknown reason. `certificate signed by unknown authority` in your log says that ARC controller-manager was somehow given wrong CA cert.
