### ISSUE TITLE
Support arbitrarily setting `privileged: true` for runner container

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#1282]
Taken from https://github.com/actions-runner-controller/actions-runner-controller/issues/1269

There might be some edge cases where being able to run a privileged pod even with docker disabled is desired.

**Comment by splitice** [comment]
Fyi a big one is building VM images or anything in qemu.

**Comment by mumoshu** [comment]
@splitice Have you already tried setting `dockerdWithinRunnerContainer: true` while pointing the runner image to our `dind` variant https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Dockerfile.dindrunner?
That would also set `privileged: true`.

**Comment by splitice** [comment]
dind can't be used for some of our use cases (e.g yocto builds).

**Comment by mumoshu** [comment]
@splitice Hey. `dockerdWithinRunnerContainer: true` doesn't require you to actually use the dind. Can you just leave the dind running within the runner container and still use yocto builds?
