### ISSUE TITLE
can we please support "podManagementPolicy"

### ISSUE THREAD

**Issue by shichengripple001** [actions-runner-controller/actions-runner-controller#1293]
**Is your feature request related to a problem? Please describe.**

I am using runnerset, and you know when statefulset scale up, it will add pod 1 by 1 after first pod is ready, so it is too slow when scale up, we need to support this field for runnerset, and actually why can't we support all the fields available for statefulset 

**Describe the solution you'd like**

support podManagementPolicy for runnerset

**Describe alternatives you've considered**

**Additional context**

**Comment by mumoshu** [comment]
Which version of ARC are you using?

**Comment by shichengripple001** [comment]
controller version is v0.20.3

**Comment by mumoshu** [comment]
@shichengripple001 Thanks. Then, please try v0.22.1. Since v0.22.0 ARC should create all the new StatefulSet and their pods at once, which might make podManagementPolicy unnecessary for your case.

**Comment by shichengripple001** [comment]
cool. i will try that

**Comment by shichengripple001** [comment]
i am using following command to deploy, but it still deploy v0.20.3, how do i upgrade to v0.22.1?
helm upgrade --install --namespace xxxx --create-namespace --wait actions-runner-controller actions-runner-controller/actions-runner-controller -f values.yaml

**Comment by toast-gear** [comment]
https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/docs/UPGRADING.md

**Comment by shichengripple001** [comment]
Hi. thank you for you reply. I confirmed it is working.
