### ISSUE TITLE
Multiple Replicas can't run on single node in AKS

### ISSUE THREAD

**Issue by d-wierdsma** [actions-runner-controller/actions-runner-controller#1297]
**Describe the bug**
When trying to run more than one replica of actions runner controllers on single-node AKS deployed using helm only one replica is stable and other gets into a CrashLoopBackOff state

```
Docker enabled runner detected and Docker daemon wait is enabled
Waiting until Docker is avaliable or the timeout is reached
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Github endpoint URL https://github.com/
Passing --ephemeral to config.sh to enable the ephemeral runner.
Configuring the runner.

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------
Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.
Runner successfully configured.
{
  "agentId": 184,
  "agentName": "example-runner-deployment-bnb87-mdfb4",
  "poolId": 1,
  "poolName": "Default",
  "ephemeral": true,
  "serverUrl": "https://pipelines.actions.githubusercontent.com/mjfAN8ME65NFTcFeofnbmuY5OON2pzYs4S3UDeC3R8SA0SIzHH",
  "gitHubUrl": "https://github.com/REDACTED",
  "workFolder": "/runner/_work"
mv: cannot move './externalstmp/node12' to './externals/node12': Directory not empty
mv: cannot move './externalstmp/node12_alpine' to './externals/node12_alpine': Directory not empty
mv: cannot move './externalstmp/node16' to './externals/node16': Directory not empty
mv: cannot move './externalstmp/node16_alpine' to './externals/node16_alpine': Directory not empty
}
√ Connected to GitHub

Failed to create a session. The runner registration has been deleted from the server, please re-configure.
```

deployment.yaml
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: <org-name>-runner-deployment
spec:
  replicas: 2
  template:
    spec:
      organization: <org-name>
```

I believe this might be similar to https://github.com/actions-runner-controller/actions-runner-controller/issues/1065 where externalstmp uses `mv` instead of `cp -r`

**Checks**

- [ x] My actions-runner-controller version (v0.22.1) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Deploy helm chart with auth secret for organization app.
2. Try to deploy a basic `runnerdeployment` with 2 replicas on a one node AKS cluster.
3. Observe one replica fail since the other has already moved files where the second replica is trying to.

**Expected behavior**
Be able to run two replicas on a single kube node.

**Environment (please complete the following information):**
 - Controller Version [v0.22.1]
 - Deployment Method [Helm]
 - Helm Chart Version [0.17.1]

**Additional context**

**Comment by BeyondEvil** [comment]
I'm seeing (a variant) of this issue. With the difference that we have a two-node AWS EKS cluster.

I've never seen it before, but it started happening while experimenting with a webhook-base HRA.

**Comment by mumoshu** [comment]
@d-wierdsma Could you share logs related to `example-runner-deployment`, by perhaps running `kubectl logs` on ARC's controller-manager and piping it to `grep example-runner-deployment`?
Also, `kubectl get po -o yaml` on the runner pods trapped into CrashLoopBackOff would be helpful.

This should happen only when your runner pod had somehow restarted and hence `config.sh` was rerun with the same RUNNER_NAME. `mv: cannot move './externalstmp/node12` seems like red herring, but might not be the cause of this exact issue.

**Comment by d-wierdsma** [comment]
Hey @mumoshu it looks like it's just started working now... Sorry for the unnecessary ticket, I'll report back here with the logs if this issue comes up again
