### ISSUE TITLE
Failed to get new registration:  404 Not Found

### ISSUE THREAD

**Issue by hyj-kim** [actions-runner-controller/actions-runner-controller#1320]
Hi.

I tried to deploy actions-runner-controller on a machine for using self-hosted-runner.
I followed Readme guide. However after launching runners in my k8, I observed these errors.
```
$ kubectl logs -n actions-runner-system actions-runner-controller-77946bd567-6xhmt manager -f
022-04-08T11:14:16Z	ERROR	actions-runner-controller.runner	Failed to get new registration token	{"runner": "runnerdeploy-4qrrn-526wm", "error": "failed to create registration token: POST https://api.github.com/repos/MYORG/MYREPO/actions/runners/registration-token: 404 Not Found []"}
github.com/actions-runner-controller/actions-runner-controller/controllers.(*RunnerReconciler).processRunnerCreation
022-04-08T11:14:16Z	ERROR	actions-runner-controller.runner	Failed to get new registration token	{"runner": "runnerdeploy-4qrrn-526wm", "error": "failed to create registration token: POST https://api.github.com/repos/MYORG/MYREPO/actions/runners/registration-token: 404 Not Found []"}
github.com/actions-runner-controller/actions-runner-controller/controllers.(*RunnerReconciler).processRunnerCreation
```

I tried to access the registration-token uri:
```
$ curl -XPOST https://api.github.com/repos/MYORG/MYREPO/actions/runners/registration-token
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/actions#create-a-registration-token-for-a-repository"
}
```

Here is my environments.
- machine: centos7
- k8: minikube(v1.23.3)
- cert-manager(v1.8.0)
- actions-runner-controller(v0.17.3)
- Repository Runners

I did both GitHub Apps and PAT for authentication, they failed with above errors.

Here are permission I granted to Apps and PAT

1.Apps:
![runner-errors](https://user-images.githubusercontent.com/22164842/162427040-7f48fac2-7cff-4458-aa3d-5d2f0ee4dd2b.png)

2. PAT:
![pat](https://user-images.githubusercontent.com/22164842/162426999-3f77a739-970f-4a27-a44c-1a5896bd7496.png)

:cry:

**Comment by mumoshu** [comment]
@hyj-kim Hey. How did you create the k8s secret containing App creds and PAT?

For PAT, what if you run `curl` with the PAT?

```
curl -H "Authorization: token $GITHUB_TOKEN" -XPOST https://api.github.com/repos/MYORG/MYREPO/actions/runners/registration-token
```

Also, have you read our troubleshooting guide?
https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md#invalid-header-field-value

**Comment by hyj-kim** [comment]
@mumoshu
Thank you for answer.
After destroying and installing again, it works well. I think I made a mistake in some process.
I will close this issue.
