### ISSUE TITLE
HorizontalRunnerAutoscaler not respecting `minReplicas`

### ISSUE THREAD

**Issue by funkswing** [actions-runner-controller/actions-runner-controller#1322]
**Describe the bug**

`minReplicas` is set to 10, but the "desired" number of pods always goes below the min during periods of low usage. We are using a managed node group in EKS and the min number of Nodes is set to 1, which would not support the `minReplicas` of 10 in our case. Is it expected that Node min would override the `minReplicas` of the actions runner controller?

**Checks**

- [ x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Described above

**Expected behavior**
Expect the `minReplicas` to be respected over the Node min in the MNG, i.e. should never has less Pods than the `minReplicas` (10 in our case)

**Screenshots**
![image](https://user-images.githubusercontent.com/3672489/162458420-9f127af0-a285-4250-8da9-f47ee65fc9c2.png)

**Environment (please complete the following information):**
 - Controller Version: `actions-runner-controller:v0.21.1`
 - Deployment Method: Helm via ArgoCD
 - Helm Chart Version: 0.16.1

**Additional context**
EKS, managed Node group for action runner pods. Use `--ephemeral` flag and NOT using webhook scaling.

**Comment by mumoshu** [comment]
@funkswing Hey. What's your scaling method? PercentageRunnersBusy or TotalInProgressAnd~?

**Comment by funkswing** [comment]
`PercentageRunnersBusy`

**Comment by mumoshu** [comment]
@funkswing Thanks. Could you also share logs from ARC's controller-manager that contains `Calculated desired replicas of ...`? `...` should be the actual number of desired replicas(that you think minReplicas isn't respected) and the line should also contain various values that helps investigating the issue.

**Comment by michael-kopsho** [comment]
Hi @mumoshu , we can close this issue. We had misconfigured `scheduledOverrides` to change `minReplicas` to `1` on Fridays during business hours, which was not the desired behavior. We've since fixed it after implementing some monitoring which helped us see the issue more clearly. Thanks for your help here!

**Comment by mumoshu** [comment]
@michael-kopsho Thanks for reporting back!
