### ISSUE TITLE
Queue information are suddenly empty -- no more scaling

### ISSUE THREAD

**Issue by Djiit** [actions-runner-controller/actions-runner-controller#1327]
**Describe the bug**

Suddenly, our queue info disappeared (we monitor our runners based on the controller metrics) and, in turn, the controller stopped asking for more replicas (which is expected with an empty queue).

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1169844/162780036-31a98b38-4881-4340-9fba-4749eba30f63.png">

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

I've no idea; but we've seen this on 2 diff clusters and 3 differents controllers.

**Expected behavior**

**Screenshots**
See above

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.18.2] 0.22.1
 - Deployment Method [e.g. Helm and Kustomize ] plain yml
 - Helm Chart Version [e.g. 0.11.0, if applicable] N/A

**Additional context**
We're opening a ticket on the Github side at the same time.

**Comment by toast-gear** [comment]
yaml + controller logs please

> Controller Version [e.g. 0.18.2] 0.22.1

You will want to upgrade to 0.22.3, there were various bugs which you are likely to run into on v0.22.1

**Comment by killmeplz** [comment]
we have something like this. started today. 
no matter how many workflows are waiting for the runner in logs there is always the same line
```
2022-04-11T16:25:57Z DEBUG actions-runner-controller.horizontalrunnerautoscaler Suggested desired replicas of 1 by TotalNumberOfQueuedAndInProgressWorkflowRuns {"workflow_runs_completed": 0, "workflow_runs_in_progress": 0, "workflow_runs_queued": 1, "workflow_runs_unknown": 0, "namespace": "actions-runner", "kind": "runnerdeployment", "name": "ci-runner", "horizontal_runner_autoscaler": "ci-runner-autoscaler"}
2022-04-11T16:25:57Z DEBUG actions-runner-controller.horizontalrunnerautoscaler Calculated desired replicas of 1 {"horizontalrunnerautoscaler": "actions-runner/ci-runner-autoscaler", "suggested": 1, "reserved": 0, "min": 0, "max": 15}
```

**Comment by jbkc85** [comment]
I am seeing the same behavior atm!

**Comment by jbkc85** [comment]
just FYI - I basically copy/pasted the code into a Golang CLI command and I am able to get the appropriate responses of queue, running etc.  Could this be an issue with the applications access to the API vs an individual account?

**Comment by jbkc85** [comment]
update - I actually got it to work using the same copy/paste code with the app....but its showing 0 workflows when there are in fact 3-5 running.

> https://api.github.com/repos/user/repo/actions/runs?per_page=50&status=in_progress

**Comment by jbkc85** [comment]
https://github.community/t/list-workflow-runs-api-not-detecting-in-progress-builds/165029/4

this looks like what is happening.  When you include the status in the options, its returning nothing.  But if you remove the status from the call, it shows all the workflows as intended.

**Comment by jbkc85** [comment]
created a support ticket to hopefully speed things along.

Nothing appears to be wrong in the code - it literally is 100% on the API's side - it looks like the status argument breaks something right now.

**Comment by Djiit** [comment]
Hey, yep indeed the support got back to us and said there was something going on with one of their elastic search cluster -- some list operations, when filtered, were stale.

**Comment by jbkc85** [comment]
> Hey, yep indeed the support got back to us and said there was something going on with one of their elastic search cluster -- some list operations, when filtered, were stale.

good to know!  Did they give you an ETA on fix?

**Comment by renperez-cpi** [comment]
@Djiit do you know if this was still happening. this started happening yesterday and today still not working

**Comment by Djiit** [comment]
No improvement on our side either. We're flying with manually scaled runner groups. Annoying, to say the least 😅

**Comment by renperez-cpi** [comment]
@Djiit good to know. I did spent some time today trying to troubleshoot. this is definitely an issue with github API. Question is why it says on their status page that their API is up and running. I ended up using this for now. 
`metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'    # The percentage of busy runners at which the number of desired runners are re-evaluated to scale up
    scaleDownThreshold: '0.3'   # The percentage of busy runners at which the number of desired runners are re-evaluated to scale down
    scaleUpAdjustment: 2        # The scale up runner count added to desired count
    scaleDownAdjustment: 1      # The scale down runner count subtracted from the desired count`

**Comment by eagleusb** [comment]
I encounter the same behavior, GH API is broken and thus the HRA do not scale at all :(

**Comment by renperez-cpi** [comment]
@eagleusb @Djiit @jbkc85 this is still happening. did github support got back to anyone of you guys? I sent a ticket yesterday but no response :(

**Comment by eagleusb** [comment]
Still the same sadly 😿

**Comment by toast-gear** [comment]
I'm going to reopen this for the sake of visibility as whilst this is a github.com issue, it'll prevent a duplicate ticket being raised whilst we wait for GitHub to sort their API out.

**Comment by jbkc85** [comment]
James (GitHub Support)
Apr 19, 2022, 2:24 PM UTC

Hi Jason,

We are sincerely sorry for the delay it has taken to fix this. As of this morning we confirmed with the engineering team that the new index has been fixed. If you're still seeing this issue now, please let us know.

Cheers,
GitHub Support

**Comment by renperez-cpi** [comment]
@jbkc85 @Djiit @eagleusb i also confirmed that this is now working

**Comment by shichengripple001** [comment]
I am still getting this error, my chart version is actions-runner-controller-0.21.1, controller image version is 0.26.0, could you help confirm whether it is an issue of github? @mumoshu 
2022-11-07T08:41:47Z	DEBUG	actions-runner-controller.horizontalrunnerautoscaler	Suggested desired replicas of 0 by TotalNumberOfQueuedAndInProgressWorkflowRuns	{"workflow_runs_completed": 0, "workflow_runs_in_progress": 0, "workflow_runs_queued": 0, "workflow_runs_unknown": 0, "namespace": "xxxx", "kind": "runnerset", "name": "xxxxxx", "horizontal_runner_autoscaler": "xxxx"}

**Comment by mumoshu** [comment]
@shichengripple001 Try it on another githu repo or org and see if workflow_runs_queued goes up and down there- then, it's more likely that your issue is due to some github errors, not ARC.

**Comment by mumoshu** [comment]
Locking this issue as accepting comments on old issues can result in conflation and we can't provide support for every comment in every old issue 🙏
