### ISSUE TITLE
Runners should be deployed in standard Deployments and ReplicaSets

### ISSUE THREAD

**Issue by Nuru** [actions-runner-controller/actions-runner-controller#133]
It is fine to have a CRD called `RunnerDeployment` if you want, but the end result should be a standard Kubernetes `Deployment` and/or `ReplicaSet`, not Pods running under the control of a RunnerDeployment. I say this because we have all our support tooling (Prometheus metrics, Alerts, Grafana, etc.) supporting Deployments, and Runners become invisible without them. Not completely invisible, of course, because they are in the end Pods, but in many cases we look at Deployments, not Pods. 

I also think this will help with #16

**Comment by Hi-Fi** [comment]
Issue with the stardard deployment and replicaset is that each pod needs separate agent token, and agents need also be removed from GH side when killed.

So IF controller would be part of runner, and runner would work alone, that would mean:
- Deployment would have quite high level Github credentials
- Each pod have to use those credentials to get the agent token to be registered
- Each pod has to somehow be able to de-register self in case of failures

I think it would be completely different solution as controller simplifies things quite a lot. In a way it could even be, that controller is on some namespace that users can't access, and they can just create own runners to their own namespace. This way only agent token is disclosed to users, and those high-power tokens are only for admins.

**Comment by Nuru** [comment]
@Hi-Fi The controller can run and be a source of authentication credentials and can monitor the status of pods using [standard Kubernetes resources watches](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) without directly owning the Pods. (It already appears to fail to handle replacements of Runner resources correctly, and it is not like the current solution is without other problems, e.g. #62)

Projects like [kiam](https://github.com/uswitch/kiam) manage to securely pass credentials in a client/server architecture. This project is already requiring `cert-manager` to create internal TLS certificates, it could certainly create client authentication certificates if desired so that it would only serve credentials to its own pods (it would be as secure as it is currently with the primary GitHub credential being in a Kubernetes secret). So the pods can register with the controller when they come up, receive their access token from the controller, and continue to be monitored by the controller and autoscaler pretty much the same as is now. And you would get the advantage of the Kubernetes scheduler managing pod replacement when pods fail or the nodes they are on shut down, among many other benefits of using standard Deployment and ReplicaSet resources.
