### ISSUE TITLE
Labels do not get transferred from RunnerDeployment to Runner

### ISSUE THREAD

**Issue by 0x416e746f6e** [actions-runner-controller/actions-runner-controller#1331]
**Describe the bug**

Labels do not get transferred from RunnerDeployment to Runner.

**Checks**

- [x] My actions-runner-controller version (v0.22.3) does support the feature

**To Reproduce**

1.  Create `RunnerDeployment` with labels defined:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: xxx
spec:
  replicas: 1
  template:
    spec:
      dockerMTU: 1460
      labels:  # <------------------------------------- Labels ARE defined here
      - test 
      repository: yyy
```

2. Wait for `Runner` object to be created and check it's definition.

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  labels:
    runner-deployment-name: xxx
    runner-template-hash: 599ddb4c8
  name: xxx-njwx5
  ownerReferences:
  - apiVersion: actions.summerwind.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: RunnerReplicaSet
    name: xxx-4992g
    uid: 0262921a-9608-45cf-973d-139e33796801
  resourceVersion: "4248605"
  uid: cdbde460-6954-421d-b8f8-49bda1b8d291
spec: # <----------------------------------------------- Labels are NOT defined here
  dockerMTU: 1460
  repository: yyy
```

**Expected behavior**

The contents of `spec.template.spec.labels` from `RunnerDeployment` should be copied to `spec.labels` of the `Runner`.

**Environment (please complete the following information):**

 - Controller Version: 0.22.3
 - Deployment Method: Helm
 - Helm Chart Version: 0.17.3

**Comment by 0x416e746f6e** [comment]
As a follow-up, apparently it was due to finaliser that got stuck.  Patching it with:

```bash
kubectl patch -n github-actions runnerdeployments.actions.summerwind.dev xxx -p '{"metadata":{"finalizers":[]}}' --type=merge
```

... and then recreating it from scratch solved the problem.

**Comment by toast-gear** [comment]
Closing as this was just a k8s quark
