### ISSUE TITLE
Getting Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by rahul-FLS** [actions-runner-controller/actions-runner-controller#1332]
**Describe the bug**
When trying to deploy RunnerDeployment.yaml on EKS, I get **Failed to create CoreCLR, HRESULT: 0x80004005**. Here are the logs--

Docker wait check skipped. Either Docker is disabled or the wait is disabled, continuing with entrypoint
Github endpoint URL https://github.com/
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
Passing --ephemeral to config.sh to enable the ephemeral runner.
Configuring the runner.
Failed to create CoreCLR, HRESULT: 0x80004005
Configuration failed. Retrying
Configuring the runner.
Failed to create CoreCLR, HRESULT: 0x80004005
Configuration failed. Retrying
Configuring the runner.

**To Reproduce**
Deploy below manifest to EKS and observe the runner logs

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  labels:
    app: test
spec:
  replicas: 1
  template:
    spec:
      group: groupName
      serviceAccountName: test
      dockerEnabled: false
      securityContext:
          runAsUser: 1000
          fsGroup: 1000
      ephemeral: true
      organization: orgName
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: "true"
      - name: RUNNER_NAME
        value: $RANDOM
      - name: DISABLE_WAIT_FOR_DOCKER
        value: "true"

**Expected behavior**
Self-hosted runner should be registered to GitHub

**Comment by mumoshu** [comment]
@rahul-FLS Hey. Due to our limited resources, we can't support every combination of possible settings. But if I were you, I would try removing `securityContext` out of your spec and isolate the cause of your issue.
Also note that it's an error from `actions/runner`, not ARC, so if it persists even after omitting `securityContext`, you'd need to file an issue in `actions/runner`.
Also, why did you need to specify securityContext that way? I think it's already uid=1000 by default as long as you're using our runner container image.
https://github.com/actions-runner-controller/actions-runner-controller/blob/c4ff1a588fc1884b846a1c15eee7bcf6cca956ed/runner/Dockerfile#L63

https://github.com/actions-runner-controller/actions-runner-controller/blob/c4ff1a588fc1884b846a1c15eee7bcf6cca956ed/runner/Dockerfile#L124

**Comment by rahul-FLS** [comment]
Hey @mumoshu yeah its odd that I still need to specify securityContext this way. If I remove it I get error **Error: container has runAsNonRoot and image has non-numeric user (runner), cannot verify user is non-root** which is weird so I had to mention it explicitly.

**Comment by toast-gear** [comment]
Odd, can you try building the runner image swapping out [L124](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Dockerfile#L124) from `USER runner` to `USER 1000` and see if that resolves the issue?

**Comment by mumoshu** [comment]
@rahul-FLS It seems like you need to tweak your own PodSecurityPolicy.

**Comment by mumoshu** [comment]
@rahul-FLS Well, I still don't get the goal of this issue! Sorry. So-... Can you just tweak or remove the PodSecurityPolicy that is blocking runner pods from correctly running?

As we can see, you don't have `securityContext.runAsNonRoot` explicitly set in the runner spec so I guess any of your PodSecurityPolicy is assuming it. Perhaps your default PSP, that may or may not be associated to the serviceaccount, has the following snippet?

```
  runAsUser:
    rule: 'MustRunAsNonRoot'
```

**Comment by rahul9170** [comment]
Hey @mumoshu I thought I replied to it sorry for late response but I could able to resolve the original error "Failed to create CoreCLR, HRESULT: 0x80004005" by mounting an emptyDir volume to /tmp. I guess runner was trying to write some of the diagnostics logs to its root which isn't allowed by PSP hence was failing. Now its write them to /tmp

<img width="673" alt="image" src="https://user-images.githubusercontent.com/61755746/165694160-d08ded13-eaf7-459a-a112-51836d6267c6.png">

**Comment by mumoshu** [comment]
@rahul-FLS Ah, that makes sense! Thanks for sharing 🙏

**Comment by rahul9170** [comment]
Issue can be closed now.

**Comment by rahul-FLS** [comment]
Issue can be closed now.
