### ISSUE TITLE
README issue: Broken link and typo

### ISSUE THREAD

**Issue by VinGarcia** [actions-runner-controller/actions-runner-controller#1352]
Hey guys, I just found two problems in the same paragraph on the README, so I thought it would be worth reporting it:

> A RunnerDeployment or RunnerSet can scale the number of runners between minReplicas and maxReplicas fields driven by either pull based scaling metrics or via a webhook event (see limitations section of [stateful runners](https://github.com/actions-runner-controller/actions-runner-controller#stateful-runners) for cavaets of this kind). Whether the autoscaling is driven from a webhook event or pull based metrics it is implemented by backing a RunnerDeployment or RunnerSet kind with a HorizontalRunnerAutoscaler kind.

So we have `Cavaets` instead of `Caveats` and and this link is not working:

```
[stateful runners](https://github.com/actions-runner-controller/actions-runner-controller#stateful-runners) 
```

I think the title #stateful-runners changed to something else maybe "Runner Sets"?

Also, I am just openning this issue because it is a great README, thank you very much for this project =]

**Comment by VinGarcia** [comment]
And since I have already created this ticket, there is another typo here:

https://github.com/actions-runner-controller/actions-runner-controller/tree/master/charts/actions-runner-controller#values

> The values are documented as of HEAD, to review the configuration options for your chart version ensure you view this file at the relevent [tag](https://github.com/actions-runner-controller/actions-runner-controller/tags)

"relevent" instead of "relevant"

**Comment by VinGarcia** [comment]
I found another issue, I will add it here, and later if you guys want I can make PR with all these fixes:

so I am configuring the webhook driven scaling and I noticed this seems not to be working as expected:

> ```
> $ helm upgrade --install --namespace actions-runner-system --create-namespace \
>             --wait actions-runner-controller actions-runner-controller/actions-runner-controller \
>             --set "githubWebhookServer.enabled=true,githubWebhookServer.ports[0].nodePort=33080"
> ```
>
> The above command will result in exposing the node port 33080 for Webhook events. Usually, you need to create an external loadbalancer targeted to the node port, and register the hostname or the IP address of the external loadbalancer to the GitHub Webhook.

Then I tried reading the [Chart README](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/README.md) and I noticed that this option mentioned above: `githubWebhookServer.ports` does not exist in the README nor in the [values.yaml file](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/values.yaml) itself.

So I would propose updating the README text here updating the code snippet to setup an ingress or a NodePort service instead. What do you guys think? Alternatively we can add more instructions on how to setup an ingress after running this helm command.

**Comment by rushikeshkalyani** [comment]
I had seen the same issues while configuring the webhook driven scalling.

This week, I planned to play with some options from the readme. Something like `githubWebhookServer.service.type=LoadBalancer`
However, if the document is updated before that would be great !!

**Comment by VinGarcia** [comment]
Good, I decided to create two PRs for this, in the first one I am running the README.md and the chart's README file through Grammarly for catching typos. And on the second one, I will try to fix this code snippet.

**Comment by VinGarcia** [comment]
Here the first one:

https://github.com/actions-runner-controller/actions-runner-controller/pull/1353

I tried to be very conservative in order to not change the meaning of any sentence, so it should be safe to merge.

I will create a second one that other issue.

**Comment by rushikeshkalyani** [comment]
``Well, Just an heads up:

I have tried with `githubWebhookServer.service.type=LoadBalancer` on eks cluster and found that its working as expected.

Full command is --
`helm upgrade --install --namespace actions-runner-system --create-namespace --wait actions-runner-controller actions-runner-controller/actions-runner-controller --set "githubWebhookServer.enabled=true,githubWebhookServer.service.type=LoadBalancer"`

Well, this creates a classic load balancer in AWS and adds a listener on TCP port 80. 

Is there any way to make it secure? by using listener as HTTPS with SSL.TLS certs?

**Comment by VinGarcia** [comment]
Uhm, so if I wanted to protect it with HTTPS I would write an ingress for it instead since I already have it set up for my k8s cluster. 

We might be able to think of a way to make it work with a LoadBalancer; but how to protect it might change depending on whether the user is on AWS, GCloud, or some other provider. 🤔 

What are you thoughts about just providing the user with an example ingress configuration so he can setup the `tls:` section himself?

**Comment by VinGarcia** [comment]
Just updated https://github.com/actions-runner-controller/actions-runner-controller/pull/1354 with some things that were necessary for it to work on my setup.

Now if you agree we can just add an example ingress and it should be enough, what do you think?

**Comment by rushikeshkalyani** [comment]
Yup, that sounds good! 
Example ingress would be better option.

**Comment by VinGarcia** [comment]
@rushikeshkalyani just added the changes we spoke about on the following PR:

https://github.com/actions-runner-controller/actions-runner-controller/pull/1354

It's ready to be reviewed, tell me if you think something should be changed.

**Comment by VinGarcia** [comment]
Keep it up, we are almost merging the last PR.

**Comment by VinGarcia** [comment]
@rushikeshkalyani the PR https://github.com/actions-runner-controller/actions-runner-controller/pull/1354 was merged so I will just close this ticket.

Thanks for the help and sorry for not including you on the PR, I made a mess with the mentions there.
