### ISSUE TITLE
Fix make `docker-buildx` target on a Mac M1

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#1357]
The controller no longer builds when using the make target docker-build on a Macbook (M1 at least, maybe Intel too)

**Comment by mumoshu** [comment]
I believe you'd need `buildx` and use `make docker-buildx` instead, because we now rely on the cache mount https://github.com/actions-runner-controller/actions-runner-controller/blob/81951780b10577d645b3ab9f5cb27c6f80134676/Dockerfile#L37-L38 (and probably that's not Mac-specific

**Comment by toast-gear** [comment]
We probably need to just remove the non-buildx target entirely from the Makefile
