### ISSUE TITLE
How to use Vault sidecar for secret injection?

### ISSUE THREAD

**Issue by rahul-FLS** [actions-runner-controller/actions-runner-controller#1364]
Hi @mumoshu I am trying to inject vault sidecar to the actions controller pod to mount the secrets as volume at /vault/secrets/* so in order to read the secrets from the volume , I want to pass a command to controller pod something like **for f in /vault/secrets/*; do source $f; done** so that they become available as environment variables i.e. GITHUB_APP_ID, GITHUB_APP_INSTALLATION_ID, GITHUB_APP_PRIVATE_KEY but it feels like the controller image doesn't contain a shell/bash so I am not able to run the above command. Is there a workaround for this?

**Comment by rahul-FLS** [comment]
Hey @mumoshu just wondering if you could provide your inputs here. Thanks 😊

**Comment by mumoshu** [comment]
@rahul-FLS I thought there were a handful of Vault sidecars in the wild. Which one are you talking about?

**Comment by mumoshu** [comment]
Although, I don't think a sidecar container can mount a secret as a volume 🤔 Are you walking about the case that there's a mutating webhook provided by your Vault integration and it generates a K8s secret from a Vault secret, inject it into the runner container, and you want it expose it as runner container's envvars?

Then, can you just mount the secret as envvars by using `envFrom`?

**Comment by rahul-FLS** [comment]
@mumoshu I am talking about a case where vault sidecar read the secrets from vault and mount them as volume in /vault/secrets/* and it shares the same volume with the main app i.e. controller. Its here: 
https://www.vaultproject.io/docs/platform/k8s/injector

**Comment by mumoshu** [comment]
@rahul-FLS How about using the `vault.hashicorp.com/agent-inject-template-` configuration and let vault-sidecar render the template as `.env` file that is read by the runner? https://github.com/actions-runner-controller/actions-runner-controller/issues/1135#issuecomment-1046237521

**Comment by rahul-FLS** [comment]
Thanks @mumoshu but I need those secrets to be loaded by controller, not runner because controller updates the registration token for the runner via GitHub App authentication which uses these env variables
GITHUB_APP_ID, GITHUB_APP_INSTALLATION_ID, GITHUB_APP_PRIVATE_KEY

**Comment by mumoshu** [comment]
Ah thanks, gotcha. Then you'd need to patch our actions-runner-controller image to load an env file.

**Comment by mumoshu** [comment]
I don't know if the use of the Vault sidecar is a strict requirement for you but anyway, another option is to use https://www.vaultproject.io/docs/platform/k8s/csi which supports projecting vault secrets into k8s secrets so that you can modify the ARC's deployment's manifest to include a envFrom field points to the k8s secret projected by the csi secret provider.

**Comment by mumoshu** [comment]
@rahul-FLS Hey! Can I safely close this as answered, or are you willing to contribute anything(perhaps a section in our doc?) to cover what worked for you? (That's definitely great if you could do so!

**Comment by rahul9170** [comment]
@mumoshu sorry for late response but this isn't worked yet. We aren't advised to use k8s secret by any means so only option is to load the secrets from vault in /vault/secrets folder, source them and load in the env variables. Still not sure how we do this in ARC.

**Comment by rahul-FLS** [comment]
@mumoshu sorry for late response but this isn't worked yet. We aren't advised to use k8s secret by any means so only option is to load the secrets from vault in /vault/secrets folder, source them and load in the env variables. Still not sure how we do this in ARC.

**Comment by mumoshu** [comment]
@rahul-FLS Hey! I can see that some kind of security folks would like to enforce such restriction :) But I'd say it's not very standard-ish. That said, you need to change the runner image accordingly to accommodate your own use case.

A simple way would be to wrap it in a custom init-like golang program that loads the vault secret files, set envvars, and run `actions/runner` process and so on. You can build such program yourself, or ask your security team to provide such one because it might be useful in many places in your organization, not only in ARC.

At least, it isn't what ARC should support out of the box. If it had to do so, every open source project has to reinvent such functionality, which doesn't seem like a valid ask.

**Comment by rahul-FLS** [comment]
Hey @mumoshu thanks for your inputs. Can you please suggest if there is a way to pass args to the ARC container like this? Also is there a way to get a shell/bash in ARC container?

- args:
        - sh
        - "-c"
        - "for f in /vault/secrets/*; do source $f; done && /manager"

**Comment by mumoshu** [comment]
@rahul-FLS The runner container depends on our own entrypoin.sh https://github.com/actions-runner-controller/actions-runner-controller/blob/4053ab3e113e2cbc06d98319cee8a9ea797e2d76/runner/Dockerfile#L127 so perhaps you can do whatever setup in a shell script and then finally exec to `/bin/bash /entrypoint.sh`.

Also recent versions of the runner entrypoint.sh has ability to load envvars from /etc/environment so you could somehow generate that file and let entrypoint.sh load it for actions/runner.

https://github.com/actions-runner-controller/actions-runner-controller/blob/4053ab3e113e2cbc06d98319cee8a9ea797e2d76/runner/entrypoint.sh#L165

**Comment by toast-gear** [comment]
you can also load env vars from a `.env` file at the actions software root (`/runner`)

**Comment by rahul9170** [comment]
Hello @mumoshu i think we’re confused here. I don’t want anything to be loaded in runner container. I want to read the values of GitHub app authentication variables from /vault/secrets (created by vault sidecar) directory of ARC.

**Comment by rahul9170** [comment]
Also is there a way to add a sidecar/init container to the controller pod? This way I can try to have the secrets from the vault mounted onto the controller via shared volume.

**Comment by mumoshu** [comment]
@rahul9170 AFAIK, you'd use any mutating webhook config to inject such sidecars into the pods of your choice. https://www.vaultproject.io/docs/platform/k8s/injector

**Comment by rahul9170** [comment]
Thanks @mumoshu but then how would I read the secrets which are mounted by vault in vault/secrets folder of controller container and set them to GITHUB_APP_ID, GITHUB_APP_INSTALLATION_ID, GITHUB_APP_PRIVATE_KEY ?

**Comment by mumoshu** [comment]
@rahul9170 You'd need to somehow map those files envvars yourself. For example, you could build our own ARC controller image based on our image, add a entrypoint.sh to export a series of envvars according to the vault-mounted files, and exec ARC.

**Comment by zura101** [comment]
it's late but I have waste lot's of time searching for solution to this issue and I have decided to write here.

we will need two annotations for it
```
vault.hashicorp.com/agent-inject-command-github-pat: 'cat /vault/secrets/github-pat > /runner/.env'
vault.hashicorp.com/agent-copy-volume-mounts: 'runner'
```
**agent-copy-volume-mounts** will mount all volumes from runner container
**agent-inject-command** will copy rendered secret into `/runner/.env`

full example:
```
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'ci-role'
        vault.hashicorp.com/agent-inject-command-github-pat: 'cat /vault/secrets/github-pat > /runner/.env'
        vault.hashicorp.com/agent-copy-volume-mounts: 'runner'
        vault.hashicorp.com/agent-inject-secret-github-pat: '***/github/pats'
        vault.hashicorp.com/agent-inject-template-github-pat: |
          {{- with secret "***/github/pats" }}
          GITHUB_PAT={{ .Data.data.arc_pat }}
          {{- end }}
```

**Comment by rakeshramakrishnan-hbk** [comment]
How to ensure that these secrets, when they are set as env variables, are masked when picked up by the runner?

**Comment by saurabtanej** [comment]
`GITHUB_APP_PRIVATE_KEY` can be passed as a file. So, we can directly use the secret file created by vault. 
This is what worked for me:
```
    vault.hashicorp.com/agent-inject-secret-arc: "secret/path"
    vault.hashicorp.com/agent-inject-template-arc: |
      {{ with secret "secret/path" }}
      {{ .Data.data.GITHUB_APP_PRIVATE_KEY }}
      {{ end }}
```
with 
```
env:
    - name: GITHUB_APP_PRIVATE_KEY
      value: /vault/secrets/arc
```

**Comment by danielemuze** [comment]
I have been stuck on migrating public keys to Vault for days now. I have added the 2 keys to Vault .pem files using the kv engine.

In the path: kv_secrets/dev 

These are the volume and volumeMount of the key respectively;

volumes:
  - name: volume-example
    secret:
      secretName: public-keys-example

volumeMounts:
  - name: volume-example
    mountPath: /etc/private/keys/public
    readOnly: true
    
    i am using the vault injector for integrating Vault to K8s.
    
    What are the annotations I need to add please ?
