### ISSUE TITLE
Add gh CLI to base runner container images

### ISSUE THREAD

**Issue by jwalters-gpsw** [actions-runner-controller/actions-runner-controller#1366]
On the Github hosted runner they all have the `gh` CLI installed. See here: https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows

Would be good to have it on the runner containers provided by actions-runner-controller.

Is there a better repo for this feature request?

**Comment by toast-gear** [comment]
I'm afriad we won't be able to add the gh cli due it not meeting our reqs for baked in packages:

* The use of the package is generally version insensitive
* Configs for the package are generally versions insensitive

https://github.com/cli/cli/releases has regular releases which introduce major features on a consistent basis. Our base runner would be bumped very frequently and we would end up with issues for the package increasing the support burden of this project. We can't include everything GitHub includes in their runners as it would mean the container ~20GB. You'll need to build your own container.

**Comment by derwasp** [comment]
Hey folks 👋 

Considering GitHub has now [adopted the project](https://github.com/actions/actions-runner-controller/discussions/2072), would this by any chance make you reconsider?

CC
@Link-

**Comment by Link-** [comment]
@derwasp et al, we've been discussing what level of support we want to provide for the runner images and we'll announce the outcomes of these discussions early next year. We agree with @toast-gear on the burden of maintaining these images with too many packages as well as the cost of having a large image size.

**Comment by derwasp** [comment]
Thank you for the lightning-fast response @Link- 
Looking forward to the announcement!

**Comment by usmonster** [comment]
Hello!

Sorry to post a year and a half later, but can a link to the announcement of the outcomes of the referenced conversations please be shared here? I couldn't find anything on the discussion forum (and maybe the context has even changed since then?).

Thanks!

**Comment by wyardley** [comment]
I opened a new issue with more or less the same request, since this one is already closed.
