### ISSUE TITLE
Workflow_job events with empty labels get matched to scale up targets

### ISSUE THREAD

**Issue by stefangluszek** [actions-runner-controller/actions-runner-controller#1370]
For some reason we receive workflow_job completed events with empty labels which are unfortunately wrongly matched to a scale up target resulting in wrongly scaling down scale targets when they shouldn't be scaled down.

Example of workflow_job completed payload:
```
{
  "event": "workflow_job",
  "hookID": "***",
  "delivery": "***",
  "workflowJob.status": "completed",
  "workflowJob.labels": [],
  "repository.name": "***",
  "repository.owner.login": "***",
  "repository.owner.type": "Organization",
  "enterprise.slug": "***",
  "action": "completed",
  "groups": "RunnerGroup{Scope:Organization, Kind:Custom, Name:BigRunners}, RunnerGroup{Scope:Organization, Kind:Custom, Name:DefaultAutoscaling}, RunnerGroup{Scope:Organization, Kind:Custom, Name:BigRunners}"
}
```
scale down event:
```
status": "completed", "workflowJob.labels": [], "repository.name": "***", "repository.owner.login": "***", "repository.owner.type": "Organization", "enterprise.slug": "***", "action": "completed", "enterprise": "***", "organization": "***", "repository": "***", "key": "mobitroll/group/BigRunners"}                                                                  
"2022-04-21T10:59:33Z;DEBUG;controllers.webhookbasedautoscaler;Patching hra runner-deployment-8c-16g-autoscaler for capacityReservations update;{"before": 0, "expired": 0, "amount": -1, "after": 0}
"2022-04-21T10:59:33Z;INFO;controllers.webhookbasedautoscaler;scaled runner-deployment-8c-16g-autoscaler by -1
```

What's interesting is that the workflow_job complete events don't seem to match in numbers workflow_job queued events:

| label      | queued | completed |
| ----------- | ----------- | ------------ |
| null | 0 | 274 |
| self-hosted | 2 | 2 |
| self-hosted-8c-16g | 4 | 3 |
| self-hosted-8c-32g | 1 | 1 |
| ubuntu-20.04 | 2 | 2 |
| ubuntu-latest | 446 | 446 |

**Expected behavior**
workflow_job completed events with empty labels should not match scale up targets.

**Environment:**
 - Controller Version: v0.22.2
 - Deployment Method:  Helm
 - Helm Chart Version: 0.17.2

**Comment by stefangluszek** [comment]
I captured the raw payload from the GH webhook and I think I see when this happens, it's when the workflow_job is skipped:
```
{
  "action": "completed",
  "workflow_job": {
    "status": "completed",
    "conclusion": "skipped",
    "steps": [

    ],
    "labels": [

    ],
)                                                              
```
And the corresponding log lines from the actions-runner-controller-github-webhook-server:
```
"2022-04-21T14:36:41Z;DEBUG;controllers.webhookbasedautoscaler;Searching in runner groups;{"event": "workflow_job", "hookID": "***", "delivery": "75129710-c180-11ec-9642-a48b3e53116d", "workflowJob.status": "completed", "workflowJob.labels": [], "repository.name": "***-frontend", "repository.owner.login": "***", "repository.owner.type": "Organization", "enterprise.slug": "***", "action": "completed", "groups": "RunnerGroup{Scope:Organization, Kind:Custom, Name:BigRunners}, RunnerGroup{Scope:Organization, Kind:Custom, Name:DefaultAutoscaling}"}"
"2022-04-21T14:36:41Z;DEBUG;controllers.webhookbasedautoscaler;groups;{"event": "workflow_job", "hookID": "***", "delivery": "75129710-c180-11ec-9642-a48b3e53116d", "workflowJob.status": "completed", "workflowJob.labels": [], "repository.name": "***-frontend", "repository.owner.login": "***", "repository.owner.type": "Organization", "enterprise.slug": "***", "action": "completed", "groups": "RunnerGroup{Scope:Organization, Kind:Custom, Name:BigRunners}, RunnerGroup{Scope:Organization, Kind:Custom, Name:DefaultAutoscaling}"}"
"2022-04-21T14:36:41Z;DEBUG;controllers.webhookbasedautoscaler;Found 2 HRAs by key;{"key": "***/group/BigRunners"}"
"2022-04-21T14:36:41Z;DEBUG;controllers.webhookbasedautoscaler;job scale up target found;{"event": "workflow_job", "hookID": "***", "delivery": "75129710-c180-11ec-9642-a48b3e53116d", "workflowJob.status": "completed", "workflowJob.labels": [], "repository.name": "***-frontend", "repository.owner.login": "***", "repository.owner.type": "Organization", "enterprise.slug": "***", "action": "completed", "enterprise": "***", "organization": "***", "repository": "***-frontend", "key": "***/group/BigRunners"}"
"2022-04-21T14:36:41Z;DEBUG;controllers.webhookbasedautoscaler;Patching hra runner-deployment-8c-16g-autoscaler for capacityReservations update;{"before": 0, "expired": 0, "amount": -1, "after": 0}"
"2022-04-21T14:36:41Z;INFO;controllers.webhookbasedautoscaler;scaled runner-deployment-8c-16g-autoscaler by -1"
```

Perhaps we should ignore workflow_job status complete if conclusion is skipped?

**Comment by toast-gear** [comment]
https://github.com/actions-runner-controller/actions-runner-controller/pull/1330 it's already fixed in `master`, the fix will be in the next release `v0.23.0`. If you fancy building `master` and deploying it to confirm that would be helpful.

**Comment by stefangluszek** [comment]
> #1330 it's already fixed in `master`, the fix will be in the next release `v0.23.0`. If you fancy building `master` and deploying it to confirm that would be helpful.

Is there an approximate ETA for `v0.23.0` ?

**Comment by toast-gear** [comment]
Not sure. You can track the milestone https://github.com/actions-runner-controller/actions-runner-controller/milestone/3. Most of the issues have PR raised which we just need to do some testing where the CI can't so I probably a few weeks but life happens sometimes etc so it could be longer

**Comment by toast-gear** [comment]
Going to close this as, as previously mentioned, this is fixed via https://github.com/actions-runner-controller/actions-runner-controller/pull/1330 which will be part of the v0.23.0 release
