### ISSUE TITLE
could not parse webhook

### ISSUE THREAD

**Issue by sagi-shimoni** [actions-runner-controller/actions-runner-controller#1380]
I'm trying to enable HorizontalRunnerAutoscaler based on github webhooks but it's not working due to webhooks not being parsed correctly.

I checked the logs of pod "actions-runner-controller-github-webhook-server" and I encountered below error.

Installed v0.22.3 via Helm chart.

```
2022-04-24T09:26:05Z	ERROR	controllers.webhookbasedautoscaler	could not parse webhook	{"webhookType": "workflow_job", "payload": "payload=%7B%22action%22%3A%22queued%22%2C%22workflow_job

..................... (sensitive payload info) .....................

"error": "invalid character 'p' looking for beginning of value"}
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2425
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2879
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1930
```

**Comment by mumoshu** [comment]
@sagi-shimoni Hey. You seem have configured a wrong content-type for your webhook. Please use application/json.

**Comment by jonathanbeber** [comment]
@mumoshu to avoid errors such this one, is there any plan or an issue (sorry, couldn't find one) about adding the feature of the controller creating the webhook by itself? i.g. was it already discussed and, if not, is it worth to create a new issue with this request?
