### ISSUE TITLE
Helm/CRDs cannot be applied during update process

### ISSUE THREAD

**Issue by Vladyslav-Miletskyi** [actions-runner-controller/actions-runner-controller#1391]
Using ArgoCD one cannot easily update CRDs. Just because of: https://github.com/prometheus-community/helm-charts/issues/1500
Potential Fix:
* https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes

**Comment by mumoshu** [comment]
Also see https://github.com/actions-runner-controller/actions-runner-controller/issues/1256#issuecomment-1082361032 and https://github.com/actions-runner-controller/actions-runner-controller/issues/1102#issuecomment-1041138914

**Comment by toast-gear** [comment]
We don't like the idea of baking in annotations that are tool specific, is it possible to set annotications in the CRDs via the values?

**Comment by Vladyslav-Miletskyi** [comment]
@mumoshu good call ;)
