### ISSUE TITLE
refactor: use go-github package for ListRunnerGroup API for GitHub Cloud

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#1402]
Ref https://github.com/actions-runner-controller/actions-runner-controller/pull/1324 https://github.com/google/go-github/issues/2328 https://github.com/google/go-github/pull/2329

At the moment we use custom code for the new [ListRunnerGroup API](https://docs.github.com/en/rest/reference/actions#list-self-hosted-runner-groups-for-an-organization). At some point the go-github package will have support for this API (probably within the next month or two) at which point we should remove our custom implementation and use the package's implementations.

Note : We need to keep the old implementation around for GHES until the new parameter available in a GHES release

EDIT https://github.com/google/go-github/releases/tag/v45.0.0 has been released which has support for the new API

**Comment by mumoshu** [comment]
Closing this one as done!
