### ISSUE TITLE
runner docker image doesn't have kubectl?

### ISSUE THREAD

**Issue by poolpitako** [actions-runner-controller/actions-runner-controller#1419]
**Is your feature request related to a problem? Please describe.**
I am setting up a workflow which deploys to a cluster.
I noticed that using the github default `ubuntu-latest` it includes kubectl but when using the default runner it's not.

**Describe the solution you'd like**
I would like the default runner docker image to include `kubectl`

**Comment by toast-gear** [comment]
We aren't adding new software to the runner image at the moment, Azure provide a good action for configuring kubectl as part of your pipeline https://github.com/Azure/setup-kubectl

**Comment by poolpitako** [comment]
@toast-gear thanks. Shouldn't the runner docker image match software stack provided by github by default?

**Comment by toast-gear** [comment]
In an ideal world yes, however it's not practical or feasible from our perspective, additionally, the runner itself container would be tens of GB big making it impractical to use.

**Comment by poolpitako** [comment]
ok, thanks for your reply!

**Comment by hellt** [comment]
> EDIT https://github.com/nektos/act#alternative-runner-images Act puts the packer image at 18 GB when built to give you sense of how large the container would be if we included everything

Hi @toast-gear 
I came looking for exactly this, using the act's runner image as a runner with actions runner controller.
Are there any guidance on how to achieve that? The size is not really an issue when the parity between the gh hosted runner and self-hosted runner is desired to make sure the workflows are unified across the two.

Would appreciate any guidance on how to achieve that.
