### ISSUE TITLE
Set securityContext separately for runner and dind containers

### ISSUE THREAD

**Issue by bmbferreira** [actions-runner-controller/actions-runner-controller#1423]
**Is your feature request related to a problem? Please describe.**
Would it be possible to set securityContext separately for the runner and the dind container? Currently if I add the following `securityContext` to avoid executing the runner container as non-root, the docker-in-docker container fails to start:
```
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
```

logs on the dind container:
```
Generating RSA private key, 4096 bit long modulus (2 primes)
...................................................................................................................................++++
............................++++
e is 65537 (0x010001)
Generating RSA private key, 4096 bit long modulus (2 primes)
.............................................................................................++++
.....................................................................................................................................................................................................................................++++
e is 65537 (0x010001)
Signature ok
subject=CN = docker:dind server
Getting CA Private Key
/certs/server/cert.pem: OK
Signature ok
subject=CN = docker:dind client
Getting CA Private Key
/certs/client/cert.pem: OK
ip: can't find device 'ip_tables'
ip_tables              32768  3 iptable_mangle,iptable_filter,iptable_nat
x_tables               49152 15 ipt_REJECT,xt_multiport,xt_state,xt_connmark,xt_nat,xt_statistic,xt_tcpudp,iptable_mangle,xt_comment,xt_mark,xt_conntrack,xt_MASQUERADE,xt_addrtype,iptable_filter,ip_tables
modprobe: can't change directory to '/lib/modules': No such file or directory
error: attempting to run rootless dockerd but missing 'rootlesskit' (perhaps the 'docker:dind-rootless' image variant is intended?)
```

**Describe the solution you'd like**
A simple solution would be to set `securityContext` differently for the containers (similar to what is done with requests/limits).

Thank you!

**Comment by mumoshu** [comment]
@bmbferreira Hey. It's not supported in RunnerDeployment today. For RunnerSet, you can define a container named `docker` under `spec.template.spec.containers` and put `securityContext` of your choice there.

**Comment by mumoshu** [comment]
@bmbferreira But your issue seems to stem from the fact that you tried to run dind as a non-root user. It's not supported by the vanilla dockerd as far as I know.

**Comment by mumoshu** [comment]
@bmbferreira Hey! Thanks for confirming.
Yeah, any contribution is always welcomed- but to be extra sure, your goal was to run `actions/runner` with a non-root user within the `runner` container in the runner pod, right? Our runner image sets the default user to `runner` which should map to uid 1000 in the container(although it won't map the exact uid in the host as far as I remember), so it's already a non-root user.

**Comment by bmbferreira** [comment]
> our goal was to run `actions/runner` with a non-root user within the `runner` container in the runner pod, right? Our runner image sets the default user to `runner` which should map to uid 1000 in the container(although it won't map the exact uid in the host as far as I remember), so it's already a non-root user.
Yes, I noticed that 😃 However, I think that setting a proper `securityContext` for the runner container (specially with `runAsNonRoot: true`) would also avoid using root that while doing `kubectl exec -it <pod-name> -c runner -- bash`. 🤔

**Comment by bmbferreira** [comment]
> our goal was to run `actions/runner` with a non-root user within the `runner` container in the runner pod, right? Our runner image sets the default user to `runner` which should map to uid 1000 in the container(although it won't map the exact uid in the host as far as I remember), so it's already a non-root user.
Yes, I noticed that 😃 However, I think that setting a proper `securityContext` for the runner container (specially with `runAsNonRoot: true`) would also avoid using root that while doing `kubectl exec -it <pod-name> -c runner -- bash`. 🤔

**Comment by mumoshu** [comment]
@bmbferreira Just to be sure, have you already tried that in a regular pod? I execed to a runner pod's runner container and `touch`ed a path to create a file. It was owned by `runner:runner` so I assume it's running the shell as the `runner` user 🤔

**Comment by bmbferreira** [comment]
> @bmbferreira Just to be sure, have you already tried that in a regular pod? I execed to a runner pod's runner container and `touch`ed a path to create a file. It was owned by `runner:runner` so I assume it's running the shell as the `runner` user 🤔

🤦‍♂️ pardon me, you are right. I tested with a custom image we had that is not using the default `runner` user 😬 If I use the default runner image of this repo it runs the shell as the `runner` user 👍
