### ISSUE TITLE
Update deprecated APIs

### ISSUE THREAD

**Issue by Hi-Fi** [actions-runner-controller/actions-runner-controller#144]
- Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
- Warning: admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
- Warning: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration

At least CRD requires also fixing of tests and the default value handling of protocol.

**Comment by callum-tait-pbx** [comment]
@mumoshu please add the `chore` label to this issue to prevent the bot killing it. This will certainly need doing or the solution will stop working on modern k8s instances

**Comment by jwalters-gpsw** [comment]
Any chance of updating admissionregistration.k8s.io/v1beta1 in the charts? We are getting "build" failures on lint.

**Comment by mumoshu** [comment]
@jwalters-gpsw Hey! Thanks for reporting. As I have other high-priority items now, would you mind submitting a PR for that? I thought we've already migrated to newer controller-runtime and controller-gen in #629 and upgraded admissionregistration API used in the kustomize config. Perhaps you can make similar manual changes in the chart.

**Comment by mumoshu** [comment]
Also note that CRDs have already been upgraded to the v1 API in #629

**Comment by mumoshu** [comment]
> I thought we've already migrated to newer controller-runtime and controller-gen in #629

Apparently, we only migrated to the newer API for newly generated resources. There are still a few remaining resources to be upgraded. You can try removing `webhookVersions=v1beta1` annotations in webhook-related types in our go code and run `make manifests` to regenerate.
