### ISSUE TITLE
Dumb-init - clarification around usage

### ISSUE THREAD

**Issue by zbenamram** [actions-runner-controller/actions-runner-controller#145]
Hi!

I was hoping @summerwind could provide some context around this commit: https://github.com/summerwind/actions-runner-controller/commit/c66916a4ee5bb2df448b0397b11f980a64c5ec78. What was the underlying issue you were seeing with the runner service / worker roles that required dumb initialization?

**Comment by ZacharyBenamram** [comment]
wondering if its around: https://github.com/actions/runner/blob/8279ae9a709dd2df948171d4bc87cf45d4879090/src/Runner.Worker/JobRunner.cs#L68
