### ISSUE TITLE
Servicemonitor - Configurable namespace

### ISSUE THREAD

**Issue by evan-hines-firebolt** [actions-runner-controller/actions-runner-controller#1490]
**Is your feature request related to a problem? Please describe.**
The service monitor should be deployable into a custom namespace.

**Describe the solution you'd like**
I would like to be able to set the serviceMonitorNamespace in the values.yaml file,

I'd be happy to implement if we agree on an API.

**Describe alternatives you've considered**
Possibly just deploy to {{ .Release.Namespace }} as well? Open to suggestion and discussion.

**Additional context**
The current service monitor implementation always goes to 'default'.

```yaml
{{- if .Values.metrics.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
  {{- with .Values.metrics.serviceMonitorLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "actions-runner-controller.serviceMonitorName" . }}
spec:
...
{{- end }}
```

**Comment by nicklev** [comment]
Hi there!

namespace: {{ .Release.Namespace }} is not very flexible.

For example the ARC is deployed in a dedicated namespace but kube-prometheus-stack usually is deployed under "monitoring" namespace.
This creates the following problem. We want all ServiceMonitors to be added under "monitoring" namespace for easier Prometheus configuration but namespace: {{ .Release.Namespace }} deploys the ServiceMonitor under ARC namespace.

In my opinion https://github.com/actions-runner-controller/actions-runner-controller/commit/d50be98bef03d890b4757624999f23ebdfd0a186
is a more flexible approach for ServiceMonitor deployment.
