### ISSUE TITLE
Support registering runners to enterprise level in addition to repository and organisation (GHE only)

### ISSUE THREAD

**Issue by Hi-Fi** [actions-runner-controller/actions-runner-controller#150]
API documentation:
https://docs.github.com/en/free-pro-team@latest/rest/reference/enterprise-admin#create-a-registration-token-for-an-enterprise

Hard to test without Enterprise admin rights, but maybe it can be made and then fixed if there's someone with suitable test environment.

**Comment by droidpl** [comment]
That feature would be cool, although it only works with PAT (unless we get GitHub Apps at the enterprise level). If you folks get this implemented I volunteer for testing it in one of my test instances. 😸

**Comment by mumoshu** [comment]
I thought we added support for this a while ago as documented in https://github.com/actions-runner-controller/actions-runner-controller#github-enterprise-support. Please feel free to test and report any issues. Thanks.
