### ISSUE TITLE
Publish on artifacthub.io

### ISSUE THREAD

**Issue by marcofranssen** [actions-runner-controller/actions-runner-controller#1502]
**Is your feature request related to a problem? Please describe.**

For better discoverability and just an additional entrypoint to this project it would be great to also publish the releases at [artifacthub.io](https://artifacthub.io/).

**Describe the solution you'd like**

It would be great if this controller and helm charts can be published on [artifacthub.io](https://artifacthub.io/).

See https://artifacthub.io/docs/topics/repositories/ on how to link the repository and get the releases visible here at [artifacthub.io](https://artifacthub.io/).

**Describe alternatives you've considered**

N.A. This thing can co-exist.

**Additional context**

N.A.

**Comment by marcofranssen** [comment]
What do you think? Would you accept a PR preparing some things? Still some action required on artifacthub.io by the maintainers though if I would prep a PR for you.

**Comment by marcofranssen** [comment]
@mumoshu any thougths?

**Comment by marcofranssen** [comment]
Is this project still active? Anyone here who can give a response on how to move this forward?

**Comment by mumoshu** [comment]
@marcofranssen Hey! This project is definitely active. But this project is driven by individual contributors like me who aren't paid enough for responding every issue and question- forgive me for not meeting your expection but it would be great if you could be patient.
Honestly speaking, the reason I put this at lower priority is that I just couldn't figure out the benefit of doing this.
We already publish the image to both Docker Hub and GHCR. You can already mirror it to whatever container image registry you like.
If we do this ourselves, does that mean we have to endlessly add support for additional container image registries as they come up...? Or artifacthub.io would be the last and the best container image registry we need to add?

**Comment by marcofranssen** [comment]
@mumoshu this is about making the helm chart discoverable. Artifcathub.io is not a registry. It is an index. The image will still be downloaded from the registry where you publish it and the helm chart is just indexed in artifacthub to be downloaded from where-ever you publish it.

**Comment by mumoshu** [comment]
@marcofranssen Thanks for clarifying! Just to be extra clear, what do you mean by "discoverable" exactly? Are you basically saying that it might be more common to look for the chart you want to use in artifacthub.io first, rather than reading the README to find out e.g. `https://actions-runner-controller.github.io/actions-runner-controller` which is our current helm chart repo?

**Comment by marcofranssen** [comment]
Whenever I search for helm charts I go first to artifacthub.io. Based on that I might be searching the repo to deep dive into the details of a chart.

**Comment by mumoshu** [comment]
@marcofranssen Thanks a lot for the detailed explanation! I'm convinced. This is absolutely a good idea.

I read the guide but am still unsure how I can actually "add" our helm chart repository to ArtifactHub.

The guide says:

> Once you have added your repository, you are all set up. As you add new versions of your charts or even new charts to your repository, they’ll be automatically indexed and listed in Artifact Hub.

But there's no mention of how you could add the repository 🤔

**Comment by mumoshu** [comment]
Okay, I figured it out. Sign up on ArtifactHub, go to "Control Panel", and you'll see the button to add a repository to ArtifactHub. There's also a mechanism to show me as the verified publisher of the chart so I'll try add some metadata to the chart for that.

**Comment by marcofranssen** [comment]
> Okay, I figured it out. Sign up on ArtifactHub, go to "Control Panel", and you'll see the button to add a repository to ArtifactHub. There's also a mechanism to show me as the verified publisher of the chart so I'll try add some metadata to the chart for that.

Awesome. This is going to make this project even more popular.
