### ISSUE TITLE
Unable to use custom image for action-runner-controller

### ISSUE THREAD

**Issue by swathida-byte** [actions-runner-controller/actions-runner-controller#1503]
I'm using chart version v.22.0 and I have downloaded action-runner-controller of that version and pushed to my docker registry and tried changing values.yaml file and added below part of code
dockerRegistryMirror: "***.com"
  image:
    repository: "***.com/releng/actions-runner-controller"
    tag: "v0.22.0"
    actionsRunnerRepositoryAndTag: "***.com/releng/custom-runner:1"
    dindSidecarRepositoryAndTag: "***.com/releng/docker:dind"
 while creating action-runner-controller-pod getting Crashloopbackoff error 
 logs:standard_init_linux.go:219: exec user process caused: exec format error
 under events:Back-off restarting failed container
 using k8s cluster

**Comment by mumoshu** [comment]
I think you get `exec format error` when you tried to run a binary for the wrong os/arch. Perhaps you built/pushed a wrong binary/image. Please check your build process.

**Comment by swathida-byte** [comment]
I pulled  using this docker pull summerwind/actions-runner-controller:v0.22.0 and pushed it to my docker registry , didnot make any changes in image

**Comment by mumoshu** [comment]
@swathida-byte This is how we built/pushed the v0.22.0 image. Please check if your container image repository supports multi-arch images or if your k8s node is not amd64 or arm64.
