### ISSUE TITLE
failed calling webhook "mutate.runnerdeployment.actions.summerwind.dev  ... lscontext deadline exceeded

### ISSUE THREAD

**Issue by klepiz** [actions-runner-controller/actions-runner-controller#1527]
### Controller Version

actions-runner-controller-0.19.0

### Helm Chart Version

0.24.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: example-runner
spec:
  repository: my-repo
  env: []
```

### To Reproduce

```markdown
1. I followed the steps to install runner actions from: https://github.com/actions-runner-controller/actions-runner-controller#installation. (I used a personal token access)
2. kubectl --namespace self-hosted-runners apply -f runner.yaml

got: Error from server (InternalError): error when creating "self-hosted-runner.yaml": Internal error occurred: failed calling webhook "mutate.runnerdeployment.actions.summerwind.dev": Post "https://actions-runner-controller-webhook.actions-runner-system.svc:443/mutate-actions-summerwind-dev-v1alpha1-runnerdeployment?timeout=10s": context deadline exceeded
```

### Describe the bug

Im trying to register a self-hoster runner on k8s and got a failling error when it tries to call mutate.runnerdeployment.actions.summerwind.dev. My nodes are bare metal so we are not using cloud. Can someone help to know what am I missing? or how to fix this? 
The certs controller looks good: 
```
# kubectl --namespace actions-runner-system get all
NAME                                            READY   STATUS    RESTARTS   AGE
pod/actions-runner-controller-bc58c5b87-2dm4q   2/2     Running   0          4m21s

NAME                                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/actions-runner-controller-metrics-service   ClusterIP  <.....>   <none>        8443/TCP   4m22s
service/actions-runner-controller-webhook           ClusterIP   <.....>    <none>        443/TCP    4m22s
service/controller-manager-metrics-service          ClusterIP   <.....>    <none>        8443/TCP   17m
service/webhook-service                             ClusterIP   <.....>    <none>        443/TCP    17m

NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/actions-runner-controller   1/1     1            1           4m22s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/actions-runner-controller-bc58c5b87   1         1         1       4m22s```

### Describe the expected behavior

Regsiter a self-hosted runner

### Controller Logs

```shell
.
```

### Runner Pod Logs

```shell
.
```

**Comment by mumoshu** [comment]
@klepiz Hey! This shouldn't be a bug in ARC. `context deadline exceeded` in this context basically means that your K8s control plane was unable to access the K8s service that is serving the admission webhook, which implies your cluster has a connectivity issue between the control plane and the pods.

I'd suggest checking pod-to-pod connectivity and the control-plane-to-pod connectivity, then pod-to-service connectivity by `kubectl exec`ing respective pods and then running `curl` against various pod IPs and services' cluster IPs.

**Comment by klepiz** [comment]
Im kind of new on k8s and not sure how to check `pod-to-pod connectivity and the control-plane-to-pod connectivity` and btw Im having something similar than this  https://github.com/actions-runner-controller/actions-runner-controller/issues/933#issuecomment-960337751 but I already try to delete the redundant for `mutatingwebhookconfiguration`  and `validatingwebhookconfiguration` but keep failing

**Comment by mumoshu** [comment]
It won't work without `mutatingwebhookconfiguration` and `validatingwebhookconfiguration` so I don't recommend removing them!
You can check pod IPs by running `kubectl get po -o syaml` and seeing the pod IP under the `status` fields. You can then exec into any of the pods or create new pod (that has `bash` or some other shell built into the container image) and run `kubectl exec -it $POD_NAME bash` to an interactive shell. From there, you should be able to run `curl` against other pod IPs and see if it works. Be sure the target pod needs to have a HTTP server running to respond the hTTP request sent by curl.

**Comment by klepiz** [comment]
```# kubectl exec -i -t -n actions-runner-system actions-runner-controller-bc58c5b87-2dm4q bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulting container name to manager.
Use 'kubectl describe pod/actions-runner-controller-bc58c5b87-2dm4q -n actions-runner-system' to see all of the containers in this pod.
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown
command terminated with exit code 126```

**Comment by mumoshu** [comment]
@klepiz You need to check if the K8s control-plane is able to access other pods or K8s services(' cluster IPs). So execing into ARC's controller-manager pod doesn't much sense to me. You'd instead find control-plane pods in the `kube-system` namespace.

**Comment by klepiz** [comment]
ah, well I have GL runners on that k8s cluster and works fine so it shouldn't be a communication issue

**Comment by klepiz** [comment]
also Im getting this 
```# kubectl get validatingwebhookconfiguration -o yaml github-actions-runner-actions-runner-controller-validating-webhook-configuration
Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "github-actions-runner-actions-runner-controller-validating-webhook-configuration" not found```

**Comment by mumoshu** [comment]
Do GitLab runners require working admission(mutating or validating) webhooks? There're only a few K8s features that require the K8s control-plane to directly access the cluster loads, like an admission webhook. So there might be chances that you can run GitLab runners fine while unable to run anything that depends on admission webhooks.

**Comment by mumoshu** [comment]
> `Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "github-actions-runner-actions-runner-controller-validating-webhook-configuration" not found`

This seems to indicate that you removed the validating webhook configuration from your cluster?

**Comment by klepiz** [comment]
> > `Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "github-actions-runner-actions-runner-controller-validating-webhook-configuration" not found`
> 
> This seems to indicate that you removed the validating webhook configuration from your cluster?

no, sorry I used the incorrect name of my validatingwebhookconfiguration

**Comment by mumoshu** [comment]
Could you also share logs from the ARC's controller-manager pod? Also, are you sure you're running ARC 0.24.0?

There're what you shared initially:

> Controller Version
> actions-runner-controller-0.19.0

> Helm Chart Version
> 0.24.0

And it looks like you're conflating ARC version with chart version. So I'm afraid you completely missed correctly choosing version numbers for ARC and the chart.

**Comment by klepiz** [comment]
![Screen Shot 2022-06-13 at 18 30 54](https://user-images.githubusercontent.com/56735755/173469039-270bd175-fddd-45f3-891f-61641183b47b.png)

**Comment by mumoshu** [comment]
Ok version numbers seem good

**Comment by klepiz** [comment]
```2022-06-13T17:43:12Z	INFO	controller.runnerset-controller	Starting workers	{"reconciler group": "actions.summerwind.dev", "reconciler kind": "RunnerSet", "worker count": 1}
2022-06-13T17:43:12Z	INFO	controller.horizontalrunnerautoscaler-controller	Starting workers	{"reconciler group": "actions.summerwind.dev", "reconciler kind": "HorizontalRunnerAutoscaler", "worker count": 1}
2022-06-13T17:43:12Z	INFO	controller.runnerpersistentvolume-controller	Starting workers	{"reconciler group": "", "reconciler kind": "PersistentVolume", "worker count": 1}
2022/06/14 00:15:59 http: TLS handshake error from 127.0.0.1:48070: EOF
2022/06/14 00:16:00 http: TLS handshake error from 127.0.0.1:48072: remote error: tls: bad certificate```
Im using the cert-manager from https://bitnami.com/stack/cert-manager/helm

**Comment by mumoshu** [comment]
@klepiz Maybe your cert-manager isn't installed correctly? It should provide a valid TLS certificate to ARC. I've never used bitnami's cert-manager chart so I can't say for sure what's going on there.

Is it supposed to work the same as the official cert-manager manifests/chart in the first place? 🤔

**Comment by klepiz** [comment]
yeah, it should be :/ but Im going to try with that one and see if there is any difference

**Comment by klepiz** [comment]
did you know if there is an specific steps or configuration that I should use for that one?

**Comment by mumoshu** [comment]
Nope. It should just work on a standard K8s cluster if you followed https://github.com/actions-runner-controller/actions-runner-controller#installation

**Comment by klepiz** [comment]
following this: https://cert-manager.io/docs/installation/helm/#2-update-your-local-helm-chart-repository-cache 
```
Not ready: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.233.42.80:443: i/o timeout
Not ready: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded
```

**Comment by klepiz** [comment]
i fixed that 

> following this: https://cert-manager.io/docs/installation/helm/#2-update-your-local-helm-chart-repository-cache
> 
> ```
> Not ready: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.233.42.80:443: i/o timeout
> Not ready: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded
> ```
 ^^ I fixed by running this 
```  223  13/06/22 21:44:23 kubectl delete mutatingwebhookconfiguration.admissionregistration.k8s.io cert-manager-webhook
  224  13/06/22 21:44:28 kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io cert-manager-webhook
```

and then I just got the same exact issue 
```
# kubectl apply -f runner.yaml
Error from server (InternalError): error when creating "runner.yaml": Internal error occurred: failed calling webhook "mutate.runner.actions.summerwind.dev": Post "https://actions-runner-controller-webhook.actions-runner-system.svc:443/mutate-actions-summerwind-dev-v1alpha1-runner?timeout=10s": context deadline exceeded
```

**Comment by mumoshu** [comment]
Check ARC's controller logs. Also, i'd recommend a clean install of ARC

**Comment by mumoshu** [comment]
And you're still seeing the below error?

```
# kubectl apply -f runner.yaml
Error from server (InternalError): error when creating "runner.yaml": Internal error occurred: failed calling webhook "mutate.runner.actions.summerwind.dev": Post "https://actions-runner-controller-webhook.actions-runner-system.svc:443/mutate-actions-summerwind-dev-v1alpha1-runner?timeout=10s": context deadline exceeded
```

Then the only possibility is that your kube-apiserver is somehow unable to access the K8s service of ARC's admission webhook server. Please ensure that your kube-apiserver is able to access K8s services (and their backend pods running on data-plane nodes).

**Comment by mikejoseph-ef** [comment]
same here

AWS EKS: 1.22.0
**APP VERSION: 0.24.1**
**CHART: ARC-0.19.1**

> Error from server (InternalError): error when creating "self-hosted-runner.yaml": Internal error occurred: failed calling webhook "mutate.runnerdeployment.actions.summerwind.dev": failed to call webhook: Post "https://actions-runner-controller-webhook.actions-runner-system.svc:443/mutate-actions-summerwind-dev-v1alpha1-runnerdeployment?timeout=10s": context deadline exceeded

tried `kubectl delete ValidatingWebhookConfiguration general-1-gh-runners-actions-runner-controller-validating-webhook-configuration`
got:

> Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "general-1-gh-runners-actions-runner-controller-validating-webhook-configuration" not found

my security group settings for EKS:
```tf
  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    ingress_cluster_metricserver = {
      description                   = "Cluster to node 8443 (Metrics Server)"
      protocol                      = "tcp"
      from_port                     = 8443
      to_port                       = 8443
      type                          = "ingress"
      source_cluster_security_group = true 
    }
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }
```

**Comment by klepiz** [comment]
> And you're still seeing the below error?
> 
> ```
> # kubectl apply -f runner.yaml
> Error from server (InternalError): error when creating "runner.yaml": Internal error occurred: failed calling webhook "mutate.runner.actions.summerwind.dev": Post "https://actions-runner-controller-webhook.actions-runner-system.svc:443/mutate-actions-summerwind-dev-v1alpha1-runner?timeout=10s": context deadline exceeded
> ```
> 
> Then the only possibility is that your kube-apiserver is somehow unable to access the K8s service of ARC's admission webhook server. Please ensure that your kube-apiserver is able to access K8s services (and their backend pods running on data-plane nodes).

yeah, Im still getting that issue

**Comment by mikejoseph-ef** [comment]
np, should I make a PR with some troubleshooting docs about this error? I've noticed it is a reoccurring issue @mumoshu

**Comment by Karen-Lepiz-Imprivata** [comment]
yes please, it will be nice :)

**Comment by mumoshu** [comment]
@mikejoseph-ef Hey. I'd appreciate it very much if you could do so!

**Comment by worawatwi** [comment]
For my case, I have to create firewall rule to allow communication from control plane to nodes as I use private kubernetes node.

**Comment by 0xF4D3C0D3** [comment]
> WORKED after deleting:
> 
> ```shell
> kubectl delete validatingwebhookconfiguration validating-webhook-configuration
> kubectl delete mutatingwebhookconfiguration mutating-webhook-configuration
> kubectl delete mutatingwebhookconfiguration actions-runner-controller-mutating-webhook-configuration
> kubectl delete validatingwebhookconfiguration actions-runner-controller-validating-webhook-configuration
> ```

I had the exactly same issue with this issue, and after above deletions, it works! Thanks a lot
It would be much better if we understand why this happens and patch this for no human intervention like above : )

**Comment by mumoshu** [comment]
@0xF4D3C0D3 Hey! The issue happens when you had conflicting/dangling ARC-related resources from its previous installation. Note that at least one validating and mutating webhook configuration are needed for ARC to function correctly.

**Comment by mumoshu** [comment]
Closing as documented via https://github.com/actions-runner-controller/actions-runner-controller/pull/1558
