### ISSUE TITLE
Autoscaling on `CountRunnersBusy`

### ISSUE THREAD

**Issue by FalconerTC** [actions-runner-controller/actions-runner-controller#1545]
**Is your feature request related to a problem? Please describe.**
I currently use `PercentageRunnersBusy` for autoscaling and it's working decently well but when a pool gets large (30+ runners) it results in a lot of extra waste when using a `scaleUpThreshold` of 75%. I would ideally like to see a count based `scaleUpThreshold` so that I can have a policy like "Always have 2 runners ready to receive jobs"

Maybe the better approach here is to look into the webhook server, but it seems like the webhook server scales up exactly to demand and I want to minimize queue times by always having ready runners instead

**Comment by mumoshu** [comment]
@FalconerTC Hey! Thanks for reporting. My impression was that your use-case can be still served by the webhook-based autoscaling.
How about giving your HRA `minReplicas: 2` and enable the webhook-based autoscaling? This way the webhook server adds an extra runner per each workflow_ job event "on top of the 2 min replicas", which basically translates to "Always have 2 runners ready to receive jobs".
