### ISSUE TITLE
Support restricting `workflow_job` events by a repository whitelist

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#1635]
Ref https://github.com/actions-runner-controller/actions-runner-controller/issues/1607

Add support for a repository whitelist like we have for the `check_run` event but for the `workflow_job` event so we can remove support for all events other than `workflow_job`

**Comment by mumoshu** [comment]
@toast-gear Hey! I'm quite confused. Why do you need it over HRA + RunnerDeployment of repository runners?

**Comment by toast-gear** [comment]
No community use case for this as far as we are aware https://github.com/actions-runner-controller/actions-runner-controller/issues/1607#issuecomment-1190144259
