### ISSUE TITLE
Print the ARC version number on startup

### ISSUE THREAD

**Issue by mumoshu** [actions-runner-controller/actions-runner-controller#1654]
This would make it unnecessary for me to ask anyone how they upgraded ARC or which ARC version they are running when providing user support.

**Comment by ViktorLindgren95** [comment]
Just a simple const that we set manually each update that print at the start of init/main function call or is there an internal version handling that should be called instead?

This is low hanging enough for me to do 🤣

**Comment by mumoshu** [comment]
This has been resolved via #1659.
Thank you so much for your contribution @ViktorLindgren95!!
