### ISSUE TITLE
Runnerautoscaling Failure - Message - "Failed to list workflow runs" GET https://api.github.com/repos/org-name/repo-name/actions/runs?per_page=100&status=queued: 404 Not Found []"

### ISSUE THREAD

**Issue by sabhika** [actions-runner-controller/actions-runner-controller#1702]
### Discussed in https://github.com/actions-runner-controller/actions-runner-controller/discussions/1701

<div type='discussions-op-text'>

<sup>Originally posted by **sabhika** August  8, 2022</sup>
Hi Team,

Version used :

Action-runner-controller - chart action-runner-controller-0.20.2
cert-manager- cert-manager-v1.9.1

Am setting up autoscaling at organization level using pull-driven scaling mechanism.
Using EKS cluster and Github Actions.

My runnerdeployment and HRA file

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
  namespace: gh-runner
spec:
  template:
    spec:
      organization: org-name
      labels:
        - controller-runner
      image: my-custom-image-from-ecr

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
  namespace: gh-runner
spec:
  scaleDownDelaySecondsAfterScaleOut: 120
  scaleTargetRef:
    name: runner-deployment
  minReplicas: 0
  maxReplicas: 5
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - repo1
    - repo2

Two issues:
1. I am not able to add label to the runner using the runnerdeployment label attribute
2. I am not able to scale up the runners. It says failed to list workflows- 404 not found.

@mumoshu  Can you please assist me in resolving this ASAP or letting me know if am missing anything from my end. Thanks in advance.

</div>

**Comment by mumoshu** [comment]
@sabhika Sorry, but we don't use Issues for Q&A and user support! Forgive me to close this as you already have a corresponding discussion.
404 on GitHub API call error means you're using wrong token or Github App credentials.
You do have configured `controller-runner` correctly in the RunnerDeployment spec so I can't see why it doesn't add labesl to the github actions runners. My guess is you're just seeing wrong runners. Match runners in Actions and in your K8s clusters by their names and see how they look.

**Comment by sabhika** [comment]
@mumoshu  I understand you closed the issue. Can you please check the discussion space. I have updated it with latest Github app credentials and still seeing same issue. Label is also not getting added.
