### ISSUE TITLE
Expose additional runnerDeployment metrics

### ISSUE THREAD

**Issue by mstevanic** [actions-runner-controller/actions-runner-controller#1705]
**Is your feature request related to a problem? Please describe.**
For horizontalRunnerAutoscaler there are specs and status metrics exposed (min and max replicas and desired replicas), but for runnerDeployment there is only desired replicas, and no ready, updated and available.

**Describe the solution you'd like**
prometheus metrics endpoint should expose all the status data for the runnerDeployment -  the ones that are displayed with `kubectl get`

**Describe alternatives you've considered**
writing a separate exporter does not fell like the most clean solution.

**Additional context**
By having the desired, ready, updated and available metrics, we could spot and alert for different issues. For example when cluster autoscaler takes too long (desired is larger than available for some threshold time ) etc...

We have modified latest release (`0.25.2`) with additional metrics added, and we run it for few days in our infrastructure. I will be more than happy to create a PR if you think this will be useful for everyone.

**Comment by shinji62** [comment]
@mumoshu Same request here, I saw this PR being merge https://github.com/actions-runner-controller/actions-runner-controller/pull/1720, which is what we want but one things which is a bit of an issues, the requirement for the 3.6 which is fresh new, and updating GHES in big company take some time..So any chance this can be cherry pick on 0.25.2 (before the 3.6 requirement)

**Comment by mumoshu** [comment]
@shinji62 Hey! I hear you, but unfortunately, we won't be adding new features to the stable version of ARC because that will further consume our already limited human resource. That said, I think it's not super hard to cherry-pick some changes into the stable version of ARC by yourself and pushing the container image, as we do provide handy make targets and our release automation github actions workflow you can use for reference.

@mstevanic I'd appreciate it if you could submit the pull request to add it to the edge version of ARC, which is going to be 0.26.0 real soon.
Do you by any chance still have some time to contribute?

**Comment by JamesAskew** [comment]
Are there any additional steps required to enable the new metrics introduced in #1720? 

I am running version 0.26.0 of the app, but can't see them appearing in prometheus.

Not sure if I am missing something obvious, or if something is wrong with my install.

**Comment by mumoshu** [comment]
It should work out of the box!

**Comment by mumoshu** [comment]
@JamesAskew Hey. Would there by any chance that you're using webhook-based HRAs? You won't see the new metrics in that case. See https://github.com/actions-runner-controller/actions-runner-controller/issues/1867#issuecomment-1260754150 for more info.

**Comment by JamesAskew** [comment]
> @JamesAskew Hey. Would there by any chance that you're using webhook-based HRAs? You won't see the new metrics in that case. See [#1867 (comment)](https://github.com/actions-runner-controller/actions-runner-controller/issues/1867#issuecomment-1260754150) for more info.

Yeah we're using the webhook approach. Thanks for following up. I'll keep an eye on the #1814 pr.
