### ISSUE TITLE
Update Required PAT Permissions

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#1716]
When testing some PRs I noticed `manage_runners:org` is now a scope, we probably only need that instead of `admin:org (Full control)` but someone needs to test it.

**Comment by debugger24** [comment]
I can give it a try.

**Comment by debugger24** [comment]
Didn't work. Maybe its something they are working on but not fully ready yet.

```
"failed to create registration token: POST https://api.github.com/orgs/demo-gh-app/actions/runners/registration-token: 403 Must have admin rights to Repository. []"}
```

[Docs also says it needs `admin:org`](https://docs.github.com/en/rest/actions/self-hosted-runners#create-a-registration-token-for-an-organization
)

PAT scope while testing

`admin:org, admin:org_hook, admin:public_key, admin:repo_hook, notifications, repo, workflow`

**Comment by toast-gear** [comment]
Lame! OK cheers for testing @debugger24, I'll close this for now then.

**Comment by toast-gear** [comment]
When this scope is working I am expecting to see it referenced as the scope required under https://docs.github.com/en/rest/actions/self-hosted-runners#create-a-registration-token-for-an-organization
