### ISSUE TITLE
Adding Additional Autoscaling Metrics to Prometheus

### ISSUE THREAD

**Issue by debugger24** [actions-runner-controller/actions-runner-controller#1717]
**Is your feature request related to a problem? Please describe.**

I am using `horizontalrunnerautoscaler`, current it exports only min, max and desired count. I also want to track other metrics like replicas_desired_before, replicas_desired, num_runners, num_runners_registered, num_runners_busy, num_terminating_busy in case of PercentageRunnersBusy and similarly other metrics in webhook based autoscaler too to understand how my action runner behaved and accordingly I can adjust the autoscaling parameters.

**Describe the solution you'd like**
Add more metrics in `controllers/metrics/horizontalrunnerautoscaler.go`.

**Describe alternatives you've considered**
Currently I am parsing it from logs and using it in my dashboard but a better approach would be to export using prometheus.

**Additional context**

**Comment by debugger24** [comment]
Would be happy to work on this.

**Comment by mumoshu** [comment]
Hey 👋
This does sound like a nice addition to ARC! I'd appreciate it if you could submit a pull request for this ☺️
