### ISSUE TITLE
Ingress resource missing when using Pulumi provider

### ISSUE THREAD

**Issue by igordrnobrega** [actions-runner-controller/actions-runner-controller#1746]
### Controller Version

0.25.2

### Helm Chart Version

0.20.2

### Deployment Method

Other

### cert-manager installation

N/A

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  annotations:
    pulumi.com/autonamed: "true"
  creationTimestamp: "2022-08-10T17:32:58Z"
  generation: 895
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: github-organization-runner-a8615ec3
  namespace: github
  resourceVersion: "9260049"
  uid: a82345f8-e996-474e-83ef-e5edc892189e
spec:
  effectiveTime: "2022-08-23T22:39:03Z"
  replicas: 0
  selector: null
  template:
    metadata: {}
    spec:
      dockerdContainerResources: {}
      dockerdWithinRunnerContainer: true
      group: staging
      image: summerwind/actions-runner-dind:v2.294.0-ubuntu-20.04
      labels:
      - staging
      organization: <organization>
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
        requests:
          cpu: "2"
          memory: 4Gi
      serviceAccountName: github-organization-runner
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: github-runners
status:
  availableReplicas: 0
  desiredReplicas: 0
  readyReplicas: 0
  replicas: 0
  updatedReplicas: 0
-----------------------------------------
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  annotations:
    pulumi.com/autonamed: "true"
  creationTimestamp: "2022-08-10T17:39:45Z"
  generation: 241
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: github-organization-runner-autoscaller-7b3d230b
  namespace: github
  resourceVersion: "9260034"
  uid: be304711-f3aa-4ce0-a405-0efe6829775b
spec:
  maxReplicas: 5
  minReplicas: 0
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    name: github-organization-runner-a8615ec3
  scaleUpTriggers:
  - amount: 1
    duration: 5m0s
    githubEvent:
      workflowJob: {}
status:
  desiredReplicas: 0
  lastSuccessfulScaleOutTime: "2022-08-23T22:39:03Z"
```

### To Reproduce

```markdown
const chart = new k8s.helm.v3.Chart(product, {
  chart: 'actions-runner-controller',
  fetchOpts: {
    repo: 'https://actions-runner-controller.github.io/actions-runner-controller',
    version: chartVersion,
  },
  // path: '../../../actions-runner-controller/charts',
  namespace: namespace.metadata.name,
  values: {
    replicaCount: 2,
    authSecret: {
      create: true,
      github_token: configurations.requireSecret('token'),
    },
    githubWebhookServer: {
      enabled: true,
      ingress: {
        enabled: true,
        ingressClassName: `nginx-public`,
        hosts: [
          {
            host: `${product}.${domain}`,
            paths: [
              {
                path: '/actions-runner-controller-github-webhook-server',
                pathType: 'Prefix',
              },
            ],
          },
        ],
      },
    },
  },
});
```
1. Using [Pulumi K8s Chart provider](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/)
2. run `pulumi up` with the above setup in an `index.ts` file

### Describe the bug

From the Helm Chart values, I should be getting an Ingress resource, but it doesn't create the resource. From the above code, you can see the commented line `// path: '../../../actions-runner-controller/charts',` where I performed some tests with a local clone of this repository, and this works as expected it creates the Ingress resource.

I'm attaching a screenshot when running with the fetched Helm Chart, where it tries to delete the created Ingress resource.
![Screen Shot 2022-08-23 at 18 58 43](https://user-images.githubusercontent.com/10760255/186286358-0e2f74fb-4eeb-4240-91cc-20a3a40b47c7.png)

### Describe the expected behavior

I expected the Ingress resource to be created when Helm Chart was fetched from the source.

### Controller Logs

```shell
N/A
```

### Runner Pod Logs

```shell
N/A
```

**Comment by mumoshu** [comment]
@igordrnobrega Hey! This looks like an issue in Pulumi based on your situation and information you provided. Could you confirm?

If you're still unsure, what if you used `helm` to render the chart? Does it still miss the ingress resource in the output?

**Comment by igordrnobrega** [comment]
@mumoshu let me try using helm command.

**Comment by igordrnobrega** [comment]
@mumoshu I just confirmed, and is indeed a problem with Pulumi Kubernetes provider.
I opened an issue there; thanks for your patience.

I explained the issue in https://github.com/pulumi/pulumi-kubernetes/issues/2153
