### ISSUE TITLE
Expose Idle/Busy state of runners

### ISSUE THREAD

**Issue by corneil** [actions-runner-controller/actions-runner-controller#1760]
**Is your feature request related to a problem? Please describe.**
I need to run many permutations of acceptance tests and the autoscaling takes to long to come online.
I know exactly how many runners I need. So I want to be able to change the number of runners requested based on how many I need and how many is idle.

**Describe the solution you'd like**
kubectl get runners should include busy/idle information about the runners. At the moment the status seems to reflect to pod status only.
Maybe some other resource may contain that information even a new CRD.

**Describe alternatives you've considered**
gh cli doesn't provide information on action runners status like the UI does.

**Additional context**

**Comment by mumoshu** [comment]
@corneil Hey! We've recently merged #1268 which seems to do exactly what you want.
Could you confirm?

**Comment by mumoshu** [comment]
> run many permutations of acceptance tests 

BTW, I'm trying to automate exactly this by enhancing https://github.com/actions-runner-controller/actions-runner-controller/blob/master/test/e2e/e2e_test.go.
I'd appreciate it if you could give it a shot and contribute anything 😄

**Comment by corneil** [comment]
This looks like it will provide what I need. 
If I launch a job that is going to require a certain number of runners and I can determine the number of idle runners I can easily update the replicas or minReplicas to ensure a certain number is available as quickly as possible.

**Comment by mumoshu** [comment]
@corneil Hey! Thanks for confirming. Just to be sure, are you talking about a potential feature request to enhance RunnerDeployment so that `kubectl get runnerdeployment` shows idle replicas number next to the desired and available replicas?

**Comment by mumoshu** [comment]
Or, you're just stating that https://github.com/actions-runner-controller/actions-runner-controller/pull/1268 would just resolve all your issues so you'll be testing https://github.com/actions-runner-controller/actions-runner-controller/pull/1268 and closing this issue once it works?

**Comment by corneil** [comment]
@mumoshu If the Idle status is exposed we can determine how much we need to scale the cluster pre-emptively.
Which release contains this?

**Comment by mumoshu** [comment]
0.26.0 is going to be the first version of ARC that contains #1268.

**Comment by corneil** [comment]
I'm now running ARC 0.26.0 and I don't see anything different from previous versions when using `kubectl get runnerdeployments` The pod status.phase also just shows Running only even when some are definetly idle

**Comment by mumoshu** [comment]
Hey. Please see the new `runner.statusUpdateHook.enabled` helm chart value and the new ARC flag named `--runner-status-update-hook` to enable it. It's currently an optional feature because enabling it results in giving ARC and runners more permissions on your cluster.

**Comment by corneil** [comment]
I added:
```yaml
runner:
  statusUpdateHook:
    enabled: true
```
To the values.yml for the helm install. Now I don't get any desired entries in the list for that deployment.
Is there any additional permissions/roles required?

**Comment by mumoshu** [comment]
No, ARC is designed to create a service account with necessary permissions on demand, as long as you don't force runners to a specific serviceaccount.

**Comment by corneil** [comment]
I am now detecting different phases. Idle, Registering etc. :1st_place_medal:
