### ISSUE TITLE
Missing spec

### ISSUE THREAD

**Issue by apanzerj** [actions-runner-controller/actions-runner-controller#1766]
https://github.com/actions-runner-controller/actions-runner-controller/blob/623c84fa529b9dad4d6522759d5f730f2374b967/charts/actions-runner-controller/crds/actions.summerwind.dev_horizontalrunnerautoscalers.yaml#L171

If you look in the spec for `pull_request` there is `branches` and allows an array. We don't have that for pushes but the docs say you can do that... 

Should I make a PR for this?

**Comment by apanzerj** [comment]
(I also don't know how to use Kubebuilder so if tweaking the yml directly is not desired, then let me know...

**Comment by toast-gear** [comment]
Nope, we're removing support for all webhook events other than `workflow_job` https://github.com/actions-runner-controller/actions-runner-controller/issues/1607

**Comment by apanzerj** [comment]
👍
