### ISSUE TITLE
Support for using new real-time runner status updates with custom service account annotations

### ISSUE THREAD

**Issue by danxmoran** [actions-runner-controller/actions-runner-controller#1847]
**Is your feature request related to a problem? Please describe.**

We are trying to use the new functionality for real-time runner status updates added in v0.26.0. We set `runner.statusUpdateHook.enabled = true` in our Helm chart values, and saw the runners trying to update their statuses - the requests were all rejected with 403 errors. I read through the controller code and saw that (as far as I could tell) the custom RBAC needed to update statuses only applies if you don't specify a `serviceAccountName` in your `RunnerDeployment` specs, so I deleted that field and reapplied the YAMLs. This caused our jobs to start failing with different auth errors because we rely on the `eks.amazonaws.com/role-arn` annotation on the service account running each runner pod to trigger injection of AWS credentials.

**Describe the solution you'd like**

Either:

1. Ability to specify annotations for the custom service accounts generated by the controller
2. Ability to use a pre-generated service account and have the controller attach/detach the custom role bindings needed for real-time runner status updates as needed

**Comment by mumoshu** [comment]
@danxmoran Hey! Can you provide your SA permissions required by status update hook beforehand? Both 1 and 2 seem to complicate ARC code without much benefit. If it's a documentation issue that the document doesn't cover how to add additional permissions required by the status update hook to your existing SA, we'd just be able to enhance the documentation, not code.

**Comment by danxmoran** [comment]
@mumoshu yeah I can, that makes sense - this is why I shouldn't open tickets on Friday afternoons 😅

I do think adding some info about service-account expectations to the docs would be good.
