### ISSUE TITLE
Add check before assigning runners to the jobs present in queue

### ISSUE THREAD

**Issue by swathida-byte** [actions-runner-controller/actions-runner-controller#1865]
Can we run a script with a list of all the repositories and branches that can use the runner before assigning the runners to the job?
Is this feasible? If so where do I need to add the script in the https://github.com/actions-runner-controller/actions-runner-controller repository?

**Comment by swathida-byte** [comment]
In a big organization, we have repositories where developers are also admins.  As a GitHub runner group admin, we want to control which branches could use a particular runner group. As GitHub didn’t provide that option, is it possible to implement a check (by an external script), to only allow a few branches to user runners from a runner group?

**Comment by mumoshu** [comment]
@swathida-byte Hey. I believe no. It isn't something that ARC can control. I'd guess you'd have some possibility if you file an issue against `actions/runner` or against GitHub Actions. Probably something like a "branch visibility" that is similar to "runner group visibility" feature present in today's GitHub Actions would do the job.
