### ISSUE TITLE
helm commands are not working for installation

### ISSUE THREAD

**Issue by SejalParmar8796** [actions-runner-controller/actions-runner-controller#1888]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.

### Controller Version

0.20.2

### Helm Chart Version

latest

### Deployment Method

Helm

### cert-manager installation

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue

### Resource Definitions

```yaml
NA as the deployment itself is failing
```

### To Reproduce

```markdown
helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller 

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml


kubectl create -f https://github.com/actions-runner-controller/actions-runner-controller/releases/download/v0.20.2/actions-runner-controller.yaml 

helm upgrade --install --namespace actions-runner-system --create-namespace --wait actions-runner-controller actions-runner-controller/actions-runner-controller --set "githubWebhookServer.enabled=true,service.type=NodePort,githubWebhookServer.service.type=LoadBalancer"
```

### Describe the bug

Release "actions-runner-controller" does not exist. Installing it now.
Error: failed to download "actions-runner-controller/actions-runner-controller"

### Describe the expected behavior

it should create webhook server 

### Controller Logs

```shell
NA as the deployment itself is failing
```

### Runner Pod Logs

```shell
NA as the deployment itself is failing
```

### Additional Context

NA as the deployment itself is failing

**Comment by mumoshu** [comment]
@SejalParmar8796 Hey!

> Error: failed to download "actions-runner-controller/actions-runner-controller"

This is an error that happens when helm was unable to download the chart index or the chart archive from the specified repository and the URL. When it happens, it usually means you have network issues or the helm chart repository is temporarily unavailable.
Could you try once again and if it doesn't still work, you'd need to ensure the connection to "*.github.io" is allowed in your environment/machine/network/etc as that's the URL for a GitHub pages hosted site, and we use GitHub Pages for hosting the chart repository.
