### ISSUE TITLE
docs for installing GitHub App for organization without admin permissions

### ISSUE THREAD

**Issue by aliusmiles** [actions-runner-controller/actions-runner-controller#1897]
Docs for installing GitHub App for organization assume that user have admin access to org. I think I've found a way to do it without full admin, just with couple steps required from an actual admin (I could swear I've got there based on ARC docs but just cant find reference anymore)

Procedure is following:
1. request admin to grant user permission to [manage apps](https://docs.github.com/en/organizations/managing-access-to-your-organizations-apps/adding-github-app-managers-in-your-organization)
2. org tab 'settings' now will be available with just GitHub Apps section
3. create app, but set `Where can this GitHub App be installed?` to `Any account` - otherwise user can't see Install option and org admin can't see app 🤷
4. click install app which will only create request to install
5. ask admin to confirm installation
6. proceed with ARC instructions (get installation ID, etc)

I can create PR with adding this to docs, but just not sure if it is actually a good way to setup GitHub app for ARC? Anyway, perhaps this issue will at least be usable for someone in a similar situation.

**Comment by mumoshu** [comment]
@aliusmiles Hey! Thanks a lot for your suggestion. This does sound like it can be a preferred way to install GitHub App. I think not everyone who has access to the infrastructure that needed to provision a cluster and install ARC onto the cluster is a GitHub org admin.
Would you mind submitting a pull request?

**Comment by aliusmiles** [comment]
Will work on PR this weekend.

So far the only other thing needed from admin is runner groups creation. Webhook and events subscription works just fine with app.

**Comment by mumoshu** [comment]
@aliusmiles Hey! Thanks for your confirmation. We've been discussing this among ARC maintainers and realized that, although the information itself is very helpful, adding every variant of configurations like this one can build up an expectation that ARC maintainers would be knowledgeable and expertise for every possible configuration options in GitHub, which isn't going to be true.
Sorry for the back and forth, but can you reformat your pull request into a "show-and-tell" GitHub Discussion instead?
That way, anyone can update it, and I can redirect folks to it when needed.

**Comment by aliusmiles** [comment]
Finally got to finish it: https://github.com/actions-runner-controller/actions-runner-controller/discussions/1933
