### ISSUE TITLE
Ability to collect logs from docker-in-docker container

### ISSUE THREAD

**Issue by RobKenis** [actions-runner-controller/actions-runner-controller#1904]
**Is your feature request related to a problem? Please describe.**
We are running some jobs using a container managed by docker:dind. When this process fails, it is hard to debug the process because logs are nowhere to be found. It is unclear where the container logs are sent. When using `docker ps`, the container seems to be started using `tail -f /dev/null` as a command. As a result, we have no idea where the logs are and how to collect them.

**Describe the solution you'd like**
- Container logs are stored in a configurable directory, by default `/var/lib/docker/containers/logs/`
- docker-in-docker containers log to stdout, so we can capture the logs by watching the log files in the `docker:dind` container.

**Describe alternatives you've considered**
We have considered running fluentbit as a sidecar container and mount the log directory in both containers. The issue is that the logs don't show up on the filesystem.

**Comment by mumoshu** [comment]
@RobKenis Thanks for the feedback and the write up!

> docker-in-docker containers log to stdout, so we can capture the logs by watching the log files in the docker:dind container.

I'd prefer this over the other option as the first step because writing logs to the fs introduces another layer the operator needs to take care of in the system.

**Comment by RobKenis** [comment]
@mumoshu Can I help with implementing this solution? I can't find where `tail -f /dev/null` is configured.

**Comment by mumoshu** [comment]
@RobKenis Sorry but I don't know either. I see no explicit occurrence of `tail -f /dev/null` in ARC, the docker:dind entrypoint https://github.com/docker-library/docker/blob/c13cbee1cfd9d7582f7b2e9f958cf24e39b64715/20.10/dind/dockerd-entrypoint.sh and ARC's entrypoint scripts https://github.com/actions-runner-controller/actions-runner-controller/tree/master/runner
