### ISSUE TITLE
Single RunnerDeployment in Multiple Organizations/User Namespaces?

### ISSUE THREAD

**Issue by gwynforthewyn** [actions-runner-controller/actions-runner-controller#1935]
**Is your feature request related to a problem? Please describe.**
I have been using actions-runner-controller to host runners for a github enterprise installation. The runners are configured for an Organization, and they work well there.

However, when I fork a repository from the Organization into my own namespace the runners are no longer available. I believe this is because the runners are exclusively registered to work in an organization, and do not have either appropriate authentication for my personal namespace or a way to get registered for my personal namespace.

I would like to have CI/CD in both organization repositories and in personal namespaces, so that me and my software team can all enjoy the benefits of CI/CD while prototyping new projects in our personal namespaces.

**Describe the solution you'd like**
I would like to be able to register a single RunnerDeployment into multiple github repositories, with the authentication brokered by a github app that each user has installed into their accounts.

**Describe alternatives you've considered**
The only solution I see to this today is to create separate RunnerDeployments with separate configurations. This works, but it means running many deployments at once and it seems inefficient. 

I know this is a volunteer project, so I'd be happy to try to do any heavy lifting with some direction. I'm just not sure where to start.

**Comment by mumoshu** [comment]
> but it means running many deployments at once and it seems inefficient.

@gwynforthewyn Hey! What do you mean by "running many deployments at once", and how your proposed feature solves the problem?
At glance, the best possible solution for your problem might be to write another K8s controller or a GitHub Actions workflow that detects the repository once forked, and deploy RunnerDeployment for the forked repository.

**Comment by gwynforthewyn** [comment]
> or a GitHub Actions workflow that detects the repository once forked, and deploy RunnerDeployment for the forked repository.

That's a great idea

----

By "running many deployments at once", I meant running a lot of deployments of the runner-controller, with each having a unique configuration for authenticating to github enterprise server. I wasn't clear, sorry.

I _think_ that what prevents me from having multiple users/organisations use the same runner controller  is that code that performs the authentication callback to the github server requires an authentication method that is either unique to a user account or to an organization. My reasoning for suggesting a github app I had hoped that I had thought that once each user installed the github app then it would provide authentication for their github namespace; I had not realised that a user has to install the github app, which generates a unique installation ID, and so I cannot share a single github app's authentication token amongst multiple users.

I _think_ if I can chat with our IT team about setting up the runners to be configured at the Enterprise level then the runners are available to everyone, but I've never tried to configure that so I'm uncertain whether there are further permissions grants required for that.

**Comment by gwynforthewyn** [comment]
I'm going to close this out; after chatting with our IT folks, I think I can meet what I was looking for using a runner group and enterprise-wide runners.

Thanks for your time!
