### ISSUE TITLE
Possibility to watch multiple (defined) namespaces from a single controller

### ISSUE THREAD

**Issue by michaelgrossopt** [actions-runner-controller/actions-runner-controller#1937]
**Is your feature request related to a problem? Please describe.**
Maybe I'm approaching this incorrectly, but our use case is having multiple runnerdeployments (for separating genpop, hi-performance, dev/prod, etc) each in their own namespace (to utilize k8s resource quotas).  We'd also like to host runners for GHEC and GHES on this same cluster (which requires separate controllers).  That all works great, but the challenge I've hit is the autoscaling webhook server is tied to the controller, so we're unable to point all GHEC webhooks at a single target and end up scaling the respective runnerdeployment.

**Describe the solution you'd like**
Ideally a single controller could watch multiple namespaces.

**Describe alternatives you've considered**
We could run separate k8s clusters between GHEC and GHES but I'd rather not multiply our cluster count (and overhead).  Or run a service that would accept all incoming webhooks and route to the appropriate webhook server/controller.  Perhaps there was a design decision to only watch a single namespace that I'm unaware of and would necessitate looking further at alternatives.

**Additional context**
If I haven't explained my situation well let me know and I'll do my best to clarify my thoughts.  Thanks!

**Comment by mumoshu** [comment]
@michaelgrossopt Hey! Quick question- are you saying that you want ARC to handle two webhooks for receiving `workflow_job` events, one for GHEC and another for GHES?

> We could run separate k8s clusters between GHEC and GHES

Another option is to deploy two instances of ARC onto one cluster. Would it work for you?

**Comment by michaelgrossopt** [comment]
Hello @mumoshu sorry, I was out of town and missed your response - we'd like for ARC to watch multiple namespaces - so we can distribute the GHEC runners into namespaces by group (for quota application), but still be managed by a single controller so we can point the webhooks to a single location at the enterprise level in GHEC.  And similarly for GHES, (multiple namespaces watched by the "GHES" controller).  

Multiple instance of ARC work great for us, the limitation we hit is them only watching a single namespace per controller, which forces us to manage the web hook destination in GHEC more granularly (instead of sending all of them to the "GHEC" arc controller).

Not sure if I've clarified or muddied it here - let me know if it's not clear or I'm trying to do something stupid.  Thanks!
