### ISSUE TITLE
Upgrade PodDisruptionBudget to policy/v1

### ISSUE THREAD

**Issue by lancehudson** [actions-runner-controller/actions-runner-controller#1949]
### What would you like added?

Upgrade PodDisruptionBudget to policy/v1

### Why is this needed?

policy/v1beta1 is deprecated in 1.21 and removed in 1.25

### Additional context

*Add any other context or screenshots about the feature request here.*

**Comment by mumoshu** [comment]
Hey! Please see #1931 for the fix.
