### ISSUE TITLE
Runner is deprecated and cannot receive messages

### ISSUE THREAD

**Issue by duhow** [actions-runner-controller/actions-runner-controller#1984]
### What would you like added?

Exit the Pod as **Failed** if **Runner version is deprecated**.

### Why is this needed?

I have multiple `RunnerDeployments` with different Docker images and different versions.
One of the pools had lots of Runners (and server instances) and did not run any job since the Runner was outdated.
(Note that we have `DISABLE_RUNNER_UPDATE` set in ARC settings).

```
Current runner version: '2.296.2'
2022-11-04 09:48:25Z: Listening for Jobs
An error occurred: Runner version v2.296.2 is deprecated and cannot receive messages.
Runner listener exit with retryable error, re-launch runner in 5 seconds.
```

The expectation of having the Pod reporting as Failed is to trigger Monitoring to acknowledge there's an issue with Runners themselves.

**Comment by arash-bizcover** [comment]
@duhow The sad truth is Github Actions design is poor on updates, we are forced to keep our clients replaced every time a new version is released (usual stupid leftist design - by Microsoft this time)

`DISABLE_RUNNER_UPDATE` just avoid automatic updates on older runner startup script. It doesn't mean the older version works though 😆 ain't that ridiculous

**Comment by duhow** [comment]
I understand, still disabling the update feature is to ensure we have the Runner up and ready ASAP.
So regarding the Pod Exit behaviour, do you consider it should be ok to do?

**Comment by toast-gear** [comment]
https://github.com/actions-runner-controller/actions-runner-controller/pull/1988 I have added a note but this isn't something to be solved on the ARC side. GitHub shouldn't treat this as a retryable error if updates are disabled as the runner will never get allocated a job.
