### ISSUE TITLE
Operation Cancelled: Matrix ends up cancelling more than a single runner consistently

### ISSUE THREAD

**Issue by bobleujr** [actions-runner-controller/actions-runner-controller#1985]
### Checks

- [X] I've already read https://github.com/actions-runner-controller/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.26.0

### Helm Chart Version

0.21.1

### CertManager Version

1.9.1

### Deployment Method

Helm

### cert-manager installation

I installed the helm chart https://cert-manager.io/docs/installation/helm/#installing-with-helm using CRDs

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions-runner-controller/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions-runner-controller/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner
  namespace: github
spec:
  replicas: 2
  template:
    spec:
      repository: <myproj>
      resources:
        limits:
          cpu: "7.5"
          memory: "27Gi"
        requests:
          cpu: "7.5"
          memory: "27Gi"
      nodeSelector:
        cloud.google.com/gke-nodepool: preemptible-2

-- 

helm upgrade --install --namespace github --create-namespace\
  --set=authSecret.create=true\
  --set=authSecret.github_token="<TOKEN>"\
  --set=nodeSelector."cloud\\.google\\.com/gke-nodepool"=general-pool\
  --set=resources.requests.cpu="1" --set=resources.requests.memory="2Gi"\
  --wait actions-runner-controller actions-runner-controller/actions-runner-controller
```

### To Reproduce

```markdown
1. Define a matrix run with 2 targets on github
2. Set the job to run on `self-hosted`
```

### Describe the bug

I am running GKE 1.22.12-gke.2300, my controller runs on a persistent node pool and my runners are in a preemptible node pool. I have a job that runs on a matrix with 2 targets only and my RunnerDeployment has 2 replicas (fixed, I removed autoscaling to simplify my tests and it still has the problem). Both jobs run `docker run ...` commands, so it depends on docker. My nodes have plenty RAM, 27GB and I have also tried supplying my `docker run` with `-m 25Gb` to isolate the possibility of OOM.

Once the matrix starts, both jobs execute until the first one fails (for a known reason such as a broken test), but suddenly, the second gets canceled almost always 20s after the first one. It's probably just a deterministic coincidence but I am adding it nonetheless. The message that appears in the runner is : `Error: The operation was canceled.` and from github debugger logs
```
##[debug]System.OperationCanceledException: The operation was canceled.
##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.Handlers.CompositeActionHandler.RunStepAsync(IStep step)
```

### Describe the expected behavior

I would expect the job to run until the end and not be cancelled

### Whole Controller Logs

```shell
https://gist.github.com/bobleujr/ad6309a9875e5b2b2cfeacd3f164f651
```

### Whole Runner Pod Logs

```shell
https://gist.github.com/bobleujr/ad6309a9875e5b2b2cfeacd3f164f651
```

**Comment by mumoshu** [comment]
That error is emitted by "actions/runner", not ARC. Would there by any chance that it's an expected behavior of the runner, where it cancels other concurrent jobs from the same matrix if one of the jobs failed? May I ask how this can be a bug in ARC...?

**Comment by bobleujr** [comment]
@mumoshu I am closing this issue since I found the root cause!
