### ISSUE TITLE
version 0.13.1 (probably also .0) no longer work

### ISSUE THREAD

**Issue by mabushey** [actions-runner-controller/actions-runner-controller#216]
We had actions-runner-controller running with 0.9.3, but it recently broke. Trying to use 0.13.1 results in controller-manager logs that mostly contain:
```
E1130 20:51:45.944769       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20190918160344-1fbdaa4c8d90/tools/cache/reflector.go:96: Failed to list *v1alpha1.Runner: the server could not find the requested resource (get runners.actions.summerwind.dev)
```

Trying version 0.12.0 has much cleaner logs, but when I try to rerun a job in GitHub it still says "Starting your workflow run..." until it times out.

We did upgrade cert-manager from 1.0.2 to 1.1.0. Is that a problem? I verified it could create `selfsigned-cert`.

**Comment by mumoshu** [comment]
@mabushey Hey! Could you try running `kubectl get crd` on your cluster and report back the result? I suspect you're actually missing the `runners.actions.summerwind.dev` CRD in your cluster.

**Comment by mabushey** [comment]
Thanks for the super fast response @mumoshu !

```
✗  kubectl get crd | grep summerwind
horizontalrunnerautoscalers.actions.summerwind.dev   2020-11-30T20:48:10Z
runnerdeployments.actions.summerwind.dev             2020-11-30T20:48:10Z
runnerreplicasets.actions.summerwind.dev             2020-11-30T20:48:10Z
runners.actions.summerwind.dev                       2020-11-30T23:33:36Z
```
Looks like it's there...

This is probably relevant:
```
✗  kubectl -n github-runner get HorizontalRunnerAutoscaler
NAME                               MIN   MAX   DESIRED
organizational-runner-autoscaler   2     12    2

✗  kubectl -n github-runner get RunnerDeployment          
NAME                    DESIRED   CURRENT   READY
organizational-runner   2                   
```

**Comment by mabushey** [comment]
I completely removed the `actions-runner-system` namespace, creates the ns and then the cert. I applied `actions-runner-controller.yaml` with version 0.13.1. Now the `runners.actions.summerwind.dev ` CRD is missing:
```
✗  kubectl get crd | grep summerwind                                      
horizontalrunnerautoscalers.actions.summerwind.dev   2020-12-01T01:08:06Z
runnerdeployments.actions.summerwind.dev             2020-12-01T01:08:06Z
runnerreplicasets.actions.summerwind.dev             2020-12-01T01:08:07Z
```

**Comment by mabushey** [comment]
Got it running! I had to blow everything away (every last CRD, cluster role, clusterrolebinding, ect) and delete the installation. With a new App ID, Installation ID, and pem key it's back up and running.

**Comment by reiniertimmer** [comment]
It's strange, I have seen that before as well on a clean installation.

The first apply installs all CRDs _except_ `runners.actions.summerwind.dev`.
Second apply configures all the others, and creates the runner CRD

Strange, I'm not sure what is causing this (need to dive in)
