### ISSUE TITLE
Could SyncPeriod be a source of subtle bugs?

### ISSUE THREAD

**Issue by deleted** [actions-runner-controller/actions-runner-controller#244]
Hi! I'm evaluating `actions-runner-controller` for use and it seems like an awesome design that would give our devs a lot of controll over the CI environment.

One thing I'm noticing is that the autoscaling features rely on `ctrl.Options.SyncPeriod` to trigger a periodic revisit of existing resources, which in turn gets the size of run queue Github and makes decisions about whether to rescale.

There seems to be some widespread confusion over what this `SyncPeriod` options does, but I found [this issue](https://github.com/kubernetes-sigs/controller-runtime/issues/521) on the `controller-runtime` repo that caught my attention.

There, controller-runtime contributor @DirectXMan12 writes:

> The problem was that nobody actually understood what this knob did -- it doesn't relist from the API server (which is what most people thought it did). All it does is force a re-reconcile of everything in the cache. Generally, you probably don't want to do this -- it's often expensive, it'll mask subtle bugs, and it's usually not necessary. It's actually probably fine to set this to never, except it might save you in production if you've got bugs in your reconcile logic because you didn't write a level-based controller.
> 
> The only place, IMO, it's actually reasonable to use this knob, is if you're writing something that needs periodic reconcilation, like a horizontal pod autoscaler, but we'd recommend using RequeueAfter or a custom event source implementation to do this instead.

They go on to explain that the resync refreshes everything that's in the controllers `go-client` cache, but doesn't necessarily call the Kubernetes API server for a list of resources.

My concerns are:
a) If `actions-runner-controller` needs to be restarted and the `client-go` cache contents were lost, would it still be triggered to poll for autoscale-triggering conditions?

b) Could controller instances with very long uptime see subtle bugs where they stop monitoring some resources do to eventual cache eviction?

I haven't tested any of this, but I'm curious if any of the authors have thought about it, or considered the impact of switching to a `RequeueAfter` strategy or a custom event source as suggested above.

**Comment by mumoshu** [comment]
> a) If actions-runner-controller needs to be restarted and the client-go cache contents were lost, would it still be triggered to poll for autoscale-triggering conditions?

Yes

> b) Could controller instances with very long uptime see subtle bugs where they stop monitoring some resources do to eventual cache eviction?

Theoretically yes. But I've never encountered such cases before, and I think we have nothing possible to do on actiosn-runner-controller side. If there's any bug if k8s informers and cache, it should be fixed in K8s. Similarly, if controller-runtime had a bug that results in something like that, it should be fixed in controller-runtime.

> I haven't tested any of this, but I'm curious if any of the authors have thought about it, or considered the impact of switching to a RequeueAfter strategy or a custom event source as suggested above.

I use both. I use RequeueAfter to throttle reconciliation to avoid e.g. excessive GitHub API call. I still use sync-period hoping so that runners are eventually synced.
