### ISSUE TITLE
Question: is there a plan for when k8s removes dockershim?

### ISSUE THREAD

**Issue by lasse-aagren** [actions-runner-controller/actions-runner-controller#251]
I _think_ this will break the current docker:dind support?

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation

best regards,
Lasse Aagren

**Comment by mumoshu** [comment]
@lasse-aagren Hey! I have no plan to do anything and I don't think it affects dind.

Just curious, but how dockershim deprecation affects dind? Shouldn't dind work on top of any container runtime used by k8s?

**Comment by lasse-aagren** [comment]
From:

https://medium.com/better-programming/kubernetes-is-deprecating-docker-8a9f7566fbca

"Are Container Workloads Impacted?
It’d be best if you made this assessment before attempting to migrate to the new runtime. If you have a CI/CD pipeline running within Kubernetes and it uses a Docker-in-Docker (DinD) approach by mounting the /var/run/docker.sock socket file, then you’re impacted.

As you won't be running Docker in your Kubernetes cluster, you need to replace it with an appropriate solution — Kaniko is an excellent solution for this, as it doesn’t rely on a Docker daemon to build container images. You can read “How to Build Containers in a Kubernetes Cluster With Kaniko” for a more detailed view on how to approach this problem."

**Comment by mumoshu** [comment]
@lasse-aagren As we don't mount `/var/run/docker.sock` from the host so it doesn't relate to actions-runner-controller deployment, right?

**Comment by lasse-aagren** [comment]
Yeah .. Frankly I'm not sure :-)

A bit more that a month ago, with success, I tested this project in a test k8s created using:

https://kind.sigs.k8s.io/

and they now state:
```
Dockershim deprecation does NOT impact kind.  🐳

If you already use kind you've actually been testing your workloads on containerd!

While kind uses docker or podman on your host, it uses CRI / containerd "inside" the nodes and does not use dockershim.
```
will report back, if I find out otherwise.

Thanks for the reponses!

/Lasse

**Comment by lasse-aagren** [comment]
Everything kept working as you expected

/Lasse

**Comment by mumoshu** [comment]
@lasse-aagren Thanks for reporting! ☺️
