### ISSUE TITLE
How to extend actions-runner-controller? (e.g. custom CA cert)

### ISSUE THREAD

**Issue by iptizer** [actions-runner-controller/actions-runner-controller#291]
We need to build our own image for *actions-runner-controller*, as our GitHub Enterprise server has a a self signed corporate CA certificate.

The plan is to add the cert, execute the `update-ca` stuff, then use this image.

Not sure what I am missing, but building even the simplest docker image fails.

```Dockerfile
FROM summerwind/actions-runner-controller:latest
RUN echo "blub" 
```

with

```sh
❯ docker build .
Sending build context to Docker daemon  6.144kB
Step 1/2 : FROM summerwind/actions-runner-controller:latest
latest: Pulling from summerwind/actions-runner-controller
5749e56bea71: Already exists 
35a8797ae88d: Pull complete 
Digest: sha256:b628337979a2e2bf3b9a6e1b75b4bb2ccbfd943bc682bb4f93c005218dcdfcf0
Status: Downloaded newer image for summerwind/actions-runner-controller:latest
 ---> b628f2245ed0
Step 2/2 : RUN echo "blub"
 ---> Running in 0e6ff4431f71
OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

Is there a best practise on adding a custom cert?

How to extend the *actions-runner-controller* image?

**Comment by callum-tait-pbx** [comment]
Whilst I don't have the answer the manager [Dockerfile](https://github.com/summerwind/actions-runner-controller/blob/4d69e0806ebfc73b0128104dfd36ad11b2dbaff1/Dockerfile#L29) is based on https://github.com/GoogleContainerTools/distroless . It doesn't have a shell or really anything in it, only what is required to run the app so there are basically 0 OS tools at all. I don't think you will really be able to do what you want to do directly in the container. Are the webhooks failing with a validation error?

**Comment by iptizer** [comment]
Damn, I checked the wrong *Dockerfile*. With this Distroless, of course this does not work. Wondering why I never stumbled upon this before. Nevertheless.

> Are the webhooks failing with a validation error? How does cert-manager not allow you to install the right certificate?

Not really, the http requests from the controller to the *GitHub Enterprise Server* are failing. But that is legitimate, as of course the CA cannot be verified.
I don't see how cert-manager comes into play here, it's communication between controller and the GitHubServer.

> you may need to use the sidecar pattern to achieve what it is you want to achieve.

Possible, but not supported by helm chart yet + complex. As long as there are alternatives, I will check them.


=> Seems like it is possible to add custom certs in a distroless container. Will check that.

**Comment by mumoshu** [comment]
@iptizer Hey! How about using `summerwind/actions-runner-controller:latest` as just the source of executable binaries?

```
FROM summerwind/actions-runner-controller:latest as actions-runner-controller

FROM ubuntu:focal #or whatever

WORKDIR /

RUN # install certs and then run update-ca or anything you want to do

COPY --from=actions-runner-controller /manager .

USER nonroot:nonroot

ENTRYPOINT ["/manager"]
```

I think you'd also need to build your own custom image for your runners(not controller) as well. The dockerfile for runners can be found at:

https://github.com/summerwind/actions-runner-controller/tree/master/runner

**Comment by fnmarquez** [comment]
> Damn, I checked the wrong _Dockerfile_. With this Distroless, of course this does not work. Wondering why I never stumbled upon this before. Nevertheless.
> 
> > Are the webhooks failing with a validation error? How does cert-manager not allow you to install the right certificate?
> 
> Not really, the http requests from the controller to the _GitHub Enterprise Server_ are failing. But that is legitimate, as of course the CA cannot be verified.
> I don't see how cert-manager comes into play here, it's communication between controller and the GitHubServer.
> 
> > you may need to use the sidecar pattern to achieve what it is you want to achieve.
> 
> Possible, but not supported by helm chart yet + complex. As long as there are alternatives, I will check them.
> 
> => Seems like it is possible to add custom certs in a distroless container. Will check that.

Were you able to add the custom cert to distroless container?
