### ISSUE TITLE
Make `TotalNumberOfQueuedAndInProgressWorkflowRuns` scale only for workflows in the queue that target self-hosted runners

### ISSUE THREAD

**Issue by callum-tait-pbx** [actions-runner-controller/actions-runner-controller#338]
**Problem**
As it stands the `TotalNumberOfQueuedAndInProgressWorkflowRuns` metric will scale based on the workflow queue depth. It doesn't however factor in how many of the queued workflows are allocated to self-hosted runners and how many are allocated to github hosted machines. This means it can scale out too aggressively.

**Links**
I took this feature from the comments on https://github.com/summerwind/actions-runner-controller/issues/258 . I thought it was worth raising as an enhancement so it doesn't get lost.

**Comment by callum-tait-pbx** [comment]
@mumoshu this is legit issue. Please add the `enhancement` label and remove the stale label so the bot doens't kill it.

**Comment by mumoshu** [comment]
@callum-tait-pbx Hey! Thanks for triaging this. I thought this was impossible due to GitHub API doesn't provide us a way to search workflow runs by targeted self-hosted runners.

Perhaps the better way forward would be to recommend PercentageRunnersBusy more?

**Comment by callum-tait-pbx** [comment]
You're right! Just gone through the API reference docs and I don't see how we could do it.

Could you add the `enhancement` label for searchability. 

> Perhaps the better way forward would be to recommend PercentageRunnersBusy more?

I'll update the docs with the limitation of the metric

I don't know if it's worth having a label for `not currently possible` or something (although that feels very long for a label)? Again for searchability down the line.

**Comment by mumoshu** [comment]
> I don't know if it's worth having a label for not currently possible or something (although that feels very long for a label)? Again for searchability down the line.

I think having an unmbrella issue collecting feature requests and fixes to GitHub would be helpful. If we had many such issues labeled with e.g. `not currently possible`, I'm afraid our issues gets overwhelmed by many issues we can't directly resolve 🤔
