### ISSUE TITLE
Feature: Log when a runner accepts a job

### ISSUE THREAD

**Issue by erikh** [actions-runner-controller/actions-runner-controller#374]
Happy to do this patch for you; right now it's silence until the runner yields a result, making it hard to debug things during initial setup.

Thanks for the great operator!

**Comment by mumoshu** [comment]
@erikh Hey! Sounds like a great addition 👍 How would you achieve it? Is there any flag that toggles the log level of the runner agent?

**Comment by callum-tait-pbx** [comment]
@mumoshu this is legit, `enhancement` label please

**Comment by erikh** [comment]
sorry I won't have time to do this patch!

**Comment by mumoshu** [comment]
We'd better file a feature request to GitHub Actions first, not here! Let's reopen or create another issue once it becomes possible.
