### ISSUE TITLE
Add CA Cert to Docker sidecar

### ISSUE THREAD

**Issue by Carus11** [actions-runner-controller/actions-runner-controller#397]
Hello,
In my github action I am trying to run a docker login command to login to a private container registry. This registry's certificate's CA Certificate needs to be imported to the image of the docker sidecar container.

- Would the best way to go about this to be to extend docker:dind and install my own certificates?
- Is there a parameter in the RunnerDeployment I can use to overwrite the image that the docker sidecar uses?
  - In the helm chart there is dindSidecarRepositoryAndTag, however I have installed the kubectl way (kustomize managed cluster)

Thanks

**Comment by callum-tait-pbx** [comment]
see https://github.com/summerwind/actions-runner-controller/issues/393 for details but basically you want to pass in to the manager the `--docker-image` flag with your unique dind image
