### ISSUE TITLE
Automate update of actions/runner

### ISSUE THREAD

**Issue by int128** [actions-runner-controller/actions-runner-controller#416]
Currently the version of actions/runner is defined at below:

https://github.com/summerwind/actions-runner-controller/blob/bc6e499e4f72f60024781d99ec66a665bedb5e1f/.github/workflows/build-and-release-runners.yml#L32-L33

It would be nice to update the version automatically using [Renovate](https://github.com/renovatebot/renovate).

I think we can use GitHub Releases datasource from https://github.com/actions/runner/releases.

**Comment by int128** [comment]
I'm investigating Renovate config at https://github.com/int128/actions-runner-controller/blob/master/.github/renovate.json5.

**Comment by mumoshu** [comment]
@int128 Hey! Thanks for your effort. FYI, I just saw an automated pull request containing a redundant `v` in RUNNER_VERSION. Everything else seems fine https://github.com/int128/actions-runner-controller/pull/21/files

**Comment by mumoshu** [comment]
Is there any way to (re)run a renovate update manually? That way we can probably test it freely and repeatedly until we're confident, without waiting for actual new runner releases?

**Comment by toast-gear** [comment]
This would be very nice to have, from a quick search of the docs it looks like you can extra the version with something like:

```
      "extractVersion": "^v(?<version>.*)$"
```

So I _think_ the complete json would be:

```
{
  "extends": ["config:base"],
  "regexManagers": [
    // runner version in https://github.com/actions/runner/releases
    {
      "fileMatch": [".github/workflows/build-and-release-runners.yml"],
      "matchStrings": ["RUNNER_VERSION: +(?<currentValue>.*?)\\n"],
      "extractVersion": "^v(?<version>.*)$"
      "depNameTemplate": "actions/runner",
      "datasourceTemplate": "github-releases"
    }
  ]
}
```

**Comment by int128** [comment]
@toast-gear I tried `extractVersion` and finally got an update as https://github.com/int128/actions-runner-controller/pull/21. Thank you for your suggestion.

I will send a pull request for it.
