### ISSUE TITLE
loglevel option

### ISSUE THREAD

**Issue by kimxogus** [actions-runner-controller/actions-runner-controller#425]
It seems debug log is enabled and cannot be configured [here](https://github.com/summerwind/actions-runner-controller/blob/master/main.go#L92) (Not sure, I'm not familiar with golang).
Hope to have cli option to enable and disable debug option

**Comment by mumoshu** [comment]
@kimxogus Good catch! It should definitely be configurable. Probably we shall add `--log-level [error|warn|info|debug]` and exposing it via the helm chart.
