### ISSUE TITLE
Deploying controller to support multiple github organizations

### ISSUE THREAD

**Issue by tzejohn** [actions-runner-controller/actions-runner-controller#442]
Is there any guidance around deploying this controller in a single EKS cluster to support multiple different GitHub organizations? We have a couple GitHub.com hosted organizations, as well as an on-prem Github Enterprise instance. I was looking to support all of those with actions runners running in the same EKS cluster.

**Comment by callum-tait-pbx** [comment]
You probably want to explore deploying multiple controllers using the `watchNamespace` feature, it's not really documented unfortunately. See https://github.com/summerwind/actions-runner-controller/issues/377 for more details.

@mumoshu can provide more details if you get stuck

**Comment by mumoshu** [comment]
Yeah, if you also need to isolate each organization('s runners) into a dedicated namespace, `--watch-namespace` should be handy.

In the Helm chart it is configurable via:

https://github.com/summerwind/actions-runner-controller/blob/b42b8406a2b6d606ef9b531867720039e1de1b42/charts/actions-runner-controller/values.yaml#L103-L104

Also, if you're okay with sharing the GitHub token/app and the namespace across GitHub orgs, I believe just creating RunnerDeployments with various `organization` field values work.

**Comment by mumoshu** [comment]
Please let me move this to Discussions as the question is already answered, the feature that supports the use case already exists, and the documentation enhancement is tracked in another issue #455.
