### ISSUE TITLE
Could we enable the discussions tab / clean up issues?

### ISSUE THREAD

**Issue by callum-tait-pbx** [actions-runner-controller/actions-runner-controller#443]
_Note I don't have a view really on issues vs dicussion tab tbh_
@summerwind  @mumoshu 
Would it be useful to have a space to discuss stuff without having to raise an issue? Maybe not though, potentially it's better to have issues for everything? If we do want everything as issues could we do a clean up and consider a general strategy / some bots so it doesn't get into a state going forward? e.g. close stale issues, labels for everything etc

**Comment by callum-tait-pbx** [comment]
would be useful to have a space to discuss stuff without having to raise an issue

**Comment by igorbrigadir** [comment]
Yeah I agree - it's hard to keep up right now and check what's important or potentially breaking in future and what's just general usage issues.

**Comment by erikkn** [comment]
I think that's a good point. 

I was also thinking about a Slack team, what do you guys think?

**Comment by callum-tait-pbx** [comment]
@mumoshu any thoughts?

**Comment by mumoshu** [comment]
@summerwind Thanks for enabling Discussions!

I'm now closing this as resolved 🎉
