### ISSUE TITLE
Bumping the docker client in runner image

### ISSUE THREAD

**Issue by Puneeth-n** [actions-runner-controller/actions-runner-controller#451]
Any plans of bumping the runner's docker client version to something like `20.10.5`?

https://github.com/summerwind/actions-runner-controller/blob/b42b8406a2b6d606ef9b531867720039e1de1b42/runner/Dockerfile#L5

**Comment by callum-tait-pbx** [comment]
It does need doing. We can look at bumping it once the runner image itself is on ubuntu 20.04 https://github.com/summerwind/actions-runner-controller/pull/438

**Comment by callum-tait-pbx** [comment]
@mumoshu could we get the `chore` label on this, we will want to bump the docker version, probably worth targeting after the new scale from 0 features are stable.

**Comment by consideRatio** [comment]
This PR is fixed by #730 according to the PR

**Comment by toast-gear** [comment]
No issues reported since release, closing as resolved.
