### ISSUE TITLE
Document the  --watch-namespace feature

### ISSUE THREAD

**Issue by callum-tait-pbx** [actions-runner-controller/actions-runner-controller#455]
**Relevant Issues / Commits**
https://github.com/summerwind/actions-runner-controller/commit/1b8a656051c8a8a187fe1b34f20b92f169485ae6
https://github.com/summerwind/actions-runner-controller/issues/377
https://github.com/summerwind/actions-runner-controller/issues/442

**Comment by callum-tait-pbx** [comment]
@mumoshu this is legit issue. Please add the `documentation` label and remove the stale label so the bot doens't kill it.

**Comment by shichengripple001** [comment]
where is the example? the document is very hard to understand..
