### ISSUE TITLE
Support dynamic scaling for  multiple runners when Webhook server is implemened

### ISSUE THREAD

**Issue by peimanja** [actions-runner-controller/actions-runner-controller#480]
In our organization we are running quite a few runners with different resources (CPU & memory) and want to use autoscaling with webhook server implementation.

From my tests I found out controller cannot scale up if multiple `HorizontalRunnerAutoscaler` is deployed with:
```yaml
    scaleUpTriggers:
    - githubEvent:
        checkRun:
          types: ["created"]
          status: "queued"
```

From a quick look, it seems that `checkRun` github events does not have any reference to requested runner so I am not sure how this can be implemented.

right now we have 5 RunnerDeployments and growing and only can scale up and down one of them using webhook server. I think this also means only one runner will get scale up even tho that's not the one requested in the `queued` workflow.

Right now we implemented `HorizontalRunnerAutoscaler` with `metrics` and type `PercentageRunnersBusy` but as mentioned in the documentation, it is not quick and efficient.

Is there anyway to get around this?

**Comment by mumoshu** [comment]
@peimanja Hey! I thought it would just work as long as your RunnerDeployments are for different GitHub repos or orgs, as the webhook server do filter the target HRA by the GitHub repo/org of its connected RunnerDeployment.

Maybe can you clarify a bit more details of your setup like how many repos and orgs you have and which runnerdeployments are connected to which repos, etc?

**Comment by mumoshu** [comment]
@peimanja Ah well I forgot to say something important. If you had multiple runnerdeployments per repo and that's the blocker for you, have you tried using checkRun `names`? https://github.com/summerwind/actions-runner-controller/blob/aad261548756ad94c1473e6629bc9594809826f3/api/v1alpha1/horizontalrunnerautoscaler_types.go#L80

My initial intention for `names` was to limit a RunnerDeployment to be scaled only on a subset of checkRun(=Actions jobs).

But theoretically, it can also be used to let the controller determine which HRA/RunnerDeployment to scale for a specific repo/org, from multiple candidates.

**Comment by peimanja** [comment]
@mumoshu Thanks for the prompt response. So all of our runners our available to the org and not limited to specific repos.

>My initial intention for names was to limit a RunnerDeployment to be scaled only on a subset of checkRun(=Actions jobs)
Oh this might actually comes handy as we are trying to standardize our workflow templates and actions. 

So if I understand this correctly, I can add names like:
```
    scaleUpTriggers:
    - githubEvent:
        checkRun:
          names: ["*docker*", ...]
          types: ["created"]
          status: "queued"
```
and if the check-runs event has a job name that matches that, it will scale up the runners ?

**Comment by mumoshu** [comment]
> if the check-runs event has a job name that matches that, it will scale up that runner deployments ?

@peimanja Absolutely 👍

**Comment by mumoshu** [comment]
Reread https://github.com/actions-runner-controller/actions-runner-controller#faster-autoscaling-with-github-webhook but I'm not sure where to enhance. HRA.Spec.ScaleTargetRef is explained earlier in the documentation and webhook-based autoscaling works by matching webhook-payload to HRAs and RunnerDeployments by repository or organization contained in the payload.

Closing as I have nothing to enhance but please feel free to raise issues for documentation enhancements, if any!
