### ISSUE TITLE
Transfer this repository to a dedicated GitHub organization

### ISSUE THREAD

**Issue by mumoshu** [actions-runner-controller/actions-runner-controller#488]
A few months back I had talked with @summerwind and he was willing to transfer this repository to me.

I don't really mind who owns the repository but recently I got some motivation to have administrative privilege myself to do:

- Enable `stale` bot #487 cc/ @callum-tait-pbx 
- Update our workflow and publish our chart in another GitHub repository https://github.com/summerwind/actions-runner-controller/issues/402#issuecomment-821934353
- Enable discussions #443 @callum-tait-pbx @igorbrigadir @erikkn 

For the second point I'd like to have another sibling repository for publishing Helm charts, too. So, I think it's more plausible and understandable to have this repository and the new repository for charts under a clean GitHub organization, rather than having it under my crowed GitHub user account :)

I've already created https://github.com/actions-runner-controller/ so if there's no strong objection I'd like to talk with @summerwind once again for the move.

**Comment by erikkn** [comment]
Sounds good, an org will help scaling this project quite a bit. Awesome, @mumoshu !

**Comment by callum-tait-pbx** [comment]
Super pleased to hear we are making progress! I really think this project could be huge if the release, issue management and testing could be improved. I spent a long time looking at solutions for adding a self-hosted capability to GitHub Actions and this project as well as [philips-labs](https://github.com/philips-labs/terraform-aws-github-runner) were far and away the best projects out there and both have their use cases, neither project was objectively better than the other.

> For the second point I'd like to have another sibling repository for publishing Helm charts, too. So, I think it's more plausible and understandable to have this repository and the new repository for charts under a clean GitHub organization, rather than having it under my crowed GitHub user account :)

I definitely think this needs thought through if you do want to go down that route, whilst better than the current setup I still don't love it tbh but there can be a thread once discussions is enabled :D

> I've already created https://github.com/actions-runner-controller/ so if there's no strong objection I'd like to talk with @summerwind once again for the move.

Great idea, just a thought, the org might be worth being named slightly more generically e.g. `actions-runner`, maybe down the road someone makes a runner chart or something and we end up with a second repository called `actions-runner-runners` 🤷‍♂️  probably bikeshedding though :D

**Comment by summerwind** [comment]
Fully agree to transfer this repository to org. I will transfer the repository as soon as I can.

Thanks to all users who have used it so far, and to the contributors who have made various improvements. Especially a big thanks to @mumoshu for his continuous development!

**Comment by summerwind** [comment]
The repository transfer is complete. actions-runner-controller org is the new home!

**Comment by mumoshu** [comment]
@erikkn @callum-tait-pbx Thanks for our comments and thanks for taking your time @summerwind!

I'm already a happy user of Discussions and Stale app 😄
