### ISSUE TITLE
Helm repo doesn't work: 404 error

### ISSUE THREAD

**Issue by ozlotusflare** [actions-runner-controller/actions-runner-controller#489]
Hi everyone,
In some case the helm repo `https://summerwind.github.io/actions-runner-controller` stopped working.
```console
helm repo update

Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "actions-runner-controller" chart repository (https://summerwind.github.io/actions-runner-controller):
	failed to fetch https://summerwind.github.io/actions-runner-controller/index.yaml : 404 Not Found
...
```
Expected:

```console
helm repo update

Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from "actions-runner-controller" chart repository
```

Thanks!

**Comment by bjw-s** [comment]
Adding a +1 here, getting the same 404 error

**Comment by peimanja** [comment]
same here

**Comment by kupachupa** [comment]
Ditto!

**Comment by summerwind** [comment]
Oops, this is due to the repository transfer. Please try the following URL.
https://actions-runner-controller.github.io/actions-runner-controller/index.yaml

**Comment by bjw-s** [comment]
That works well for me, thanks for the quick response!

**Comment by ozlotusflare** [comment]
> Oops, this is due to the repository transfer. Please try the following URL.
> https://actions-runner-controller.github.io/actions-runner-controller/index.yaml

Thanks, works
P.s. Please don't forget change it in `README.md`
