### ISSUE TITLE
How to change updateStrategy

### ISSUE THREAD

**Issue by zezaeoh** [actions-runner-controller/actions-runner-controller#494]
Hi there,

i wonder how can i change update strategy of runner deployment resource.
i would like to change update strategy to "recreate" to use persistent volume.

is there any good way to use persistent volume?

**Comment by mumoshu** [comment]
@zezaeoh Hey! Unfortunately no. I believe we need a concept like `volumeClaimTemplates` in the first place to use PV in any meaningful way. Otherwise, your max runner replica is limited to only 1, which doesn't seem practical to me.

**Comment by mumoshu** [comment]
BTW, it would be nicer to use Discussions for questions!

Issues are for bug reports and feature requests.
