### ISSUE TITLE
Ability to remove PVs

### ISSUE THREAD

**Issue by marcinkubica** [actions-runner-controller/actions-runner-controller#5]
### What would you like added?
Ability to remove persistent volumes. 
A feature to set to delete unbounded PVs after ie. x-amount of minutes.

### Why is this needed?

Currently, there seems to be no way to delete PVs at all (even if having reclaim policy delete) meaning on systems like GKE we will end up with PVs running without use overnight or over the weekends.

Cheers

**Comment by Link-** [comment]
@marcinkubica this project has been migrated to: https://github.com/actions/actions-runner-controller
            
This is a **mirror repository**. Issues and Pull Requests opened in this repository will not be addressed.

Please open this issue in the [new repository](https://github.com/actions/actions-runner-controller/issues) instead.
