### ISSUE TITLE
Feature Request: Enable liveness probes for the runner container

### ISSUE THREAD

**Issue by jwalters-gpsw** [actions-runner-controller/actions-runner-controller#517]
Still experiencing the issue described in https://github.com/actions-runner-controller/actions-runner-controller/issues/458

Perhaps the new chart will fix the issue. But if not would like to be able to use a liveness probe to detect the lack of a /runner/.credentials file to restart the container. Might be more generally useful if different issues arise.

**Comment by mumoshu** [comment]
@jwalters-gpsw Hey! The idea sounds good. But I still doubl it's a necessity- actions-runner-controller greater than v0.18.0 detects `offline` runners and automatically recreates those. We don't need a liveness probe just to achieve the same goal, right?

**Comment by jwalters-gpsw** [comment]
Seems to be working. Thanks
