### ISSUE TITLE
Broken hyperlink for creating GH app in organization

### ISSUE THREAD

**Issue by sbuvaneshkumar** [actions-runner-controller/actions-runner-controller#530]
> If you want to create a GitHub App for your organization, replace the :org part of the following URL with your organization name before opening it. Then enter any unique name in the "GitHub App name" field, and hit the "Create GitHub App" button at the bottom of the page to create a GitHub App.
> 
>     Create GitHub Apps on your organization
The link to  [Create GitHub Apps on your organization](https://github.com/organizations/:org/settings/apps/new?url=http://github.com/actions-runner-controller/actions-runner-controller&webhook_active=false&public=false&administration=write&organization_self_hosted_runners=write&actions=read) seems to be broken, I am getting 404 error.

**Comment by callum-tait-pbx** [comment]
Did you do as the docs said and `replace the :org part of the following URL with your organization`?

**Comment by sbuvaneshkumar** [comment]
My bad, I didn't check that. Thanks for pointing it out.
