### ISSUE TITLE
Can we install this without cert-manager

### ISSUE THREAD

**Issue by rverma-nsl** [actions-runner-controller/actions-runner-controller#531]
We already have our self-signed certificates or ou certifications. Is it possible to use them instead of cert manager?

**Comment by mumoshu** [comment]
@rverma-nsl Maybe. As long as you can create your own certificate that can be a replacement for https://github.com/actions-runner-controller/actions-runner-controller/blob/05fb8569b33555e2ecede2c59095405e22dc3005/charts/actions-runner-controller/templates/certificate.yaml#L12-L24, it should work.
