### ISSUE TITLE
acceptance helm test failure

### ISSUE THREAD

**Issue by ToMe25** [actions-runner-controller/actions-runner-controller#533]
Since a few commits back, i don't know exactly how many, the acceptance helm tests fail.
I tried this with a fresh clone of the master branch, but it fails with the same error.
I do not know what exactly fails, but this seems to be the only hint the log gives:
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "mutate.runnerdeployment.actions.summerwind.dev": Post "https://actions-runner-controller-webhook.actions-runner-system.svc:443/mutate-actions-summerwind-dev-v1alpha1-runnerdeployment?timeout=30s": dial tcp 10.96.135.248:443: connect: connection refused
```
Here is a full `make acceptance` log: https://pastebin.com/TnikkGh7
I do not know for sure whether this is because of a timeout set too low, but most of them caused inconsistencies where it sometimes works and sometimes doesn't, while this always fails.

**Comment by mumoshu** [comment]
@ToMe25 I think this is because of too low timeout. I think it depends on your internet connection speed and your machine resource, but giving it a safer value, like 60s, would make sense!

**Comment by ToMe25** [comment]
@mumoshu There seem to only be two relevant instances of `30`, one in runner_controller.go and one in startup.sh, i tried replacing both of them(in separate runs) to 60, but nether changed the timeout parameter there, and neither fixed the crash.

**Comment by mumoshu** [comment]
@ToMe25 Ah sorry I was talking about the different beast! You should tweak the `sleep` seconds instead https://github.com/actions-runner-controller/actions-runner-controller/blob/master/acceptance/deploy.sh#L43-L44

**Comment by ToMe25** [comment]
I don't think this actually is a timeout.
After increasing both the sleep from 20 to 60 seconds, and the kubectl timeout before it from 60 to 120 seconds the same still happens.
I now looked at the log for the manager container, and this is its log:
```
invalid value "" for flag -sync-period: parse error
Usage of /manager:
  -common-runner-labels value
    	Runner labels in the K1=V1,K2=V2,... format that are inherited all the runners created by the controller. See https://github.com/summerwind/actions-runner-controller/issues/321 for more information
  -docker-image string
    	The image name of docker sidecar container. (default "docker:dind")
  -enable-leader-election
    	Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
  -github-app-id int
    	The application ID of GitHub App.
  -github-app-installation-id int
    	The installation ID of GitHub App.
  -github-app-private-key string
    	The path of a private key file to authenticate as a GitHub App (default "/etc/actions-runner-controller/github_app_private_key")
  -github-token string
    	The personal access token of GitHub. (default "1f841d34b8b580e9e9b0d5ec3cfb3bddf7bd9f4b")
  -kubeconfig string
    	Paths to a kubeconfig. Only required if out-of-cluster.
  -master --kubeconfig
    	(Deprecated: switch to --kubeconfig) The address of the Kubernetes API server. Overrides any value in kubeconfig. Only required if out-of-cluster.
  -metrics-addr string
    	The address the metric endpoint binds to. (default ":8080")
  -runner-image string
    	The image name of self-hosted runner container. (default "summerwind/actions-runner:latest")
  -sync-period duration
    	Determines the minimum frequency at which K8s resources managed by this controller are reconciled. When you use autoscaling, set to a lower value like 10 minute, because this corresponds to the minimum time to react on demand change (default 10m0s)
  -watch-namespace string
    	The namespace to watch for custom resources. Set to empty for letting it watch for all namespaces.
```
I'm pretty sure this is because the sync period wasn't set, however I'm not yet sure what to do about that.
There is probably some variable that has no default value somewhere, and i will be looking for that.

**Comment by ToMe25** [comment]
@mumoshu The issue seems to be that the deploy script doesn't have access to SYNC_PERIOD.
I don't know if this is caused by the version of make i am using, or if this is always the case, but adding `SYNC_PERIOD=${SYNC_PERIOD}` to the line that executes the deploy script fixes this.

**Comment by mumoshu** [comment]
@ToMe25 Ah, good catch. It does seem like a bug I've introduced. Yes, adding `SYNC_PERIOD=${SYNC_PERIOD}` to https://github.com/actions-runner-controller/actions-runner-controller/blob/master/Makefile makes sense
