### ISSUE TITLE
Document permissions required for GitHub App

### ISSUE THREAD

**Issue by Nuru** [actions-runner-controller/actions-runner-controller#543]
The README helpfully [documents exactly what scopes a PAT needs](https://github.com/actions-runner-controller/actions-runner-controller/tree/v0.18.2#deploying-using-pat-authentication) for it to work with `actions-runner-controller`. Unfortunately, there is no such documentation for using a GitHub App, and there are a lot to choose from:

<details><summary>Screenshots of GitHub App Permissions Settings</summary>

(A couple of lines appear twice because I could not get this all to fit on one screen, so this is multiple screen shots)

![image](https://user-images.githubusercontent.com/2793313/118020172-a4c1a400-b30e-11eb-954b-e836ac30a1e3.png)
![image](https://user-images.githubusercontent.com/2793313/118020227-b4d98380-b30e-11eb-8568-3d86f489ea36.png)
![image](https://user-images.githubusercontent.com/2793313/118020294-c589f980-b30e-11eb-8fe9-ffabc75bf20e.png)

</details>

Please document the required permissions for a GitHub App for the `actions-runner-controller` and for the owner of the account it is installed in (e.g. does the account owner need to be an Organization Owner?)

**Comment by toast-gear** [comment]
We could probably document out explicitly the scopes however they are just a hyperlink away. The:

`Create GitHub Apps on your account` and `Create GitHub Apps on your organization` links contain the permissions required in the query string. Perhaps we could make that more clear?

**Comment by Nuru** [comment]
@toast-gear 

We need to know both the permissions the App needs and the permissions that the User installing the App needs.


The hyperlink for `Create GitHub Apps on your account` is `https://github.com/settings/apps/new?url=http://github.com/actions-runner-controller/actions-runner-controller&webhook_active=false&public=false&administration=write&actions=read` and thereby sets 4 options:
- "Webhook Active" checkbox set to unchecked
- "Where can this GitHub App be installed?" set to "Only on this account"
- Repository Permissions -> Administration set to "Read & Write"
- Repository Actions -> Actions set to "Read"

This means that in order to work, the app needs to be installed on a user that Repository Admin permissions. So it is not enough to just have the link. It is also not at all clear that the link sets the necessary permissions, or that these are the only permissions needed.

The organization runners link adds `organization_self_hosted_runners=write`. It is not clear to me what permissions the app user needs to have for this, but my guess is that the user needs to be an Organization Owner.


Also, organizations want to evaluate the differences between using a GitHub App and a PAT. For this, it is helpful to compare the App required permissions to the PAT required scopes to see if one is better than the other from a security and/or management standpoint.

**Comment by mumoshu** [comment]
@Nuru Hey! Thanks for bringing this up.

> for the owner of the account it is installed in (e.g. does the account owner need to be an Organization Owner?)

Well, I can't say for sure. I "think" the organization's `Settings` page that shows some link to let me add a GitHub is shown only when you have admin/owner permissions on the organization. I see it's working like that. But how can I verify that? I'm not a GitHub folk.

What do you see? Are you only able to create a GitHub App when you are an admin/owner?

**Comment by mumoshu** [comment]
> Also, organizations want to evaluate the differences between using a GitHub App and a PAT. For this, it is helpful to compare the App required permissions to the PAT required scopes to see if one is better than the other from a security and/or management standpoint.

@Nuru What do you want us to do for this, exactly?

We already have a list of required permissions for the PAT case, and we have respective links to github app creation for per-user and per-organization scenarios.

Given that, shouldn't it be users' responsibility to know how GitHub security works(like which permission allows exactly what?)

In other words, I don't know how "exactly" permissions for PAT, per-user GitHub App, and per-organization correspond to those of each other.

We have some "experience" to believe that the suggested permissions are sufficient and necessary for respective deployment scenarios, but nothing more. That said, I think we aren't sure which one is better.

If anyone could help to summarize and compare those deployments options in terms of security, I'd gladly add it to our documentation.

Does that sound good to you?

**Comment by ayk33** [comment]
Can you expand the documentation to show why administrator access is required? Will anything less then admin get the job done? Was admin selected because it just made things simpler or is there a subset of permissions for both options (github app / PAT) that we can assign to let the runners work without admin? 

I'm not to comfortable making an app/pat with administrator access into my org.

**Comment by mumoshu** [comment]
@ayk33 You're taking about organizational runners, right?

Then perhaps `admin` permissions can be replaced by something like `actions` permissions today, as all we need should be some read only access to `repos` and `workflows` for use in our autoscaling logic and various self-hosted `actions` runners read/write access for managing runners.

I thought we didn't had `actions` permissions for e.g. organization when we first wrote that part of the documentation?

**Comment by ayk33** [comment]
Thanks for breaking it down. I'll take a look at testing with just these permissions.

**Comment by Nuru** [comment]
@mumoshu 
> We already have a list of required permissions for the PAT case, and we have respective links to github app creation for per-user and per-organization scenarios with required permissions already checked.

For starters, it would be helpful to list the GitHub App "permissions already checked" so that list can easily be compared to the "list of required permissions for the PAT case". I had no idea (before opening this issue) that the GitHub App links already had the required (and only the required) permissions checked; I thought I still had to figure that out. 

I don't know how hard it is, but an interim next step would be to list all the GitHub API calls the modules make so people can see what permissions are needed and why.

**Comment by mumoshu** [comment]
Turns out `administration` permissions are required only when you use repository runners, as the controller use these two endpoints for creating/removing runner registration tokens for repository runners

```
POST /repos/:owner/:repo/actions/runners/registration-token (:write)

POST /repos/:owner/:repo/actions/runners/remove-token (:write)
```

https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-administration

So my recommendation would be to avoid using repository runners and instead use organizational runners when you need to uncheck `administration` permissions.

**Comment by ayk33** [comment]
> It turns out that `administration` permissions are required only when you use repository runners, as the controller use these two endpoints for creating/removing runner registration tokens for repository runners
> 
> ```
> POST /repos/:owner/:repo/actions/runners/registration-token (:write)
> 
> POST /repos/:owner/:repo/actions/runners/remove-token (:write)
> ```
> 
> https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-administration
> 
> So my recommendation would be to avoid using repository runners and instead use organizational runners when you need to uncheck `administration` permissions.

Great, thanks for digging into this for me.
