### ISSUE TITLE
Mismatch between CRDs and appVersion in the actions-runner-controller-0.11.0 helm chart

### ISSUE THREAD

**Issue by Puneeth-n** [actions-runner-controller/actions-runner-controller#545]
I was going through the CRDs and appVersion in the helm chart `actions-runner-controller-0.11.0`.

I see that the CRDs has the `dockerVolumeMounts` attribute but the appVersion `0.18.2` doesn't support this feature yet. Will it cause any issue if i install this version of Helm chart?

**Comment by mumoshu** [comment]
@Puneeth-n Probably no. Any redundant fields should be ignored by the controller that doesn't support it. I.e. as long as the CRD is backward-compatible, that should be okay.
