### ISSUE TITLE
Readme runner.yaml -> runnerdeployment.yaml

### ISSUE THREAD

**Issue by puggan** [actions-runner-controller/actions-runner-controller#546]
At this line:
https://github.com/actions-runner-controller/actions-runner-controller/blame/master/README.md#L272

```bash
kubectl apply -f runner.yaml
```

proberly should be:
```bash
kubectl apply -f runnerdeployment.yaml
```

**Comment by mumoshu** [comment]
@puggan This has been fixed by @toast-gear now. Thanks for reporting!
