### ISSUE TITLE
How to get docker:dind container to log into Docker Hub?

### ISSUE THREAD

**Issue by funkypenguin** [actions-runner-controller/actions-runner-controller#557]
We have actions which required building of images from Dockerfiles, and these Dockerfiles pull images from Docker Hub (i.e., `FROM alpine`. When we process a lot of actions, we've found that the Docker build fails because we've hit the Docker Hub rate-limits. These rate-limits are relaxed somewhat if you log into a Docker Hub account before attempting the build.

**Describe the solution you'd like**

Make it possible to log into Docker Hub using PullSecret-style credentials.

**Describe alternatives you've considered**

An alternative is to avoid using GitHub Actions which require the building of Dockerfiles, or avoid dependence on Docker Hub images for these builds.

**Comment by toast-gear** [comment]
This isn't something this project can solve. You can solve this in various ways but it's up to you as an end user to fix it, you can:

1. Use an alternative registry e.g. ECR
2. Authenticate within your workflow by either using an action like https://github.com/docker/login-action or if you are pulling the container as part of your workflow env using the [container](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer) then you need to use the auth features of that key

**Comment by mumoshu** [comment]
Or include a docker config or credentials helper in your custom runner image, if you need to pull images before running `login-action` or you need to avoid using login-action?

https://github.com/actions-runner-controller/actions-runner-controller/issues/474#issuecomment-825273057

**Comment by toast-gear** [comment]
Yup but I'm not aware of a credentials helper for DockerHub, only the 1 for ECR https://github.com/awslabs/amazon-ecr-credential-helper

**Comment by mumoshu** [comment]
Me too.

Can we label this as `question`, so that we can communicate clearly that this seems not like something this project does for you?

I think 99% of the cases `login-action` works. Theoretically, you only need the credentials helper or dockerd config thing only when you need to grab a `login-action` like action/container from a private container registry. But I have never heard about such special use-case.

**Comment by zetaab** [comment]
mirror feature were added in https://github.com/actions-runner-controller/actions-runner-controller/pull/478 which could also solve this issue. We are using mirror currently and it works pretty well.
