### ISSUE TITLE
Cannot run privileged workloads on containers without invoking sudo

### ISSUE THREAD

**Issue by ciriarte** [actions-runner-controller/actions-runner-controller#578]
**Describe the bug**

Cannot run privileged programs on containers without invoking sudo e.g. running `iptables -L`

**Checks**

N/A

**To Reproduce**

Running a workflow of the form:

```
  on-self-hosted:
    runs-on: [self-hosted]
    container:
      image: myimage
      options: '--privileged'

    steps:
      - name: Run a one-line script
        run: |
          if ! iptables -L >/dev/null 2>&1; then
            echo "is not running as root/with privileges."
            exit 1
          fi
```

Fails.

Even if I `sudo -i` and become root I still have trouble running privileged containers. I always have to sudo my docker calls.

**Expected behavior**

I was expecting to run sshuttle in the container, but it needs NET_ADMIN. I would expect options to be honor flags like `--privileged` like the native implementation.

If I run the exact same stanza:

```
  on-gh-runners:
    runs-on: ubuntu-latest
    container:
      image: myimage
      options: '--privileged'

    steps:
      - name: Run a one-line script
        run: |
          if ! iptables -L >/dev/null 2>&1; then
            echo "is not running as root/with privileges."
            exit 1
          fi
```

**Screenshots**

<img width="554" alt="Screen Shot 2021-05-26 at 10 10 23 PM" src="https://user-images.githubusercontent.com/5928/119769362-2ff27c00-be6f-11eb-8520-5efaa8f3399c.png">

**Environment (please complete the following information):**

 - Controller Version 0.18.2
 - Deployment Method **kustomize**
 - Helm Chart Version **0.11.0**
 
**Additional context**

Happy to assist if you need more information or help debugging.

**Comment by mumoshu** [comment]
@ciriarte Hey! How's your runner deployment and the runner spec look like?

**Comment by mumoshu** [comment]
@ciriarte Could you confirm your correct controller version number? `0.11.0` looks like a chart version. If you're really using controller 0.11.0, please upgrade to a more recent version.

**Comment by mumoshu** [comment]
@ciriarte Ah so are you basically saying that you need a way to add `NET_ADMIN` capability to the runner container, right?

**Comment by mumoshu** [comment]
If so, fyi, you might need to tweak the `newPod` function which generates the pod and containers spec:

https://github.com/actions-runner-controller/actions-runner-controller/blob/d2b0920454bc317c91b442b52776549d608e1bca/controllers/runner_controller.go#L565

**Comment by mumoshu** [comment]
@ciriarte Still not sure why you didn't need it for the managed runners, but shouldn't you need `--cap-add=NET_ADMIN` instead?

https://stackoverflow.com/questions/41706983/installing-iptables-in-docker-container-based-on-alpinelinux

**Comment by ciriarte** [comment]
@mumoshu thank you so much. Sorry for disappearing. I got sick and I was away from the keyboard.

> @ciriarte Ah so are you basically saying that you need a way to add NET_ADMIN capability to the runner container, right?

Yeah, I need `CAP_NET_ADMIN` so I can use `sshuttle`. This is usually possible in regular GitHub runners by using the `options` key under the `container` config.

I got it to work for my use case, these are the steps I had to follow:

1. There's a section in the dockerfile where the we generate the `/etc/sudoers` file. I think it removes the ability of root to sudo itself (which we use during several steps while building the image):

    https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Dockerfile.dindrunner#L47

1. Set the following env var: `RUNNER_ALLOW_RUNASROOT`.

I'm happy to submit a pull request with my changes if you're interested. Let me know! Thank you so much for this amazing project. I've learned a lot.

**Comment by ciriarte** [comment]
> @ciriarte Could you share the correct controller version number? `0.11.0` looks like a chart version. If you're really using controller 0.11.0, please upgrade to a more recent version.

Ouch. I got confused. I'm using 0.18.2 thanks for catching that up.
