### ISSUE TITLE
actions-runner-dind startup dockerd service errors

### ISSUE THREAD

**Issue by songyanping** [actions-runner-controller/actions-runner-controller#579]
**Describe the bug**
summerwind/actions-runner-dind:v2.278.0-ubuntu-20.04 startup dockerd service errors,
This parameter seems to be missing --privileged

**Environment (please complete the following information):**
image version: summerwind/actions-runner-dind:v2.278.0-ubuntu-20.04

**Additional context**

dockerd.out.log:

error msg="failed to mount overlay: operation not permitted" storage-driver=overlay2
time="2021-05-27T10:46:57.272539782Z" level=error msg="AUFS was not found in /proc/filesystems" storage-driver=aufs
time="2021-05-27T10:46:57.273277727Z" level=error msg="failed to mount overlay: operation not permitted" storage-driver=overlay
time="2021-05-27T10:46:57.273305829Z" level=error msg="Failed to built-in GetDriver graph devicemapper /var/lib/docker"
time="2021-05-27T10:46:57.280931691Z" level=info msg="Loading containers: start."
time="2021-05-27T10:46:57.282046259Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: , error: fork/exec /usr/local/bin/modprobe: exec format error"
time="2021-05-27T10:46:57.284115385Z" level=warning msg="Running iptables --wait -t nat -L -n failed with message: `iptables v1.8.4 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)\nPerhaps iptables or your kernel needs to be upgraded.`, error: exit status 3"

**Comment by mumoshu** [comment]
@songyanping Hey! Sry but you say what component is missing `--privileged`? To be extra sure, your runner+dockerd container should have `privileged: true` and use supervisors and [this config](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/supervisor/dockerd.conf) to run dockerd with root. So this shouldn't happen if you configured everything correctly.

Could you share your runner spec? Are you sure you did set `dindWithinRunnerContainer: true`? That's required to use actions-runner-dind images.

**Comment by mumoshu** [comment]
@songyanping I haven't seen this issue before and does it have something to do with `NET_ADMIN`, which we are missing in the runner/dind containers' capabilities? For more contenxt see https://github.com/actions-runner-controller/actions-runner-controller/issues/578#issuecomment-850032678. Hope that helps.

**Comment by songyanping** [comment]
hi,
I did not use the deploy.yaml you provided, I think it is complicated.
I used the custom deploy.yaml
Please help to have a look.

the sample:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: qa-paas-sre
  labels:
    name: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      name: github-runner
  template: 
   metadata:
     labels:
       name: github-runner
   spec:
     containers:
     - name: github-runner
       image: summerwind/actions-runner-dind:latest
       imagePullPolicy: IfNotPresent
       env:
       - name: RUNNER_ORG
         value: test-org
       - name: GITHUB_URL
         value: https://xxxxxxx.com/
       - name: RUNNER_TOKEN
         value: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
       - name: RUNNER_LABELS
         value: k8s
       - name: RUNNER_WORKDIR
         value: _work
       - name: RUNNER_NAME
         value: runner-k8s
       volumeMounts:
       - mountPath: "/runner"
         name: runner
     volumes:
     - name: runner
       emptyDir: {}
