### ISSUE TITLE
[Helm Chart] Labels for pods

### ISSUE THREAD

**Issue by cdobinsky** [actions-runner-controller/actions-runner-controller#581]
**Is your feature request related to a problem? Please describe.**
Currently you can only set labels for the deployment but not for the pods. Since we use the labels to get the logs, we would like to add pod labels as well.

**Describe the solution you'd like**
Having a value for example podLabels where you can set labels for the pods.

**Comment by mumoshu** [comment]
@cdobinsky hey! just set runnerdeployment.spec.template.metadata.labels and that should be inherited down to runnerreplicasets, runners, and pods.

**Comment by cdobinsky** [comment]
Yes, but I use the helm chart and there is no value which sets something at runnerdeployment.spec.template.metadata.labels.

**Comment by mumoshu** [comment]
@cdobinsky Ah gotcha! Thanks for confirming. Would you mind contributing something like `podLabels`, so that it is consistent with `podAnnotations`?

**Comment by cdobinsky** [comment]
Sure, I opened a pr. I wasn't sure about the Chart Version, I hope thats fine.
