### ISSUE TITLE
Investigate using Bazel to deploy CRDs when using Helm

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#594]
**Problem**
Currently due to how CRDs are handled by Helm users can get themselves into situations like https://github.com/actions-runner-controller/actions-runner-controller/issues/512 if they are not careful about keeping the CRD versions on their cluster aligned with the controller app version.

**Solution**
CRDs are included in the deploy order of the `templates/` folder in Helm https://github.com/helm/helm/blob/release-3.6/pkg/releaseutil/kind_sorter.go#L31.

If we package the CRDs in the `templates/` folder Helm will be happy to perform all CRUD operations on them removing the need for special upgrade instructions and people getting themselves into the infinite runner loop issue.

**Comment by mumoshu** [comment]
FYI, this is what we're doing today: https://github.com/actions-runner-controller/actions-runner-controller/blob/cb60c1ec3baed8690d4546dacfdfdc564891e852/Makefile#L88-L89

Can we just change the cp destination to `charts/actions-runner-controller/templates` to achieve the goal? 😃

**Comment by toast-gear** [comment]
🤷  😄  it's worth testing, I'll try to make time to test in minikube

**Comment by mumoshu** [comment]
> I guess the problem with that is we can't deploy them conditionally? Some people prefer to wrap their CRDs into their own charts and so we should probably support that as it's a common setup. Would a simple boolean in the values.yaml do the job? I guess it would

Ah, that's good point! I somehow forgot about that... So we definitely need some way to "wrap" what we've copied with the `cp` command into a helm chart template that contains a biiig `if-end` block to allow that.

**Comment by toast-gear** [comment]
yeh, I wonder if that alone would be enough! I think it would!

**Comment by callum-tait-pbx** [comment]
https://github.com/helm/community/blob/main/hips/hip-0011.md this is the authority on CRDs and Helm, I need to read it and process

**Comment by toast-gear** [comment]
There isn't really a good way of handling this, we are updating the recommended upgrade process as that is the best we can do really. If we did get Helm to do the install and uninstall the CRDs they would:

A) Delete everyone's runners during an upgrade which the end user may not expect unless they have a reasonable level of understanding of CRDs
B) The upgrade process could take a long time as the delete request will wait until all runners are not busy before it will complete
