### ISSUE TITLE
Version numbers are decrementing

### ISSUE THREAD

**Issue by mabushey** [actions-runner-controller/actions-runner-controller#611]
Usually version number INCREMENT. On March 31st v0.18.2 was released. On Apr 17 v0.11.0 was released.

**Comment by mumoshu** [comment]
@mabushey Hey! Anything prefixed with `actions-runner-controller-` are chart releases. Others like `v0.18.2` is the controller release.

**Comment by mumoshu** [comment]
We'll be moving chart releases to https://github.com/actions-runner-controller/charts so hopefully, this will be a non-issue soon.

**Comment by mumoshu** [comment]
cc/ @callum-tait-pbx

**Comment by mabushey** [comment]
@mumoshu Is there any documentation as to the differences? I didn't see any.

**Comment by toast-gear** [comment]
Differences with regards to?

**Comment by mabushey** [comment]
Differences in installation, configuration, usage. Can I just swap the manifest .18 version with the operator?

**Comment by toast-gear** [comment]
They're not interchangeable as such, they just 2 releases for the 2 deployment methods:

- The raw yaml built using kustomize
- The helm chart build

We in general will release both at the same time however that may not always be the case, additionally, the Helm release may have more releases as there may be a release that only impacts the helm chart.

It wouldn't be a case of choosing the "best" release, either you're a Helm shop and so would want the Helm release or you are a Kustomize shop and will want the raw yaml or will produce a build yourself from the repository. It really just depends what deployment tool you use in your organisation.

**Comment by mabushey** [comment]
That's an easy question. I despise helm like an ex who keyed my car, and just the word kustomize brings me happiness. I thought one of the actions runner was an operator...  
I currently have:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner-system
resources:
- https://github.com/summerwind/actions-runner-controller/releases/download/v0.18.2/actions-runner-controller.yaml
...
```

**Comment by mabushey** [comment]
@toast-gear @mumoshu 

OK, I'm way more confused than ever. There is the "older" version for helm or kustomize, and now there is an operator. Typically Operators are more resilient and reliable. Is there a comparison chart between the differences between the help/kustomize deployment and the operator?

**Comment by mumoshu** [comment]
> Can I just swap the manifest .18 version with the operator?

>  There is the "older" version for helm or kustomize, and now there is an operator.

Sry but I don't understand what you mean.

Any actions-runner-controller chart release roughly equivalent to kustomization/maniefsts released at the similar timing. There's no "operator" that installs actions-runner-controller for you. You install actions-runner-controller onto your cluster kustomize or helm. actions-runner-controller is just a k8s controller-manager that is composed of runner/runnerreplicaset/runnerdeployment/etc controllers.

**Comment by mabushey** [comment]
@mumoshu Sorry, just really confused. You said `Others like v0.18.2 is the controller release.` , I misread that as operator. I'm using `actions-runner-controller-xxx` for Kustomize, so I do not believe the "controller" releases have any use, at least for someone like me using Kustomize. It's just really bizarre to basically fork your releases and not document anything. Is this a social experiment like what UMN did for the Linux kernel?

**Comment by shadiramadan** [comment]
I think the confusion stemmed from:
> @mabushey Hey! Anything prefixed with actions-runner-controller- are chart releases. Others like v0.18.2 is the controller release.

> Others like v0.18.2 is the *controller* release.

*kustomize* instead of controller would have been less confusing!  Even I misunderstood.

**Comment by toast-gear** [comment]
There are 2 distinct releases within the 1 repository:

- The Kustomize build which is the release which defines the release of a new version of the actual controller app this whole thing is deploying. These have a tag structure of `vX.X.X`
- The Helm release which is typically released at the same time as the Kustomize build as well as any releases that are Helm specific i.e. chart changes. These have a tag structure of `actions-runner-controller-X.X.X`

There is no operator

**Comment by mumoshu** [comment]
> I'm using actions-runner-controller-xxx for Kustomize, so I do not believe the "controller" releases have any use, at least for someone like me using Kustomize. It's just really bizarre to basically fork your releases and not document anything. Is this a social experiment like what UMN did for the Linux kernel?

@mabushey Sorry, but this didn't make sense to me. If you want to use kustomize, just git-clone tags like `v0.19.0` and use the kusomize config files stored under the `config` directory. Or you can grab the source archive from releases named like `v0.19.0` that contains the `config` directory, as well.

![CleanShot 2021-06-16 at 08 38 12@2x](https://user-images.githubusercontent.com/22009/122136810-3c6e6100-ce7e-11eb-98c0-c8c7098a4311.png)

Chart releases are for charts. Not for manifests and kustomize configs.

We also have this documentation https://github.com/actions-runner-controller/actions-runner-controller#installation that instructs you to use controller releases like `v0.19.0` to grab manifests for `kubectl apply`. We just don't document one for `kustomize`, as it seemed obvious to kustomize users, as many projects I have encountered in other places used similar patterns.

> Is this a social experiment like what UMN did for the Linux kernel?

I don't think this is a nice move. We are sacrificing our own spare time for everyone. A question like `how can I deploy actions-runner-controller onto my cluster using Kustomize`, or a constructive feedback like `Shall we document how to use kustomize to deploy arbitrary version of actions-runner-controller, perhaps under https://github.com/actions-runner-controller/actions-runner-controller#installation` makes sense to me. But calling someone's voluntary work a social experiment- why and for what you do that?

**Comment by mumoshu** [comment]
> > Others like v0.18.2 is the controller release.
>
> kustomize instead of controller would have been less confusing! Even I misunderstood.

@shadiramadan Thanks fo the feedback! Well, I thought it isn't very common that there are GitHub releases dedicated for kustomize configs.

What do you think if we take the below two actions? Would it be less confusing for you?

1. Add short instructions for kustomize/kubectl/helm deployments in the beginning of the release note of every controller release like `v0.19.0`
2 Use a separate GitHub repository for chart releases

**Comment by mabushey** [comment]
@mumoshu
> But calling someone's voluntary work a social experiment- why and for what you do that?

Just an absolute misunderstanding / confusion of something that seemed to make absolutely no sense. I apologize for making you feel like this. Thank you for your work on this project, :)
