### ISSUE TITLE
Add support for volumeClaimTemplates

### ISSUE THREAD

**Issue by mumoshu** [actions-runner-controller/actions-runner-controller#612]
Like Kubernetes StatefulSet, investigate adding support for volumeClaimTemplates to e.g. Runner spec, so that you can use two or more pods per node while leveraging docker layer caching and other custom caching using Kubernetes persistent volumes.

Theoretically, any functionality that can dynamically resize pool of PVCs and PVs and attach PVs to each runner pod should work. It's basically what volumeClaimTemplates does and I thought it's better to start modeling it after that.

**Comment by inahga** [comment]
I had thought generic ephemeral volumes would fulfill this need https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes. Unfortunately it's alpha in Kubernetes 1.20, and beta in 1.21.

**Comment by mumoshu** [comment]
@inahga Hey! Thanks for the info. But I'm not sure how ephemeral volumes help. If it is `ReadWriteOnce`, any data doesn't persist between pod recreations, right? That defeats our goal of caching data. If it is `ReadWriteMany`, data is shared by you cant actually use it for docker layer caching, as /var/lib/docker is not designed to be shared by multiple dockerd processes.

**Comment by inahga** [comment]
> If it is ReadWriteOnce, any data doesn't persist between pod recreations, right?

Ah I think you're right. I was thinking you could set the `reclaimPolicy` of the PVC's `storageClass` to `retain`, but it seems then the backing volume won't be reused, rather it'll just sit there until manual deletion. https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain

Still though it might depend on the storage driver. I think `sig-local-storage-provisioner` for instance you can avoid scrubbing any released volumes--but I doubt other storage drivers work that way.

Either way thanks for clarifying the use case, looks like your proposed approach should fit it well.

**Comment by Puneeth-n** [comment]
@mumoshu This would be dope :) I am currently using `emptyDir` and running 1 runner per instance. The `dockerVolumeMounts` feature finally enabled me to switch to GHA from Jenkins for our heavier workloads and huge docker images 😅

**Comment by mumoshu** [comment]
@Puneeth-n Just read your voice here https://github.com/actions-runner-controller/actions-runner-controller/issues/452#issuecomment-859403796. Congrats! 🎉

**Comment by Puneeth-n** [comment]
The only reason we had Jenkins was because of the docker layer caching as our base images are huge. Huge base images + lots of services in the monorepo that leverage on these base images made it very difficult for me to move away from Jenkins.

Now I wast GitHub to allow different parameter types like choices in `workflow_dispatch` so that I can completely get rid of Jenkins

**Comment by AndreaSoldino-TomTom** [comment]
@Puneeth-n thank you for your kind words! Happy to see this work improving your quality of life 🎉

**Comment by mumoshu** [comment]
ARC v0.22.0 makes RunnerSet even more reliable so I can generally recommend v0.22.0 + RunnerSet if you do need voluemClaimTemplates!
