### ISSUE TITLE
kube webhook issue: webhooks[0].clientConfig.caBundle should not have a default empty value because it breaks ArgoCD sync

### ISSUE THREAD

**Issue by jstewart612** [actions-runner-controller/actions-runner-controller#614]

**Comment by jstewart612** [comment]
![Untitled](https://user-images.githubusercontent.com/32647598/121218530-d1ef6c80-c850-11eb-8140-772a065e536f.png)

**Comment by mumoshu** [comment]
@jstewart612 How can we fix that? I don't know much about ArgoCD

**Comment by jstewart612** [comment]
@mumoshu I have put up a PR for a suggested fix in https://github.com/actions-runner-controller/actions-runner-controller/pull/617

**Comment by peimanja** [comment]
having the same issue. appreciate the fix
