### ISSUE TITLE
QUESTION: how could I know the version of the github runner?

### ISSUE THREAD

**Issue by shenmou98** [actions-runner-controller/actions-runner-controller#618]
QUESTION: how could I know the version of the github runner is running?

**Comment by mumoshu** [comment]
@shenmou98 Hey! The only way would be to run `kubectl get po -o yaml` and see the image tag of the runner image. Also, please consider using GitHub Actions for questions and discussions. Issues are for concrete bug reports and feature requests :)

**Comment by mumoshu** [comment]
Moving to Discussions
