### ISSUE TITLE
Getting a time out when trying to install with Helm chart

### ISSUE THREAD

**Issue by GreedHub** [actions-runner-controller/actions-runner-controller#620]
**Describe the bug**

I recive:
`Error: UPGRADE FAILED: timed out waiting for the condition`

When trying to install with:
`helm upgrade --install --namespace github-actions-runner-system --create-namespace --wait actions-runner-controller actions-runner-controller/actions-runner-controller`

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Install kubernetes 1.21.1
2. Install calico network
3. Install cert-manager 1.3.1
4. Add repo https://actions-runner-controller.github.io/actions-runner-controller
4. Execute helm upgrade command

**Expected behavior**
The runner installs

**Environment (please complete the following information):**
 - Controller Version:  1.21.1
 - Deployment Method: Helm

**Context**
![image](https://user-images.githubusercontent.com/39564497/121375043-cbc3c380-c916-11eb-815c-30bbe0df5596.png)

**Comment by toast-gear** [comment]
Any more information when you include the `--debug` flag?

**Comment by GreedHub** [comment]
> Any more information when you include the `--debug` flag? https://helm.sh/docs/helm/helm_upgrade/
> 
> The below is normally helpful for finding why Helm installs fail:
> 
> ```
> kubectl -n github-actions-runner-controller get events --sort-by='{.lastTimestamp}'
> ```
It hungs at:

![image](https://user-images.githubusercontent.com/39564497/121379710-acc73080-c91a-11eb-84ca-33d331c90617.png)

I've realized that this happens 'cause of the pods being in CrashLoopBackOff, and the problem comes from the default 'controller-manager' secret. So at the middle of the installation I've executed `kubectl delete -n github-actions-runner-system secret/controller-manager` and installed one with the correct ids and secrets and the helm installation succeded.

Shold we report this as a bug?

**Comment by toast-gear** [comment]
yeh, there are 2 existing issues atm, both solvable, both problems:

1. The docs get you to deploy the solution before setting up the auth stuff. There are historical reasons as to why it's like that but it isn't correct and needs fixing, it's just never been a priority to resolve as the docs need changing quite a bit for it to not be janky

2. Look at implementing helm's `required` function so the chart rendering will fail if you haven't set 1 of the 2 auth methods e.g. https://github.com/helm/charts/blob/7e45e678e39b88590fe877f159516f85f3fd3f38/stable/atlantis/templates/secret-webhook.yaml#L14

**Comment by GreedHub** [comment]
@toast-gear 

Now im getting:
![image](https://user-images.githubusercontent.com/39564497/121393151-75f71780-c926-11eb-961c-ce0d6a81caaf.png)

And the runner never comes up:
![image](https://user-images.githubusercontent.com/39564497/121393240-8b6c4180-c926-11eb-8f95-8fc3b7d5243b.png)

This is how I created the runner:
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: dl380-g6
  namespace: github-actions-runner-system
spec:
  repository: GreedHub/UTN-AdS-2021-Anual
  env: []
```

I know the secret is working fine 'cause otherwise the actions-runner-controller wouldn't come ready, but I can't find out whats wrong, any suggestions?

**Comment by toast-gear** [comment]
Are you sure your chosen auth method has the appropriate permissions? The logs of the controller might reveal more, you can also set the log level as part of the deployment https://github.com/actions-runner-controller/actions-runner-controller/tree/master/charts/actions-runner-controller#values

**Comment by GreedHub** [comment]
I'm using App auth method, and the permissions are configrated like this:
![image](https://user-images.githubusercontent.com/39564497/121399826-367ff980-c92d-11eb-97da-4af918e3244a.png)

I've configured the secret like this (matching colors):

![image](https://user-images.githubusercontent.com/39564497/121400118-92e31900-c92d-11eb-9992-50d97dc4608c.png)
![image](https://user-images.githubusercontent.com/39564497/121400445-f79e7380-c92d-11eb-8ada-a931b038a460.png)
![image](https://user-images.githubusercontent.com/39564497/121400332-d89fe180-c92d-11eb-97af-4e2911dc77d8.png)

![image](https://user-images.githubusercontent.com/39564497/121400210-b4dc9b80-c92d-11eb-84a4-52ec567e0f1e.png)

In the logs I see this:
`error: no kind "Runner" is registered for version "actions.summerwind.dev/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"`

**Comment by GreedHub** [comment]
Here's the manager logs:

![image](https://user-images.githubusercontent.com/39564497/121403139-0175a600-c931-11eb-85b7-45d01fac10dc.png)

is it a DNS resolution error?

Also, is it ok that the services doesn't have a external-ip? It's a bare-metal cluster using Traefik as ingress controller
![image](https://user-images.githubusercontent.com/39564497/121403827-b14b1380-c931-11eb-941a-60cd06e70230.png)

**Comment by toast-gear** [comment]
> is it a DNS resolution error?

Looks like it, looks like it can't resolve the DNS entry api.github.com, your cluster must be doing something to prevent it.

> Also, is it ok that the services doesn't have a external-ip? It's a bare-metal cluster using Traefik as ingress controller

yeh, the standard setup is a pull based so as long as the controller pod can talk to the internet (specifically GitHub's addresses) then it's fine. If you want to use [webhooks](https://github.com/actions-runner-controller/actions-runner-controller#faster-autoscaling-with-github-webhook) then you will need to expose the webhook server.

**Comment by GreedHub** [comment]
@toast-gear I've solved the DNS problem and now the runner is registered in the repo

Last question:
I want to store my docker images inside Githubs Container Registry, and for that, I need my runners to have a PAT. Can I use a k8s secret inside the runner?
If not: Do I have a way to add a global ENV var for all my runners or I have to add it in every single one of them?

**Comment by mumoshu** [comment]
@GreedHub Usually you shold use [GitHub Actions "Secrets"](https://docs.github.com/en/actions/reference/encrypted-secrets). I don't think that's a good idea but if you really need to provide the PAT without using GitHub Actions' secrets, use `Runner.Spec.Env` as you would do when you mount K8s secret onto pod/container env.

**Comment by GreedHub** [comment]
I feel so dumb right now, thanks for all your help, you're awesome!

**Comment by toast-gear** [comment]
I'm considering this issue resolved, closing.
