### ISSUE TITLE
ServiceMonitor labels

### ISSUE THREAD

**Issue by vineetmadan** [actions-runner-controller/actions-runner-controller#621]
It's good to see that the support for ServiceMonitor has now been included which will make exposing metrics to prometheus a lot easier. 

In our case, prometheus is deployed to pick up servicemonitors & podmonitors with a specific label only, as I'm sure will be the case with other folks too. At the moment, the chart doesn't support adding custom labels to the ServiceMonitor.
Do you have plans to allow to add custom labels to the ServiceMonitor? 
TIA

**Comment by mumoshu** [comment]
@vineetmadan Hey! No plan on my end. But I'll gladly review any changes to make it customizable in our chart.

**Comment by roeelandesman** [comment]
Just a heads up, I think work is being done in this PR to add labels: https://github.com/actions-runner-controller/actions-runner-controller/pull/670
