### ISSUE TITLE
Remove redundant flags from webhook server

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#623]
https://github.com/actions-runner-controller/actions-runner-controller/blob/master/cmd/githubwebhookserver/main.go#L82-L83 election flag
https://github.com/actions-runner-controller/actions-runner-controller/blob/master/cmd/githubwebhookserver/main.go#L84 sync period flag

Both of these are dead parameters and could be removed

**Comment by Puneeth-n** [comment]
I was always wondering what it did 😅
