### ISSUE TITLE
Accessing the cluster with Helm from inside a runner

### ISSUE THREAD

**Issue by GreedHub** [actions-runner-controller/actions-runner-controller#627]
**Describe the bug**
I want to deploy my app from the action that's inside the runner

I've tryed setting the `KUBECONFIG` env, or the `~/.kube.config` file and applying the chart like this:
```yaml
- 
  uses: azure/setup-helm@v1
  id: install
- 
  name: 'Deploy'
        run: mkdir -p $HOME/.kube && echo ${{ secrets.KUBECONFIG }} | base64 -d > $HOME/.kube/config && cd ./frontend/helm-chart && helm install ads-frontend -f values.yaml ./

```

But I got the error (I've also tried with kubernetes.default.svc):
```
Run mkdir -p $HOME/.kube && echo *** | base64 -d > $HOME/.kube/config && cd ./frontend/helm-chart && helm install ads-frontend -f values.yaml ./
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/runner/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/runner/.kube/config
Error: Kubernetes cluster unreachable: Get "https://192.168.0.131:6443/version?timeout=32s": dial tcp 192.168.0.131:6443: i/o timeout
Error: Process completed with exit code 1.
```

**Expected behavior**
The connection with the cluster is made and the chart is deployed

**Environment (please complete the following information):**
 - Controller Version: 1.21.1
 - Deployment Method: Helm
 - Helm Chart Version: 0.1.0

**Additional context**
Running on k8s bare-metal

Runner yaml (I havn't found any documentation for the options):
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: dl380-g6
  namespace: github-actions-runner-system
spec:
  repository: GreedHub/UTN-AdS-2021-Anual
  env: []
```

**Comment by mumoshu** [comment]
@GreedHub Hey! The error message says that you're facing any of the below:

- `https://192.168.0.131:6443` is not reachable from your pod/container
- The host or the firewall running in front of it is blocking your pod/container
- The k8s pod network is not correctly set up

Ensure that other pods can e.g. access `192.168.0.131:6443` via e.g. `curl` or ping 192.168.0.131 and see what can prevent your k8s network from working.

> Runner yaml (I havn't found any documentation for the options):

RunnerDeployment.Template.Spec is basically Runner.Spec so read https://github.com/actions-runner-controller/actions-runner-controller#additional-tweaks

**Comment by mumoshu** [comment]
To be clear, this question has nothing to do with actions-runner-controller. This is a standard K8s or GitHub Actions question. If anyone facing a similar issue is reading this, be sure to fully set up your K8s cluster beforehand.

**Comment by GreedHub** [comment]
Actually I can access the k8s cluster from the runner pod.

Here's the output of `kubectl exec -i -t dl380-g6 -n github-actions-runner-system -- curl https://192.168.0.131:6443/version?timeout=32s -k`

```
Defaulted container "runner" out of: runner, docker
{
  "major": "1",
  "minor": "21",
  "gitVersion": "v1.21.1",
  "gitCommit": "5e58841cce77d4bc13713ad2b91fa0d961e69192",
  "gitTreeState": "clean",
  "buildDate": "2021-05-12T14:12:29Z",
  "goVersion": "go1.16.4",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

But when I execute an action with this runners I get the error I've mentioned before. I'm sorry if I'm asking something out of topic, but is there any extra configurations that I should do when I create the runner to give the actions that runs on him access to the k8s cluster?

**Comment by GreedHub** [comment]
Is it posible that github is using one of their runners instead of my self-hosted one?

**Comment by GreedHub** [comment]
> Is it posible that github is using one of their runners instead of my self-hosted one?

That was totally the problem, it's solved now, but the runner runs very slowly, is there something that can be done to speed them up?

If not, feel free to close the issue, and thanks for your help!

**Comment by mumoshu** [comment]
@GreedHub Glad to hear you were able to fix it :)

> the runner runs very slowly

What part of the whole process looked slow? How did you trigger your GitHub Actions workflow run? How many job steps do your workflow have? Which step is taking so long, pulling docker images, or running commands?

**Comment by GreedHub** [comment]
> What part of the whole process looked slow?
The whole process, it tooks like a minute to start, arround 30 seconds to run something like running checkout, and 6 minutes to build and push a docker image, compared to less than a minute that it took to a github online runner.

> How did you trigger your GitHub Actions workflow run?
Is running on commit to main

> How many job steps do your workflow have? Which step is taking so long, pulling docker images, or running commands?
2 workflow with 10 steps each. All the steps are taking too long.

> What cpu and ssd and how much memory do your baremetal machine running the runner have?
CPU: Intel Xeon x5670 x2 (12c,24t @2.93Ghz with 3.3Ghz boost)
RAM: 64 GB DDR3
HDD: 2x1tb wd blue raid 1 + 2x144gb sass raid 1

> How many runners are running on a single baremetal machine?
A single RunnerDeployment with 2 replicas

> What are running on your baremetal machine other than runners and actions-runner-controller?
A couple other services in kubernetes like a mosquitto server, but neither RAM or CPU usage doesn't get over 15% as it was formatted recently and it's not currently in use.

![image](https://user-images.githubusercontent.com/39564497/121786132-5cf39e00-cb94-11eb-9670-a548254358a4.png)
![image](https://user-images.githubusercontent.com/39564497/121786164-88768880-cb94-11eb-80fc-2a08d5a0bcb3.png)

I don't think that the server is too slow for the runner, neither is overloaded, but I don't really know.

**Comment by mumoshu** [comment]
@GreedHub Hey! Thanks for the additional info. A few more points from my end.

- `it tooks like a minute to start` can happen when there were no available runner at the time you pushed the commit. By default, each runner pod gets recreated on each "job" run. So if you've queued so many commits at once, it may take a while until the last job finally runs, because it also take a bit time for actions-runner-controller to autoscale. Perhaps giving more replicas to RunnerDeployment, or setting `spec.template.spec.ephemeral: false` to avoid pod restarting on each job run, or [tuning autoscaling](https://github.com/actions-runner-controller/actions-runner-controller#autoscaling) help, depending on your scenario.
- `6 minutes to build and push a docker image` does seem odd. Your machine should have enough resources. Then the only thing I suspect would be your network bandwidth and reliability, and/or dockerhub's rate limiting. I see you are running docker-build with the docker context `context: ./backend`. What if you manually create a `docker:dind` pod in your cluster using e.g `kubectl run` and run `docker build` on the same Dockerfile and build context? Does it run faster?

**Comment by GreedHub** [comment]
> * `6 minutes to build and push a docker image` does seem odd. Your machine should have enough resources. Then the only thing I suspect would be your network bandwidth and reliability, and/or dockerhub's rate limiting. I see you are running docker-build with the docker context `context: ./backend`. What if you manually create a `docker:dind` pod in your cluster using e.g `kubectl run` and run `docker build` on the same Dockerfile and build context? Does it run faster?

yes, it runs pretty quickly, the steps it takes long to make are the building ones, so is like a computing power issue, but the server has enough resources to spare

**Comment by mumoshu** [comment]
Then my best bet is your have some MTU issue or you have external connectivity issue
