### ISSUE TITLE
Clean up import list

### ISSUE THREAD

**Issue by sledigabel** [actions-runner-controller/actions-runner-controller#644]
Hi,

Not a bug per say, and sorry if this was mentioned before, I've noticed that some imports are pointing to `summerwind` rather than `actions-runner-controller`, as I understand it, it's some left overs from the rename.

A few examples:
https://github.com/actions-runner-controller/actions-runner-controller/blob/master/cmd/githubwebhookserver/main.go#L28-L29

https://github.com/actions-runner-controller/actions-runner-controller/blob/master/main.go#L27-L29

and basically everywhere. I presume it still works because of the github redirection after the project was moved,
Just thought I'd file an issue to mention this, and if that makes sense I could file a quick PR to search/replace `summerwind` into `actions-runner-controller` as a first contribution to this great project?

**Comment by toast-gear** [comment]
Yes this needs doing, the only thing that doesn't need migrating to the new location in the code is the summerwind API itself.

**Comment by mumoshu** [comment]
@sledigabel Hey! Thanks a lot for reporting. I completely forgot to do this. As I was about to start working on another feature, I've submitted #645 for this to avoid potential conflict. Would you mind reviewing it?

**Comment by sledigabel** [comment]
Well done for the quick feedback! I put a few comments around the helm charts, but the rest looks good to me

**Comment by jstewart612** [comment]
@mumoshu @sledigabel you haven't renamed Docker Hub account yet so .Values.image.repository value is currently broken

**Comment by mumoshu** [comment]
@jstewart612 Thanks! I'll fix it in https://github.com/actions-runner-controller/actions-runner-controller/pull/663
