### ISSUE TITLE
Update CRDs in helm chart

### ISSUE THREAD

**Issue by ozlotusflare** [actions-runner-controller/actions-runner-controller#650]
**Describe the bug**
Hello everyone,
I have upgraded actions-runner-controller from `0.10.4` to `0.12.2`, for this I used [Upgrade instruction](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/docs/UPGRADING.md) and found that the `CRDs ` were different. (comparing with repo) 

**To Reproduce**
1. Go to 'https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/docs/UPGRADING.md'
2. Run step-by-step 
``` bash
CHART_VERSION=0.12.2

curl -L https://github.com/actions-runner-controller/actions-runner-controller/releases/download/actions-runner-controller-${CHART_VERSION}/actions-runner-controller-${CHART_VERSION}.tgz | tar zxv --strip 1 actions-runner-controller/crds

kubectl apply -f crds/ 
```

**Expected behavior**
Install the new version of `CRDs`

**Screenshots**
Here is diff
<img width="1718" alt="crds-repo:actions summerwind" src="https://user-images.githubusercontent.com/78478066/123087671-78309a00-d42d-11eb-8903-911206d6b97f.png">

**Comment by mumoshu** [comment]
@ozlotusflare What are you diffing the repo crds against? CRDs on your cluster?

**Comment by ozlotusflare** [comment]
Hi @mumoshu 
`CRDs in repo` vs `CRDs` from Helm chart (I've pulled chart and checked) , also I checked difference  between `CRDs in repo` vs `CRDs` from  here: 
``` bash
...
curl -L https://github.com/actions-runner-controller/actions-runner-controller/releases/download/actions-runner-controller-${CHART_VERSION}/actions-runner-controller-${CHART_VERSION}.tgz | tar zxv --strip 1 actions-runner-controller/crds
...
```
Same situation.

**Comment by toast-gear** [comment]
The CRDs @ HEAD in the repo won't match the CRDs in the release because we don't do an individual release for every single change that is merged into master. The CRDs will match the CRDs in the repo @ the tag commit.

Are you saying the CRDs don't match HEAD?

**Comment by ozlotusflare** [comment]
Hi @toast-gear , 
Thanks for clarification.
