### ISSUE TITLE
DIND Runner: Wrong github-action runner ".env" file name?

### ISSUE THREAD

**Issue by thomas-z-meyer-db** [actions-runner-controller/actions-runner-controller#655]
The github action runner does only seem to pick up the environment variables from the file ".env" (at least as far as I could understand from the runner's source code).

https://github.com/actions-runner-controller/actions-runner-controller/blob/acb906164b6cc8b3604fa816cd3a99acffe991a2/runner/Dockerfile.dindrunner#L95

The other two Dockerfiles seems to output the environment variable AGENT_TOOLSDIRECTORY to the correct ".env" file.

Because of this the dind runners fail to correctly setup a persistent RUNNER_TOOL_CACHE cache directory, which make each new github workflow invocation download all binaries again, e.g. setup-gcloud.
This is because the runner will fallback to a _tool directory inside the _work directory which will be wiped with each workflow run:
https://github.com/actions/runner/blob/main/src/Runner.Common/HostContext.cs#L249

**Comment by mumoshu** [comment]
@thomas-z-meyer-db Thanks for reporting! This has been fixed via #65 by @toast-gear. Would you mind giving it a shot again with the latest runner image?

**Comment by mumoshu** [comment]
BTW, anything other than `RUNNER_TOOL_CACHE` seem to have already deprecated according to https://github.com/actions/runner/blob/ee34f4842e747b452e13235836c92b2bb1606816/src/Runner.Common/HostContext.cs#L244-L245

Perhaps we'd better migrate to `RUNNER_TOOL_CACHE`? (It would worth another dedicated github issue though

**Comment by thomas-z-meyer-db** [comment]
Not sure, the initial commit that did introduce the env here, did talk about a setup-ruby action that needed this environment variable.
Also searching in Microsofts virtual-environment itself, it looks like AGENT_TOOLSDIRECTORY is still in heavy use: https://github.com/actions/virtual-environments/search?p=2&q=AGENT_TOOLSDIRECTORY

**Comment by toast-gear** [comment]
yeh I noticed this when I was doing my searching for the change. In all examples I found either `RUNNER_TOOL_CACHE` was respected or the path was hard-coded because it can't be custom regardless so I decided it was worth doing the change now. If we end up with reports saying this is an issue we can add `ENV AGENT_TOOLSDIRECTORY=$RUNNER_TOOL_CACHE` in with a comment.
