### ISSUE TITLE
Service monitor reports "server returned HTTP status 400 Bad Request" on latest

### ISSUE THREAD

**Issue by AlexDHoffer** [actions-runner-controller/actions-runner-controller#656]
**Describe the bug**

Set to latest, my Prometheus Operator installation cannot seem to scrape the service monitor. It reports the following:

![image](https://user-images.githubusercontent.com/19369483/123486067-371cbf00-d5c0-11eb-9dd1-8e6ace066bd2.png)

The endpoint it is looking at is "metrics-port". Kind of curious if this is an HTTP/HTTPS issue?

**Checks**

- [ x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

Run the latest Helm chart. Make sure CRDs are updated to this version. Make sure runner pods are using latest image. Then, enable the service monitor with a label that your Prometheus Operator can key off. Then, look at your targets in your Prometheus UI.

**Expected behavior**
Successful flowing of metrics.

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.18.2] summerwind/actions-runner-controller:v0.19.0
 - Deployment Method [e.g. Helm and Kustomize ] Helm
 - Helm Chart Version [e.g. 0.11.0, if applicable] 0.12.2

**Additional context**

Running on AKS. Prometheus stack version is kube-prometheus-stack-9.3.4 deployed via Helm.

**Comment by AlexDHoffer** [comment]
Note: disabling the metrics proxy fixed the issue here. Any ideas how I can adjust so that I can enable the metrics proxy here and it will work?

**Comment by mumoshu** [comment]
@AlexDHoffer Hey! Thanks for reporting. I think this is the exact same issue as I'm discussing for a potential fix at #625 with @jstewart612.

Would you mind checking https://github.com/actions-runner-controller/actions-runner-controller/pull/625#issuecomment-867229742 and see if the potential solution work?

**Comment by AlexDHoffer** [comment]
@mumoshu Thanks for the heads up! I'll give it a shot Monday and report back. Hopefully it is OK if I leave this open til then.

**Comment by AlexDHoffer** [comment]
@mumoshu This config borrowed from the posted link indeed allows you to scrape via the proxy:

````
endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true

**Comment by rlandesman** [comment]
Hi all,

I think i'm seeing a similar issue on the `actions-runner-controller-github-webhook-server-service-monitor`, getting a HTTP status 401 unauthorized code from Prometheus. I wonder if the fix is the same as in #625?

**Comment by mumoshu** [comment]
@rlandesman Yes, I believe so! Would you mind giving it a shot with your local fork of the chart and submit a PR for that if possible?

**Comment by rlandesman** [comment]
Sure thing, opened a PR here: https://github.com/actions-runner-controller/actions-runner-controller/pull/685 👍🏼
