### ISSUE TITLE
new chart specifies image that requires auth to access (or does not exist)

### ISSUE THREAD

**Issue by oneubauer** [actions-runner-controller/actions-runner-controller#662]
**Describe the bug**
new chart default values pull from a repo that requires auth

**To Reproduce**
- Install default chart. 
- note image uri for action controller:
`actions-runner-controller/actions-runner-controller:v0.19.0`
vs old
`summerwind/actions-runner-controller:v0.19.0`
- note:
```
❯ kubectl get pods -n actions-runner-system
NAME                                        READY   STATUS             RESTARTS   AGE
actions-runner-controller-746b956bd-8ghxp   1/2     ImagePullBackOff   0          25m
```

and from `describe`:
```
  Warning  Failed       25m (x3 over 26m)    kubelet            Failed to pull image "actions-runner-controller/actions-runner-controller:v0.19.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for actions-runner-controller/actions-runner-controller, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
- attempt to pull new image ```actions-runner-controller/actions-runner-controller:v0.19.0``` without credentials

```
❯ docker pull actions-runner-controller/actions-runner-controller:v0.19.0

                                                                         
Error response from daemon: pull access denied for actions-runner-controller/actions-runner-controller, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
Older location works as expected:
```
❯ docker pull summerwind/actions-runner-controller:v0.19.0


v0.19.0: Pulling from summerwind/actions-runner-controller
5dea5ec2316d: Already exists 
3f8f197f898e: Pull complete 
0058164f90d9: Pull complete 
Digest: sha256:46f7d937168de71bbee9767fe20296e5a569e64a7926661d7ea59423c500a5d2
Status: Downloaded newer image for summerwind/actions-runner-controller:v0.19.0
docker.io/summerwind/actions-runner-controller:v0.19.0
```

**Expected behavior**
pulling image should not require credentials

**Environment (please complete the following information):**
 - Controller Version https://github.com/actions-runner-controller/actions-runner-controller/releases/tag/actions-runner-controller-0.12.3. 
 - Image version: 0.19
 - Deployment Method: Helm (via in cluster helm-controller, but behavior is not specific to that)
 - Helm Chart Version: 0.12.3

**Workaround**

explicitly specify legacy image location

**Comment by mumoshu** [comment]
@oneubauer Thanks for reporting! I'm fixing it in https://github.com/actions-runner-controller/actions-runner-controller/issues/662
