### ISSUE TITLE
GithubWebhookServer Service Annotations Field

### ISSUE THREAD

**Issue by rlandesman** [actions-runner-controller/actions-runner-controller#664]
**Is your feature request related to a problem? Please describe.**
For my use case of the helm chart I would like to add annotations to the githubWebhookServer Service, i.e here: https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/templates/githubwebhook.service.yaml#L4-L8

**Describe the solution you'd like**
Implementation of the annotation field

**Comment by toast-gear** [comment]
The raised PR has been merged which included a chart bump, closing.
