### ISSUE TITLE
Runner not starting: `mv: inter-device move failed: '/runnertmp/bin' to '/runner/bin'`

### ISSUE THREAD

**Issue by rajbos** [actions-runner-controller/actions-runner-controller#686]
**Describe the bug**
The runner is not starting correctly

**Checks**

- [x] My actions-runner-controller version (v0.18.2) does support the feature

**To Reproduce**
I've deployed everything with settings for GitHub Enterprise, including the GitHub App settings. 
When I deploy either a single Runner (below) or a  RunnerDeployment, the runner container logs show errors and fail to start.

``` yaml
# runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: gh-runner
spec:
  repository: robbos/testing-grounds
  env: []
```

I've already had to overcome having the container images available locally (tight down security internally) and giving access to the GHE Api through the firewall, so I was hoping to have jumped trough all internal hoops by now :grin:.

**Expected behavior**
The runner to start or give me an error I can hunt down :-).

I'm getting either of the two logs below
**Logs 1**
```
kubectl logs gh-runner runner

mv: inter-device move failed: '/runnertmp/bin' to '/runner/bin'; unable to remove target: Directory not empty
mv: inter-device move failed: '/runnertmp/externalstmp' to '/runner/externalstmp'; unable to remove target: Directory not empty


--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication
```
And then nothing, or the logs below

**Logs 2**
````
kubectl logs gh-runner runner

Github endpoint URL https://gh-dev.*********.***/
mv: inter-device move failed: '/runnertmp/bin' to '/runner/bin'; unable to remove target: Directory not empty
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/runner/bin/'.
diff: bin/runsvc.sh: No such file or directory
mv: cannot stat 'bin/runsvc.sh': No such file or directory
19c19
< var runService = function () {
---
> var runService = function() {
23c23
<     if (!stopping) {
---
>     if(!stopping) {
27c27
<                 listener = childProcess.spawn(listenerExePath, ['run'], { env: process.env });
---
>                 listener = childProcess.spawn(listenerExePath, ['run'].concat(process.argv.slice(3)), { env: process.env });
30c30
<                 listener = childProcess.spawn(listenerExePath, ['run', '--startuptype', 'service'], { env: process.env });
---
>                 listener = childProcess.spawn(listenerExePath, ['run', '--startuptype', 'service'].concat(process.argv.slice(2)), { env: process.env });
33c33
<             console.log(`Started listener process, pid: ${listener.pid}`);
---
>             console.log('Started listener process');
43,46d42
<             listener.on("error", (err) => {
<                 console.log(`Runner listener fail to start with error ${err.message}`);
<             });
< 
64c60
<                 if (!stopping) {
---
>                 if(!stopping) {
69c65
<         } catch (ex) {
---
>         } catch(ex) {
78c74
< var gracefulShutdown = function (code) {
---
> var gracefulShutdown = function(code) {
95c91
< });
---
> });
\ No newline at end of file
.path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/runner/.local/bin
Starting Runner listener with startup type: service
Started listener process
Started running service
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/runner/bin/'.
Runner listener exited with error code 131
Runner listener exit with undefined return code, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/runner/bin/'.
Runner listener exited with error code 131
Runner listener exit with undefined return code, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
````

The last few lines are then returned continuously in a loop:
```
Started listener process
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/runner/bin/'.
Runner listener exited with error code 131
Runner listener exit with undefined return code, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service 
```

Checking the logs from the controller-manager I see this;
```
2021-07-09T08:44:22.308Z	DEBUG	actions-runner-controller.runner	Rechecking the runner registration in 1m10.090837275s	{"runner": "default/gh-runner"}
2021-07-09T08:44:22.317Z	INFO	actions-runner-controller.runner	Skipped registration check because it's deferred until 2021-07-09 08:45:22 +0000 UTC. Retrying in 58.682771464s at latest	{"runner": "default/gh-runner", "lastRegistrationCheckTime": "2021-07-09 08:44:22 +0000 UTC", "registrationCheckInterval": "1m0s"}
2021-07-09T08:44:54.013Z	INFO	actions-runner-controller.runner	Skipped registration check because it's deferred until 2021-07-09 08:45:22 +0000 UTC. Retrying in 26.986504386s at latest	{"runner": "default/gh-runner", "lastRegistrationCheckTime": "2021-07-09 08:44:22 +0000 UTC", "registrationCheckInterval": "1m0s"}
2021-07-09T08:45:06.442Z	INFO	actions-runner-controller.runner	Skipped registration check because it's deferred until 2021-07-09 08:45:22 +0000 UTC. Retrying in 14.557120212s at latest	{"runner": "default/gh-runner", "lastRegistrationCheckTime": "2021-07-09 08:44:22 +0000 UTC", "registrationCheckInterval": "1m0s"}
2021-07-09T08:45:21.099Z	DEBUG	actions-runner-controller.runner	Runner pod exists but we failed to check if runner is busy. Apparently it still needs more time.	{"runner": "default/gh-runner", "runnerName": "gh-runner"}
2021-07-09T08:45:21.100Z	DEBUG	actions-runner-controller.runner	Rechecking the runner registration in 1m10.926986803s	{"runner": "default/gh-runner"}
2021-07-09T08:45:21.107Z	INFO	actions-runner-controller.runner	Skipped registration check because it's deferred until 2021-07-09 08:46:21 +0000 UTC. Retrying in 58.892661515s at latest	{"runner": "default/gh-runner", "lastRegistrationCheckTime": "2021-07-09 08:45:21 +0000 UTC", "registrationCheckInterval": "1m0s"}
```
Which makes sense, if the runner is not starting correctly.

If I connect to the pod and call `./run.sh` I get this error, which makes sense from the errors above:
```
$ ./run.sh
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/runner/bin/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.20.04-x64
```

**Environment:**
 - Controller Version [v0.18.2]
 - Deployment Method [kubectl]

**Additional context**
Running this on Rancher, inside a project with no Pod Security Policies during the initial testing phase, so I don't expect any errors from that setup.

Any help finding the cause of this is appreciated, would love to have a running setup :-)

**Comment by rajbos** [comment]
Is there a way to prevent the runner from being restarted every minute because of this? That would help with debugging :-)

**Comment by mumoshu** [comment]
@rajbos Hey! How did you build your runner image? The libhostpolicy.so error seems to be related to dotnet core and it is very likely you've some missing file in your custom runner image

**Comment by mumoshu** [comment]
> Is there a way to prevent the runner from being restarted every minute because of this? That would help with debugging :-)

Nope. But you should be able to create a copy of the runner pod that is not managed by the controller by running `kubectl get po -o yaml` and removing managedFields and changing metadata.name in the yaml and then run `kubectl apply -f $THE_POD_YAML_FILE`.

**Comment by rajbos** [comment]
> @rajbos Hey! How did you build your runner image? The libhostpolicy.so error seems to be related to dotnet core and it is very likely you've some missing file in your custom runner image

We mirror the images over to our internal setup, based on these:
```
summerwind/actions-runner-controller:v0.18.2
summerwind/actions-runner:v0.18.2
brancz/kube-rbac-proxy:v0.8.0
docker:dind
```

**Comment by mumoshu** [comment]
@rajbos Gotcha! Thanks for clarifying. Then I doubt if the `mv` error is doing something wrong.

What if you run `df -h` within the pod? I think `/runner` and `/runnertmp` aren't in different devices, right? Then you'd need to somehow let kubelet(as far as I remember) to use the same device for the `emptyDir` volume that is backing `/runner`.

Otherwise, trying changing this `mv` to `cp -r` and build a custom runner image and specify that via a command-line flag of actions-runner-controller.

https://github.com/actions-runner-controller/actions-runner-controller/blob/f19e7ea8a8bce21bf66d2ee9eaaabb245c7992fa/runner/entrypoint.sh#L58

**Comment by rajbos** [comment]
dh -h results:
``` 
$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
overlay                       50G   21G   30G  41% /
tmpfs                         64M     0   64M   0% /dev
tmpfs                         32G     0   32G   0% /sys/fs/cgroup
/dev/mapper/KUBELET-KUBELET   50G  450M   50G   1% /runner
/dev/mapper/DOCKER-DOCKER     50G   21G   30G  41% /etc/hostname
shm                           64M     0   64M   0% /dev/shm
tmpfs                         32G   12K   32G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                         32G     0   32G   0% /proc/acpi
tmpfs                         32G     0   32G   0% /proc/scsi
tmpfs                         32G     0   32G   0% /sys/firmware
```

**Comment by toast-gear** [comment]
> > @rajbos Hey! How did you build your runner image? The libhostpolicy.so error seems to be related to dotnet core and it is very likely you've some missing file in your custom runner image
> 
> We mirror the images over to our internal setup, based on these:
> 
> ```
> summerwind/actions-runner-controller
> summerwind/actions-runner
> brancz/kube-rbac-proxy:v0.8.0
> docker:dind
> ```
> 
> I guess the latest versions where pulled for this, since I see the sha265 hashes on the `actions-runner` match with latest.

You're also probably going to want to mirror all tags of `brancz/kube-rbac-proxy` because we will be bumping this over time.

**Comment by rajbos** [comment]
> > > @rajbos Hey! How did you build your runner image? The libhostpolicy.so error seems to be related to dotnet core and it is very likely you've some missing file in your custom runner image
> > 
> > 
> > We mirror the images over to our internal setup, based on these:
> > ```
> > summerwind/actions-runner-controller
> > summerwind/actions-runner
> > brancz/kube-rbac-proxy:v0.8.0
> > docker:dind
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I guess the latest versions where pulled for this, since I see the sha265 hashes on the `actions-runner` match with latest.
> 
> You're also probably going to want to mirror all tags of `brancz/kube-rbac-proxy` because we will be bumping this over time.

Thanks! Already planning for that as well, first a working setup ;-)

**Comment by rajbos** [comment]
> I'll try with a custom image then to change this and will report back. Thanks!

Finally got through other issues (like a proxy for downloading/allowlisting external images) and things work :-). 

So the only change needed was this:
```
# update from https://github.com/actions-runner-controller/actions-runner-controller/issues/686
# mv /runnertmp/* /runner/ 
cp -r /runnertmp/* /runner/
``` 

If it helps, I can send in a PR for this, doesn't do any harm for regular setups, right?
