### ISSUE TITLE
RunnerDeployment Repository Var Bug

### ISSUE THREAD

**Issue by riesbl01** [actions-runner-controller/actions-runner-controller#688]
**Describe the bug**
The regex check for the repoisitoy variable in Kind: RunnerDeployment, checks for '^[^/]+/[^/]+$' which requires a '/' between 2 strings. For my case I am using a repository inside of the my company organization, so I am also defining the organization var. The issue is the repo var should take only the name of the repo (when inside an org), with no '/' denoting who owns it. Then because the org var is also defined I would think the helm chart would concat those 2 vars together with the '/', but I get the following error:

│ Error: RunnerDeployment.actions.summerwind.dev "example" is invalid: spec.template.spec.repository: Invalid value: "": spec.template.spec.repository in body should match '^[^/]+/[^/]+$'

So I also tried to define org var as the org value, but then put in the repo var as org/repo but then get the following error:

| Error: cannot patch "example" with kind RunnerDeployment: admission webhook "validate.runnerdeployment.actions.summerwind.dev" denied the request: RunnerDeployment.actions.summerwind.dev "example" is invalid: spec.template.spec.repository: Invalid value: "<org name>/<repo name>": Spec cannot have many fields defined enterprise, organization, and repository.

So to finish it off, I concluded by trying to set the repo to <org name>/<repo name> again, but without defining the organization var this time. Finally it deployed in terraform. 

**Note** I have yet to check and see if the runner is working, so I wouldn't consider this a viable workaround. 

**Checks**
_Versionz:_ actions.summerwind.dev/v1alpha1

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
- See description above

**Expected behavior**
I expect a conditional to exist within the code that says when organization is defined, rgex excludes the need for the '/', and when organization is NOT defined, then to keep the regex that is currently being used.

**Environment (please complete the following information):**
 - Kubernetes Version: 1.18.17
 - Deployment Method: Terraform Helm Release
 - Helm Chart Version: 0.0.1

**Additional context**
I also tried to deploy these helm charts locally outside of terraform and got the same errors. So I feel very confident the issue is unrelated to deploying with terraform.

**Comment by mumoshu** [comment]
> I expect a conditional to exist within the code that says when organization is defined, rgex excludes the need for the '/', and when organization is NOT defined, 

Nope. `organization` is for defining organizational runners and `repository` is for repository runners`. If it worked like you expected, there will be no way to distinguish the two :)

All the explanations and logs you've shared seem to explain this. So to me, it looks like you're just explaining how the runner deployments are supposed to work (and it seems to be working as expected to me).

Also, we don't have a chart that creates RunnerDeployment. So it should have nothing to do with Helm.

**Comment by riesbl01** [comment]
> > I expect a conditional to exist within the code that says when organization is defined, rgex excludes the need for the '/', and when organization is NOT defined,
> 
> Nope. `organization` is for defining organizational runners and `repository` is for repository runners`. If it worked like you expected, there will be no way to distinguish the two :)
> 
> All the explanations and logs you've shared seem to explain this. So to me, it looks like you're just explaining how the runner deployments are supposed to work (and it seems to be working as expected to me).
> 
> Also, we don't have a chart that creates RunnerDeployment. So it should have nothing to do with Helm.

Gotcha, thank you for the explanation, that makes more since.
