### ISSUE TITLE
Summerwind Dockerhub publishing endpoint for images

### ISSUE THREAD

**Issue by ap0phi5** [actions-runner-controller/actions-runner-controller#699]
1. Since the GH Org was renamed from **summerwind** to **actions-runner-controller**, we haven't done the same with the dockerhub org.

Can I suggest that someone claims the **actions-runner-controller** namespace in dockerhub as an organisation and then we start using that as where we publish to?

2. Since https://github.com/actions-runner-controller/actions-runner-controller/pull/510, `DOCKERHUB_USERNAME` was changed from `${{ github.repository_owner }` to `${{ secrets.DOCKER_USER }}` - this has also made it difficult to track where the actions are publishing the images (Secrets are obfuscated in the log output).

Can I suggest we consider hardcoding the environment variable into actions?
aka, use DOCKERHUB_USERNAME = "summerwind" or "actions-runner-controller".

Happy to PR, but need someone with repo admin to own the Dockerhub integration and create a second `DOCKER_ACCESS_TOKEN` secret.

**Comment by mumoshu** [comment]
@ap0phi5 Hey! Can we close this as a dup of https://github.com/actions-runner-controller/actions-runner-controller/issues/566? Anyway, I've already taken `actionsrunnercontroller` organization on GitHub for this. Do you this that's a good-enough name?

**Comment by ap0phi5** [comment]
Hi @mumoshu ,
Cool. If I was being picky, I would try and opt for exactly the same namespace as how this org is named with the hyphens, aka actions-runner-controller. Is that possible?

Also, I do see that we need to do something about the secret variable that is being used to store the namespace, because the push to DockerHub is no longer transparent. 

I saw the other ticket talking about the use of GHCR - are you not keen to push to this too?

**Comment by mumoshu** [comment]
@ap0phi5 Hey! As I have written in #566,

> DockerHub doesn't allow hyphens in the organization name so it's impossible to just use actions-runner-controller.

**Comment by mumoshu** [comment]
> are you not keen to push to this too?

What do you mean by this, exactly? I have no motivation to move it forward myself at the moment. But if anyone from the community is willing to take leadership and start contributing automated workflows and other things, I'd appreciate it!

**Comment by ap0phi5** [comment]
Ah I didn't know that hyphens didn't work. Alright, let's go with actionsrunnercontroller - we can continue to use the existing namespace in parallel to give end users time to transition - cool?

I'm away for a few days but happy to pickup and do a PR when I get back next week.
