### ISSUE TITLE
Runners are not always unregistered from GitHub

### ISSUE THREAD

**Issue by shahar-h** [actions-runner-controller/actions-runner-controller#702]
**Describe the bug**
First of all, thanks for this awesome project 🏆 .

When runner is deleted by actions-runner-controller as a result of a scale down it should be unregistered from GitHub. However, runners are not always unregistered, so after some time there are many offline runners in GitHub (See screenshot), and I need to manually remove them.
According to the logs runner was removed from GitHub but it's still there:
`INFO	actions-runner-controller.runner	Removed runner from GitHub	{"runner": "actions-runner/runner-pool-8tqwt-97pc8", "repository": "", "organization": "****"}`

I can see that runner pod and `runner` custom resource are deleted from the cluster.

I'm not sure how to investigate this issue so any help would be appreciated. 

**Checks**

- [x ] My actions-runner-controller version (v0.19.0) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
It's hard to reproduce, as it doesn't occur consistently. 

**Expected behavior**
When runner is deleted GitHub runner should be unregistered. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16555289/126513721-438331ab-4b65-4449-840d-3052327e5725.png)
![image](https://user-images.githubusercontent.com/16555289/126513844-45d055b8-2e0a-43e5-b268-6863cba14082.png)
![image](https://user-images.githubusercontent.com/16555289/126514230-a96b533e-0e9b-4e8d-9522-ee6ea7af2b8b.png)

As you can notice the first 4 runners in GitHub do not appear in the cluster.

**Environment (please complete the following information):**
 - Controller Version [0.19.0]
 - Deployment Method [Helm]
 - Helm Chart Version [0.12.2]

**Additional context**
I'm working against GHE 3.0.10.

**Comment by mumoshu** [comment]
@shahar-h Hey! Thanks for reporting. Theoretically speaking, any runner pod that terminated unexpectedly(due to a node breakage, spot termination on EC2, etc) can result in that situation. Currently, you'll need to periodically run some "cleaner" process that matches all the runners in your K8s cluster and those in GitHub and remove runners missing in K8s from GitHub.

**Comment by gjkim42** [comment]
https://github.com/gjkim42/actions-runner-cleaner

made my own cleaner to workaround this issue.
