### ISSUE TITLE
Autoscale runners based on label

### ISSUE THREAD

**Issue by lucavallin** [actions-runner-controller/actions-runner-controller#703]
**Is your feature request related to a problem? Please describe.**
I am using the HPA to autoscale runners based on total queued and in progress jobs. The controller monitors the repositories, but makes no distinction between different environments (set with labels). Currently, the runners in all of my environments scale together even when there are no queued/in progress jobs in my, for example, acceptance or production environments.

**Describe the solution you'd like**
I would like the HPA to respect the custom labels I am assigning to the runners when it comes to autoscaling, so that runners for different environments are scaled based on the effective load there is on runners for a specific environment.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by toast-gear** [comment]
We get this request often and we can't add the feature as it isn't technically possible atm. GitHub do not provide the requireed `runs-on` information for us to be able to scale runners up based on a label. The good news is GitHub are aware of this limitation and are making the backend changes needed for us to be able to scale based on labels https://github.com/actions-runner-controller/actions-runner-controller/issues/697

I'm closing this issue as we can't do anything about this until GitHub make their changes available to their public API.

**Comment by lucavallin** [comment]
Thank you!
