### ISSUE TITLE
Guidance on the callback URL for GitHub app authentication

### ISSUE THREAD

**Issue by matthewcummings** [actions-runner-controller/actions-runner-controller#704]
This controller is fantastic. I have a question about authenticating via a GitHub application. When I go to create an org level app, I'm required to add an Oauth callback URL. What should use for that? I feel like this might be something the controller will expose provided GitHub can access it over the internet.
Any help here is appreciated.

**Comment by mumoshu** [comment]
@matthewcummings Hey! You don't need it, because actions-runner-controller doesn't rely on the user authorization.
