### ISSUE TITLE
Outdated version of https://github.com/actions/runner causes crash loop

### ISSUE THREAD

**Issue by ToMe25** [actions-runner-controller/actions-runner-controller#706]
**Describe the bug**
It seems that after trying to update the runner software the pod gets stuck in an perpetual crash loop.
For some reason it was working earlier today even tho the new release is 6 days old, but that might have been because it didn't restart the pod since then, which got forced by me updating the deployment yaml and reapplying it.
I had something like this earlier with the last update, however there was a runner image update shortly after I encountered the issue which fixed it, so I didn't report it.

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Deploy a version of the runner with an outdated actions runner version, i guess
2. try to get it to execute an action
3. See the error

**Expected behavior**
I expected the runner pod to either update once and then work or not update at all.

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version v0.19
 - Deployment Method kubectl
 - Helm Chart Version N/A

**Additional context**
The log from one of the pods: https://pastebin.com/3m6pxYir

**Comment by ToMe25** [comment]
Somehow this fixed itself now, even tho I tried for hours to get it to work before reporting it without any success.

**Comment by ToMe25** [comment]
I was away for a while and now the problem is back...

**Comment by mumoshu** [comment]
@ToMe25 Hey! Thanks for reporting, but unfortunately I don't think we can debug this on our end. Have you already reported your issue to `actions/runner`?

**Comment by ToMe25** [comment]
@mumoshu I have not reported that to them, because last time I had this issue it seemed to me like it was caused by the pod restarting whenever the runner updated.
This time it didn't seem to restart actually, which surprised me, however it still looked like a container related issue to me.
If you think this is an issue with the runner itself, tell me and I will report it to them.

**Comment by ToMe25** [comment]
Uh, I forgot to mention, but while the runners are set to be ephemeral, they don't seem to actually restart after the update.
Last time they did definitively restart after updating, putting them in an endless loop.

**Comment by toast-gear** [comment]
Closing this as this as we have an existing [issue](https://github.com/actions-runner-controller/actions-runner-controller/issues/416) for solving this problem. If you would like to show your support on https://github.com/actions/runner/issues/485 as the inability to opt-out of this behaviour is in GitHub's hands (please do as it's a bit silly that GitHub offers no solution, especially as it causes lots of issues for anyone running Actions in containers)

**Comment by ToMe25** [comment]
I didn't know there was an issue for this already.
I have reacted to some comments on the runner issue.
Thanks for letting me know.
