### ISSUE TITLE
Webhook ping doesn't work on GHES and github.com

### ISSUE THREAD

**Issue by vvraskin** [actions-runner-controller/actions-runner-controller#709]
I've tried look for existing issues of this kind, but was not able to do so. I'm quite new to this repo, so let me know if some info is missing or there is some easy fix. Thank you!

**Describe the bug**

Configuring a webhook in github for a webhook server doesn't work. A 500 response code is received.
The following error is shown in the logs of webhook server (truncated for readability):
```
2021-08-02T08:54:05.946Z	ERROR	controllers.Runner	could not parse webhook	{"webhookType": "ping", "payload": "payload=%7B%
....
7D%7D", "error": "invalid character 'p' looking for beginning of value"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/summerwind/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerGitHubWebhook).Handle
	/workspace/controllers/horizontal_runner_autoscaler_webhook.go:131
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2417
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2843
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1925
```

**Checks**

- [x] My actions-runner-controller version (v0.19.0) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Follow the instructions to configure an [autoscaler with a github webhook](https://github.com/actions-runner-controller/actions-runner-controller#faster-autoscaling-with-github-webhook)
2. Configured an ingress controller to expose the webhook server endpoint
3. Make sure that the webhook server is running 
    - Run `curl http://my-url.com` and see it returns `webhook server is running`.
4.  Configure a new webhook in a repo in github.com or in GHES
5. See a 500 response code from the server
6. Go to the logs of the webhook server and see the error above 

**Expected behavior**
A github webhook ping returns a 200.

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version - 0.19.0
 - Deployment Method - Helm
 - Helm Chart Version - v3.6.3

**Comment by mumoshu** [comment]
@vvraskin Hey! Thanks for reporting. This does soudn like a bug. I read some code and my theory is that the HTTP request body for a webhook ping isn't JSON-encoded so we need to skip json parsing here only for pings:

https://github.com/actions-runner-controller/actions-runner-controller/blob/743e6d620219d7b31e611c88051a560927b02780/controllers/horizontal_runner_autoscaler_webhook.go#L124-L131

Would you mind submitting a PR for that, if possible?

**Comment by vvraskin** [comment]
hey @mumoshu thank you for a quick reply!

Actually it should be in json format according to the documentation https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#ping . 

I would be happy to fix it myself, just don't know how fast I would get an approval from my company to contribute to the project. Due to legal reasons (~~internal bureaucracy~~) it might take several months to get one.

Do you think that is something you could take in the community backlog?

**Comment by mumoshu** [comment]
@vvraskin Hey! Thanks for the reply. Yeah, I'm going to tag this as a `bug` and try to convince people and me to have some time to work on it, if this turned out to be 100% a bug. Thanks for clarifying your situation. I appreciate that.

> Actually it should be in json format according to the documentation

Sounds odd, right?!
Would you mind checking your "webhook settings" page in GitHub and see what `content type` is set there?
I guess it's set to `application/x-www-form-encoded` when you get the error?
If so, can you change it to `application/json` and see if the error goes away?

**Comment by vvraskin** [comment]
@mumoshu Thank you for your time!
You are right, it was the content type! These newbie user problems... :)
