### ISSUE TITLE
secret "controller-manager" not found

### ISSUE THREAD

**Issue by nicolasdonoso** [actions-runner-controller/actions-runner-controller#713]
**Describe the bug**
I followed the install instructions from [this](https://github.com/actions-runner-controller/actions-runner-controller#installation) link using helm and kubectl and in both cases the controller-manager pod is not starting and this is the error that I'm getting 

```
  Warning  FailedMount  5m43s (x2 over 7m59s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[controller-manager], unattached volumes=[cert controller-manager default-token-54h4s]: timed out waiting for the condition
  Warning  FailedMount  3m27s (x2 over 10m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[controller-manager], unattached volumes=[controller-manager default-token-54h4s cert]: timed out waiting for the condition
  Warning  FailedMount  119s (x13 over 12m)    kubelet            MountVolume.SetUp failed for volume "controller-manager" : secret "controller-manager" not found
```

**To Reproduce**
1. Go to 'https://github.com/actions-runner-controller/actions-runner-controller#installation'
2. Follow the installation instructions
3. `kubectl describe po controller-manager.... -n actions-runner-system`

**Expected behavior**
Controller manager running and creating runner pods when jobs start

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.18.2]
 - Deployment Method [e.g. Helm and Kubectl ]

**Comment by mumoshu** [comment]
Hey! `kubectl describe po controller-manager.... -n actions-runner-system` doesn't make sense as it `controller-manager` should be the name of secret, where your command is trying to get a pod of that name.

Please create a secret named `controller-manager` in the same namespace as your actions-runner-controller pods are deployed to.

**Comment by nicolasdonoso** [comment]
I did not share the complete pod id in  the example, but it is describing the pod that is complaining about the secret missing. So I have to assume that the installation does not create the `controller-manager` secret and I have to go ahead and create it. If I do this, what values should I store in this secret object?

**Comment by callum-tait-pbx** [comment]
https://github.com/actions-runner-controller/actions-runner-controller#setting-up-authentication-with-github-api it's in the docs, it entirely depends on you
