### ISSUE TITLE
Intermittent permissions errors from multiple GHA runs on self-hosted runners

### ISSUE THREAD

**Issue by jslusher** [actions-runner-controller/actions-runner-controller#720]
**Describe the bug**
On multiple GHA workflow runs, occasionally we see permissions errors when the worker attempts to clean up its `/runner/_work` directory. 

```
2021-08-09T22:15:11.2384401Z [command]/usr/bin/git config --local --get remote.origin.url
2021-08-09T22:15:11.2413148Z https://github.com/org/repo
2021-08-09T22:15:11.2427272Z ##[group]Removing previously created refs, to avoid conflicts
2021-08-09T22:15:11.2431002Z [command]/usr/bin/git rev-parse --symbolic-full-name --verify --quiet HEAD
2021-08-09T22:15:11.2462004Z HEAD
2021-08-09T22:15:11.2472613Z [command]/usr/bin/git rev-parse --symbolic-full-name --branches
2021-08-09T22:15:11.2503865Z ##[endgroup]
2021-08-09T22:15:11.2505886Z ##[group]Cleaning the repository
2021-08-09T22:15:11.2507411Z [command]/usr/bin/git clean -ffdx
2021-08-09T22:15:11.2604862Z warning: failed to remove .pytest_cache/v/cache/stepwise: Permission denied
2021-08-09T22:15:11.2606855Z warning: failed to remove .pytest_cache/v/cache/nodeids: Permission denied
2021-08-09T22:15:11.2608515Z warning: failed to remove .pytest_cache/README.md: Permission denied
2021-08-09T22:15:11.2609874Z warning: failed to remove .pytest_cache/.gitignore: Permission denied
...
2021-08-09T22:15:11.4287979Z ##[endgroup]
2021-08-09T22:15:11.4295434Z ##[warning]Unable to clean or reset the repository. The repository will be recreated instead.
2021-08-09T22:15:11.4310445Z Deleting the contents of '/runner/_work/org/repo'
2021-08-09T22:15:11.4321152Z ##[error]Command failed: rm -rf "/runner/_work/org/repo/.pytest_cache"
rm: cannot remove '/runner/_work/org/repo/.pytest_cache/v/cache/stepwise': Permission denied
rm: cannot remove '/runner/_work/org/repo/.pytest_cache/v/cache/nodeids': Permission denied
...
```
 
**Checks**

- [x ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. Create a self-hosted runner for a repo, preferably one with several jobs 
2. Trigger multiple jobs so they queue up
3. At some point, at least for us, one of the jobs will error, usually on the first step or two, on permissions

**Expected behavior**
I would expect we could queue up these jobs and they would be able to clean themselves without permissions errors.

**Environment (please complete the following information):**
 - Controller Version = 0.18.2
 - Deployment Method = Kustomize

The example I was able to reproduce here mentions being unable to clean up pycache, but I've seen this error in a couple of other plugins, namely the asdf plugin, so we don't think it has anything to do with pycache in particular. We've seen the error in several of our repos also, so it's not isolated to the repo that produced these logs either.

It seems like the runners at times anyway are not restarting with a clean slate. I'm having a heck of a time getting any more information that might be useful, but I will update this if I find out anything else. Please let me know if there's anything you would like me to add to this issue that might help you track down the problem.

**Comment by callum-tait-pbx** [comment]
This is unlikely to be a actions-runner-controller issue, https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging I doubt it but does enabling the debug logs help at all for finding more information? Do you download these files at all via the `actions/download-artifact` action? They do not guarantee permisisons are maintained https://github.com/actions/download-artifact#permission-loss. If you investigate the permisisons on the files e.g. `ls -al` what do they look like?

**Comment by jslusher** [comment]
We don't use `actions/download-artifact` directly. The two most common actions we see the failure are `actions/checkout@v2` and `asdf-vm/actions/install@v1.1.0`, but they are also usually the first two steps that get executed in any of our workflows. The ephemeral nature of the runner pods is making it difficult to get a good look at the failed actions once they happen. I will try adding a `ls -la` step to the test workflow prior to the two aforementioned actions. I will also look into enabling debug logs and I will get back to you with any more information.

**Comment by jslusher** [comment]
I was able to reproduce the permissions error I mentioned that's related to the `asdf-vm` action. I attached a sanitized version of the log output with debug enabled.

```
2021-08-11T18:49:23.6895824Z Cloning asdf into ASDF_DIR: /home/runner/.asdf
2021-08-11T18:49:23.6962088Z [command]/usr/bin/git clone --depth 1 --branch master https://github.com/asdf-vm/asdf.git /home/runner/.asdf
2021-08-11T18:49:23.7027628Z fatal: destination path '/home/runner/.asdf' already exists and is not an empty directory.
2021-08-11T18:49:23.7074810Z ##[error]Action failed with error Error: The process '/usr/bin/git' failed with exit code 128
```

This one seems to be complaining about `/home/runner` and not the main `/runner/_work` directory. Is the `ASDF_DIR` correct there or should I change it to `/runner/_work`? 

I had added a `ls -la /runner/_work` as a step previous to this one, but apparently it's not the directory that's related. Here are some output results of directory permissions after this was run, which means the runners have been reset at this time.

```
kubectl exec -it x k8s-test-runner-lcj26-4vj7h -c runner -- ls -la
total 4
drwxr-xr-x   1 root   root     67 Aug 11 19:17 .
drwxr-xr-x   1 root   root     67 Aug 11 19:17 ..
lrwxrwxrwx   1 root   root      7 Jul 23 17:35 bin -> usr/bin
drwxr-xr-x   2 root   root      6 Apr 15  2020 boot
drwxr-xr-x   3 root   root     20 Aug 11 19:17 certs
drwxr-xr-x   5 root   root    360 Aug 11 19:17 dev
-rwxr-xr-x   1 root   root   3652 Aug 11 15:43 entrypoint.sh
drwxr-xr-x   1 root   root     25 Aug 11 15:45 etc
drwxr-xr-x   1 root   root     20 Aug 11 15:44 home
lrwxrwxrwx   1 root   root      7 Jul 23 17:35 lib -> usr/lib
lrwxrwxrwx   1 root   root      9 Jul 23 17:35 lib32 -> usr/lib32
lrwxrwxrwx   1 root   root      9 Jul 23 17:35 lib64 -> usr/lib64
lrwxrwxrwx   1 root   root     10 Jul 23 17:35 libx32 -> usr/libx32
drwxr-xr-x   2 root   root      6 Jul 23 17:35 media
drwxr-xr-x   2 root   root      6 Jul 23 17:35 mnt
drwxr-xr-x   1 root   root     29 Aug 11 15:45 opt
dr-xr-xr-x 391 root   root      0 Aug 11 19:17 proc
drwx------   2 root   root     37 Jul 23 17:38 root
drwxr-xr-x   1 root   root     21 Aug 11 19:17 run
drwxrwxrwx   8 runner docker  244 Aug 11 19:17 runner
drwxr-xr-x   1 runner docker   21 Aug 11 15:45 runnertmp
lrwxrwxrwx   1 root   root      8 Jul 23 17:35 sbin -> usr/sbin
drwxr-xr-x   2 root   root      6 Jul 23 17:35 srv
dr-xr-xr-x  13 root   root      0 Aug  9 18:45 sys
drwxrwxrwt   1 root   root    128 Aug 11 19:17 tmp
drwxr-xr-x   1 root   root     45 Aug 11 15:44 usr
drwxr-xr-x   1 root   root     41 Jul 23 17:38 var
```

```
kubectl exec -it k8s-test-runner-lcj26-4vj7h -c runner -- ls -la /home/runner
total 12
drwxr-xr-x 1 runner runner   39 Aug 11 19:17 .
drwxr-xr-x 1 root   root     20 Aug 11 15:44 ..
-rw-r--r-- 1 runner runner  220 Aug 11 15:44 .bash_logout
-rw-r--r-- 1 runner runner 3771 Aug 11 15:44 .bashrc
-rw-r--r-- 1 runner runner  807 Aug 11 15:44 .profile
-rw-r--r-- 1 runner runner    0 Aug 11 19:17 .sudo_as_admin_successful
```

```
kubectl exec -it k8s-test-runner-lcj26-4vj7h -c runner -- ls -la /runner/_work
total 0
drwxrwxrwx 2 runner docker   6 Aug 11 19:17 .
drwxrwxrwx 8 runner docker 244 Aug 11 19:17 ..
```

**Comment by toast-gear** [comment]
> The ephemeral nature of the runner pods is making it difficult to get a good look at the failed actions once they happen.

https://github.com/actions-runner-controller/actions-runner-controller#additional-tweaks
You can set `ephemeral: false` in the spec to prevent the pod being restarted which might allow you to investigate further if you can also reproduce the issue

**Comment by jslusher** [comment]
@toast-gear Thanks for the tip! I will try it out. I did end up adding `ls -la /home/runner` as a first step in all my test jobs that use asdf and I was able to verify that on a runner that should have restarted (default configuration `ephemeral: true`), I see that `/home/runner/.asdf` is indeed present on the jobs that end up failing at the asdf step. 

Here's a snippet of the relative parts of the log output that hopefully shows what I mean:
```
2021-08-11T22:12:15.3359378Z ls -la /home/runner
...
2021-08-11T22:12:15.3477389Z total 16
2021-08-11T22:12:15.3478994Z drwxr-xr-x  1 runner runner   52 Aug 11 22:11 .
2021-08-11T22:12:15.3479983Z drwxr-xr-x  1 root   root     20 Aug 11 15:44 ..
2021-08-11T22:12:15.3480953Z drwxr-xr-x 16 runner runner 4096 Aug 11 22:11 .asdf
2021-08-11T22:12:15.3482167Z -rw-r--r--  1 runner runner  220 Aug 11 15:44 .bash_logout
2021-08-11T22:12:15.3483223Z -rw-r--r--  1 runner runner 3771 Aug 11 15:44 .bashrc
2021-08-11T22:12:15.3484275Z -rw-r--r--  1 runner runner  807 Aug 11 15:44 .profile
2021-08-11T22:12:15.3485441Z -rw-r--r--  1 runner runner    0 Aug 11 22:10 .sudo_as_admin_successful
....
2021-08-11T22:12:15.3746395Z ##[group]Run asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa
2021-08-11T22:12:15.3747272Z with:
2021-08-11T22:12:15.3747737Z   asdf_branch: master
...
2021-08-11T22:12:15.4478708Z Cloning asdf into ASDF_DIR: /home/runner/.asdf
2021-08-11T22:12:15.4523228Z [command]/usr/bin/git clone --depth 1 --branch master https://github.com/asdf-vm/asdf.git /home/runner/.asdf
2021-08-11T22:12:15.4577431Z fatal: destination path '/home/runner/.asdf' already exists and is not an empty directory.
2021-08-11T22:12:15.4618160Z ##[error]Action failed with error Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by lucas-pate** [comment]
I have also experienced this issue and found the same results as @jslusher in my attempts to debug it.

**Comment by jslusher** [comment]
@lucas-pate We're currently blocked rolling this out to our teams because of this bug. We have GHA using self-hosted runners for about 98% of our repos, but we have a "monolith" repo that is very involved about 6 separate jobs with every push) and this bug comes up on a regular enough basis that we're holding off until we can hopefully figure out a solution or workaround. One thought we had was to explicitly add a `rm -rf /runner/_work/.` and `rm -rf /home/runner/.asdf` step at the top of each job, but it's not ideal of course.

**Comment by mumoshu** [comment]
Hey! Thanks for reporting.

> I was able to reproduce the permissions error I mentioned that's related to the asdf-vm action. I attached a sanitized version of the log output with debug enabled.

This one doesn't look like a permission error to me. Perhaps that's more like `asdf-vm` action's bug that it doesn't check for the existence of `$HOME/.asdf` before it does its own cache save?

https://github.com/asdf-vm/actions/blob/b797cb8027b273ade6b7701ba2b4ce5fd1d477cb/install/main.js#L1237-L1252

I.e. I think the `asdf-vm` action needs to be fixed so that it checks the existence of the directory referenced by `asdfDir` before committing to run `git clone`.

> This one seems to be complaining about /home/runner and not the main /runner/_work directory. Is the ASDF_DIR correct there or should I change it to /runner/_work?

As I said above, my theory says this is more like a asdf-vm bug 🤔 In other words, I don't have any theory that says changing it to use `/runner` or `/runner/_work` fix the issue.

**Comment by mumoshu** [comment]
For the original issue of permission errors you've encountered, I guess that one of the causes might be due to the instability of `--once` flag. The flag is provided by `actions/runner` and used by `actions-runner-controller` to configure a runner as ephemeral.

And the flag is considered experimental and known to have race issues that it ends up running two or more jobs before terminating even though the expected behavior of an ephemeral runner is to run only one job.

As long as each ephemeral runner runs the job only once, there should be no need to clean `/runner/_work` dir at all.

FWIW, https://github.com/actions-runner-controller/actions-runner-controller/issues/466 is one of outcomes of the race issue. And we, actions-runner-controller maintainers and GitHub, are currently testing the new `--ephemeral` flag as part of https://github.com/actions-runner-controller/actions-runner-controller/issues/697 so that there's no race issue anymore.

**Comment by mumoshu** [comment]
To be clear, I don't think `actions/runner` nor `actions-runner-controller` is responsible for cleaning up `$HOME`. It should be each plugin's responsibility to use $HOME correctly.

Here's where `actions/runner` runs `git clean` and `rm -rf` for a clean up. It looks to target the runner dir only, not $HOME:

https://github.com/actions/runner/blob/be9632302ceef50bfb36ea998cea9c94c75e5d4d/src/Runner.Plugins/Repository/v1.1/GitSourceProvider.cs#L188-L207

**Comment by mumoshu** [comment]
@lucas-pate What were the exact error messages you've encountered?

To me `Permission denied` errors and [asdf errors](https://github.com/actions-runner-controller/actions-runner-controller/issues/720#issuecomment-897209334) are completely different things from completely different sources, and I'm interested in which one you're seeing.

**Comment by lucas-pate** [comment]
I've looked back through the workflows, and I was unable to find the exact error message. I'm sure that mine didn't reference an asdf directory. I'll try to reproduce the issue.

**Comment by jslusher** [comment]
@mumoshu Thank you for the details on the issue. 
>This one doesn't look like a permission error to me. Perhaps that's more like asdf-vm action's bug that it doesn't check for the existence of $HOME/.asdf before it does its own cache save?

Although the error isn't permissions-based exactly, I still think it's caused by the same race condition as the other action's permissions errors. I'm guessing that the asdf-vm action is not accounting for the race condition like the other actions.

>And we, actions-runner-controller maintainers and GitHub, are currently testing the new --ephemeral flag as part of #697 so that there's no race issue anymore.

Do you have any idea when we should expect this fix to be in place? I was thinking of putting a couple of initial steps in my workflows that would remove anything leftover in `/runner/_work` and `/home/runner/` before running the job, but if the race condition will be fixed soon enough I'll just wait. Thanks again!

**Comment by mumoshu** [comment]
@jslusher Hey!

> I'm guessing that the asdf-vm action is not accounting for the race condition like the other actions.

To be clear, I still believe it's a bug in `asdf-vm` action.

`actions/runner` doesn't seem to be responsible for cleaning up `/home/runner` and not all actions use `/home/runner`. It might be the case that only `asdf-vm` in your workflow relies on `/home/runner` and it doesn't handle dirty `/home/runner` gracefully.

> Do you have any idea when we should expect this fix to be in place?

Sry but I don't know. Only the god may know...

My theory is that if you use `ephemeral: false` today, permissions errors on `/runner/_work` might go away, but `asdf-vm` errors on `/home/runner` persists. Then the only workaround you would need would be to clean up `/home/runner` leftovers on each run.

Have you tried

**Comment by callum-tait-pbx** [comment]
> Do you have any idea when we should expect this fix to be in place? I was thinking of putting a couple of initial steps in my workflows that would remove anything leftover in /runner/_work and /home/runner/ before running the job, but if the race condition will be fixed soon enough I'll just wait. Thanks again!

@jslusher FYI I saw the latest comment on https://github.com/actions/runner/pull/660 is saying Septermber. Obviously we're not GitHub employees so we have no idea if they will hit that date or if priorities will shift but that's the expectation they are setting atm.

**Comment by jslusher** [comment]
@mumoshu I tried setting `ephemeral: false` on our test cluster and I haven't been able to reproduce either of the issues I posted here in the earlier comments. This is a little confusing to me because I was under the impression that those issues were being cause by a runner not getting restarted and therefore leaving files behind from previous jobs, and I would assume setting `ephemeral: false` would do the same thing. For my knowledge, can you explain why this might fixed the problem? Also thanks!
