### ISSUE TITLE
Failed to create registration token - 401 Bad credentials

### ISSUE THREAD

**Issue by Jimmyh85** [actions-runner-controller/actions-runner-controller#725]
**Describe the bug**
I am not able to register a new runner for our Github Enterprise Server installation. It always fails with 
`ERROR   controller-runtime.controller   Reconciler error        {"controller": "runner-controller", "request": "actions-runner-system/example-runner", "error": "failed to create registration token: POST https://${GHES-HOSTNAME}/api/v3/repos/runner-test/runner-1/actions/runners/registration-token: 401 Bad credentials []"}`

I can successfully query the same API endpoint with the exact same token, so I wonder what the problem can be. Is there a possibility to log out the request to verify how the token is sent in the request?

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
1. I installed the controller via helm and adjusted the values.yaml accordingly to our GHES installation
2. kubectl apply -f runner.yaml 
3. Runner will be created, but the connection is failing due to the 401 Bad Credentials error

**Expected behavior**
The runner can be created successfully.

**Environment (please complete the following information):**
 - Github Enterprise Server 3.1.4
 - Controller Version [0.19.0]
 - Deployment Method [Helm]
 - Helm Chart Version [0.12.7]

**Comment by Jimmyh85** [comment]
Thank you @mumoshu , I think I already tried all variations of adding the password (bas64 encoded, not encoded, created with 'echo -n' and just 'echo'. But all failing so far. Can I somehow see the actual request that is sent over to GitHub? Unfortunately, it seems that on the GitHub enterprise server the logs to not include the request headers...

**Comment by mumoshu** [comment]
@Jimmyh85 I have not tried that, but it should be possible by tweaking HTTP or GitHub API client in our Go code, build a container image, and deploying it.

A more easy way to see the actual token passed to the controller would be to `kubectl exec -it` into the controller pod and run `echo $GITHUB_TOKEN`, assuming you've used the Helm chart for deployment / you used that envvar to give the token to the controller.

https://github.com/actions-runner-controller/actions-runner-controller/blob/dc9f9b0bfb512009fab75f2e524749793da3c8a8/charts/actions-runner-controller/templates/deployment.yaml#L63

**Comment by Jimmyh85** [comment]
Hello @mumoshu , I was unable to exec into the controller pod. I am not sure if this is related to my setup here at work (Windows environment... or if the Pod does not contain an interactive shell), however I could solve the issue: The controller pod did not consume the updated token secret until it got restarted...After a restart, everything is working for the moment. Thank you for your help!

**Comment by mumoshu** [comment]
> I could solve the issue: The controller pod did not consume the updated token secret until it got restarted

@Jimmyh85 Ah, that makes sense! That's how an envvar set from a secret works on Kubernetes. Kubernetes doesn't automatically restart pods and containers to load new secret value into an envvar, nor it doesn't reset the envvar while the pod is running.
