### ISSUE TITLE
Disable autoscaling if no `metrics` are supplied

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#728]
**Current Behaviour**
If no `metric` is provided in the HRA (`HorizontalRunnerAutoscaler`) kind then it defaults to applying the `TotalNumberOfQueuedAndInProgressWorkflowRuns` scaling metric logic

**Suggestion**
If no `metric` is provided in the HRA then no attempt is made to perform any autoscale activity other than those defined in the scheduled overrides configuration

**Rationale**
The original behaviour of applying a default metric was helpful as it meant you could deploy HRAs with less knowledge making it easier for the end user as well as reducing the amount of yaml in a manifest. Additionally, the project original only had a single scaling metric (`TotalNumberOfQueuedAndInProgressWorkflowRuns`) and so it made sense to just apply it by default.

Since this original logic was implemented the project has added support for scheduled overrides of the replica counts. The scheduled overrides feature allows you to adjust the min / max replica count of a `RunnerDeployment` based on a schedule. One use case (and I suspect a common one) of this feature is scaling replica counts down to 0 outside of a time range such as core business hours, this then allows you to scale the underlying node group down to 0 saving you £££££.

If you are attempting to save money by scaling down your nodes but not by scaling up because you can't save money scaling up due to how your cluster is setup then will want to deploy a `RunnerDeployment` with a min / max replica count set to the same value and back it with a HRA to take advantage of the scheduled override feature. With the current behaviour the controller will make API calls, consuming API calls (which are rate limited) unnecessarily as you are using the HRA more like a schedular than an autoscaler.

Seen as this is a breaking change to the default behaviour if anyone has any concerns please do highlight on this issue, additionally, you may want to add a metrics to all your HRAs now to prevent issues post upgrading.

**Comment by mumoshu** [comment]
Implemented in #1372
