### ISSUE TITLE
Question - Is it possible to not have self-hosted label?

### ISSUE THREAD

**Issue by vikas027** [actions-runner-controller/actions-runner-controller#737]
I have followed the instructions and everything is working out great for me :) .

The only thing I am looking to change is the default label `self-hosted`, is it a way to do the same? My use case is that if someone (in the organization) is already using a label `self-hosted` in their workflows, it would land on my runners which I am trying to avoid.

**Comment by mumoshu** [comment]
Hey! That's not possible. You should create a feature request against GitHub.
