### ISSUE TITLE
Unable to pass dnsConfig to self-hosted autoscaling runners

### ISSUE THREAD

**Issue by sammcj** [actions-runner-controller/actions-runner-controller#761]
I'm trying to set `dnsConfig` on the self-hosted autoscaling runner deployments.

Apologies if I'm simply trying to set it in the wrong place - I'm new to helm and very new to Actions.

**Checks**

- [?] My actions-runner-controller version (v0.12.7) does support the feature
- [-] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

I followed [actions-runner-controller.md](https://github.com/actions-runner-controller/actions-runner-controller#autoscaling), using helm for the controller and deploying the runners via a simple kubernetes deployment manifest.

Which errors as it can't find RunnerDeployment.spec.template.spec.dnsConfig:

```
error: error validating "runnerdeployment.yaml": error validating data: ValidationError(RunnerDeployment.spec.template.spec): unknown field "dnsConfig" in dev.summerwind.actions.v1alpha1.RunnerDeployment.spec.template.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

1. Deploy the self-hosted runner controller using the provided helm chart.
2. Create a deployment.yaml similar to those supplied in [actions-runner-controller.md](https://github.com/actions-runner-controller/actions-runner-controller#autoscaling).
3. Add `dnsConfig` to the deployment.yaml and apply.
4. Try applying the deployment.
5. Experience error above as the CRD doesn't accept `RunnerDeployment.spec.template.spec.dnsConfig`

**Expected behavior**

The following k8s deployment manifest (or similar) to work:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-runner-deployment
spec:
  template:
    spec:
      dnsConfig:
        options:
        - name: ndots     
          value: "1"
```

and from that `dnsConfig` should be passed to runner pods which configures /etc/resolv.conf inside containers with the provided options.

**Environment:**
 - Controller Version - 0.19.0
 - Deployment Method - Helm
 - Helm Chart Version - v0.12.7

**Additional Context:**

The reason I'm needing to configure this is because it seems with DIND (or really Docker in ContainerD) some base images (such as alpine) incorrectly get `ndots:5` configured in `/etc/resolv.conf` which causes DNS lookup failures inside the container.

[information on what ndots is](https://www.reddit.com/r/kubernetes/comments/duj86x/help_understanding_how_dns_works_and_what_ndots/f76k3hc/?utm_source=reddit&utm_medium=web2x&context=3)

**Comment by mumoshu** [comment]
@sammcj Hey! This sounds like a valid feature request. Would you mind submitting a PR like https://github.com/actions-runner-controller/actions-runner-controller/pull/628 to add the additional pod template field support for Runner and RunnerDeployment resources?

You can also try RunnerSet which is still an unreleased feature, if you could try building a custom build of actions-runner-controller from `master` branch.

https://github.com/actions-runner-controller/actions-runner-controller#stateful-runners

RunnerSets supports any pod template fields out of the box.

**Comment by callum-tait-pbx** [comment]
@sammcj FYI https://github.com/rewanthtammana/kubectl-fields this plugin is super helpful for checking if a attribute is part of your deployed CRD set, for example here what it found for the `limits` attribute:

```
$ kubectl fields runnerdeployment limits

spec.template.spec.dockerdContainerResources.limits
spec.template.spec.resources.limits
spec.template.spec.volumes.ephemeral.volumeClaimTemplate.spec.resources.limits

```

**Comment by sammcj** [comment]
Thanks for confirming this isn't currently possible @mumoshu, I'll submit a PR!

**Comment by sammcj** [comment]
@callum-tait-pbx that looks really useful! Thank you!

**Comment by sammcj** [comment]
@mumoshu - Initial crack at it: https://github.com/actions-runner-controller/actions-runner-controller/pull/764

I've almost certainly missed a few things and the local test suite takes over 40 mins to run which made experimentation a little difficult - I'm hoping Github Actions workflow for PRs has the same coverage.
