### ISSUE TITLE
Runners crashing frequently with CrashLoopBackOff

### ISSUE THREAD

**Issue by azizzoaib786** [actions-runner-controller/actions-runner-controller#770]
**Describe the bug**

Suddenly GitHub Runners containers starts to crash with below errors and keeps in CrashLoopBackOff.

And when we update the runner with the latest release it gets fixed but after sometime it starts throwing same error.

```mv: inter-device move failed: './externalstmp/node12' to './externals/node12'; unable to remove target: Directory not empty```
```mv: inter-device move failed: './externalstmp/node12_alpine' to './externals/node12_alpine'; unable to remove target: Directory not empty```

**Checks**

- [x] My actions-runner-controller version (2.280.3) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**Environment (please complete the following information):**
 - Controller Version [2.280.3]
 - Deployment Method [Helm]

**Comment by toast-gear** [comment]
> @mumoshu not sure if we are using actions-runner-controller in our case, what we are using is simple GitHub runner from here by building our custom docker image.

We aren't GitHub employees, we maintain the project `actions-runner-controller`, we aren't maintainers of the Actions product. If you have issues you need to reach out to to GitHub managed locations like their forum or repositories like `actions/runner`
