### ISSUE TITLE
Authenticate to docker registry without hardcoding credentials

### ISSUE THREAD

**Issue by vikas027** [actions-runner-controller/actions-runner-controller#781]
_**Is your feature request related to a problem? Please describe.**_

My goal is to authenticate to ECR credentials without having AWS Access keys as GitHub Secrets as suggested [actions/aws-ecr-docker-login](https://github.com/marketplace/actions/aws-ecr-docker-login) or [aws-actions/amazon-ecr-login](https://github.com/aws-actions/amazon-ecr-login). I am using [IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) and my pod has permission to get temporary credentials.
I know I can limit what the AWS access keys can do but will have an overhead of managing and rotating these keys outside of kubernetes which I want to avoid.

_**Describe the solution you'd like**_

In order to achieve the above, I think I have two options. I have looked around but these are not possible as of now, am I right?

1. Create a docker secret (and keep rotating it using a Cronjob) and mount it on the container at `$HOME/.docker/config.json`
2. (my preference) Run a command like below (to generate `$HOME/.docker/config.json`) when the container of image `docker:dind` or a [custom image](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/values.yaml#L35) which has `aws` CLI installed.
```
$ aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 11111111.dkr.ecr.us-east-1.amazonaws.com
```

_**Describe alternatives you've considered**_
Add `aws-cli` to the official `docker:dind` image and modify the entrypoint script to populate `$HOME/.docker/config.json` and then use the same in [values.yaml](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/values.yaml#L35)

**Comment by mumoshu** [comment]
@vikas027 Hey! AFAIK docker credentials must be saved in the environment that runs `docker` command, not daemon. So The number 1 would be the only viable option.

See https://github.com/actions-runner-controller/actions-runner-controller/issues/474#issuecomment-824959191 - Although I have never tried that myself, you'd need to build a custom runner image(not a custom dind image).

**Comment by vikas027** [comment]
> AFAIK docker credentials must be saved in the environment that runs `docker` command, not daemon

Yeah, you are right. I am using a custom image and have tried hacking around the entrypoint scripts but looks like it ignores the `~/.docker/config.json` :( 

I took a hint from [here](https://github.com/aws-actions/amazon-ecr-login/issues/147) and have used [awslabs/amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper). It works fine with IRSA.

**Comment by mumoshu** [comment]
@vikas027 Thanks for confirming!

> ignores the ~/.docker/config.json

Oh, that's odd! Perhaps you missed the homedir, or have a better result by specifying the exact path to the config file via this envvar https://docs.docker.com/engine/reference/commandline/cli/#change-the-docker-directory

Good to know that `awslabs/amazon-ecr-credential-helper` works with IRSA. Thanks for sharing ☺️

**Comment by vikas027** [comment]
> Oh, that's odd! Perhaps you missed the homedir

Hmm, I know about this variable but I thought all commands will be run as `runner` user and I had created the file at `/home/runner/.docker/config.json`. Now, when I think a bit deeper, I don't quite like that workaround/solution as the temporary docker auth will expire after a few hours which can be a problem for any runner which has been idle for some time.

**Comment by dolphyns** [comment]
Hi. 

It might not be applicable here but I echo the Certificate PK to the proper folder (CA Root) inside the container so the SSH should work seamlessly.  I did that for my GitLab Pipeline and works like a charm. I don't know if you can do the same with AWS... hope it helps.
