### ISSUE TITLE
flag provided but not defined: -docker-registry-mirror

### ISSUE THREAD

**Issue by peimanja** [actions-runner-controller/actions-runner-controller#789]
**Describe the bug**
When providing `dockerRegistryMirror` to the latest helm chart, controller pod goes into `CrashLoopBackOff` with this error:
```
flag provided but not defined: -docker-registry-mirror
```

**Checks**

- [] My actions-runner-controller version (v0.19.0) does support the feature
- [] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**
Deploy the controller using latest helm chart (0.12.8) and set `dockerRegistryMirror: https://mirror.gcr.io/`

**Expected behavior**
Controller come up successfully with `--docker-registry-mirror=https://mirror.gcr.io/` in the arguments

**Environment (please complete the following information):**
 - Controller Version [v0.19.0]
 - Deployment Method [Helm]
 - Helm Chart Version [0.12.8]

**Comment by peimanja** [comment]
Shortly after posted this, I set the controller image tag to `canary` and that resolved the issue.

Is this expected to support this in the helm chart while the latest version of controller that is set in the chart does not support it?

Is the new version of the controller will be released soon supporting this feature? Don’t really feel comfortable running our production system on `canary` version.

**Comment by toast-gear** [comment]
Definately don't run a production system on the `canary` version, it breaks often as it's a continously updated test image.

Are you sure the controller container you were previously running was v0.19.0? The chart should default to v0.19.0 if no version was provided with chart version 12.8, can confirm with no version specified that your controller version does default to v0.19.0?

**Comment by peimanja** [comment]
@toast-gear yes, just double checked to confirm the controller image version and it's `summerwind/actions-runner-controller:v0.19.0`.

Looking at [images in Docker hub](https://hub.docker.com/r/summerwind/actions-runner-controller/tags?page=1&ordering=last_updated) looks like it was built 3 months ago while this feature was added in https://github.com/actions-runner-controller/actions-runner-controller/pull/689 about 2 months ago.

**Comment by toast-gear** [comment]
Ah apologies, I was mixing this up with the runner dind registry option, yes this isn't part of a release yet, you can see it isn't implemented in the v0.19.0 image by going to that release and viewing the main.go at that commit https://github.com/actions-runner-controller/actions-runner-controller/blob/v0.19.0/main.go

I'll close this as there isn't an issue, we are aiming to release a new version soon. In the mean time you use the runner level docker registry configuration, see release for details https://github.com/actions-runner-controller/actions-runner-controller/releases/tag/v0.19.0
