### ISSUE TITLE
dind pods are not getting created

### ISSUE THREAD

**Issue by ayush-c-gupta-db** [actions-runner-controller/actions-runner-controller#790]
After running this command, pods are not getting created, nothing is happening

ayush_gupta@operations-vm-v9wc-uat:~/build-runners-gke/dind$ kubectl apply -f runner_deployment.yaml
runnerdeployment.actions.summerwind.dev/runnerdeploy configured.

runner_deployment.yaml

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runnerdeploy
spec:
  replicas: 5
  template:
    spec:
      labels:
        - dbguat_docker
      runnergroup: DBGDEV
      image: gcr.io/db-ctl-rymz-runners/actions-runner-dind:31.08
      dockerdWithinRunnerContainer: true
      resources:
        limits:
          cpu: "4000m"
          memory: "2Gi"
        requests:
          cpu: "200m"
          memory: "200Mi"
      volumeMounts:
      - mountPath: /runner
        name: runner
      volumes:
      - name: runner
        emptyDir: {}

below secretshave been installed
 kubectl get secrets -n actions-runner-system
NAME                  TYPE                                  DATA   AGE
controller-manager    Opaque                                1      83d
default-token-cq2sr   kubernetes.io/service-account-token   3      83d
webhook-server-cert   kubernetes.io/tls                     3      83d

**Comment by mumoshu** [comment]
@ayush-c-gupta-db If you think it's a bug, could you please fill in the default issue template we provide, so that we can better trouble-shoot your issue? Otherwise please use Discussions for Q&A. Thanks for your cooperation!
