### ISSUE TITLE
How to bypass ssl certificate check  in GHE enterprise with internal certificate 

### ISSUE THREAD

**Issue by roshvin** [actions-runner-controller/actions-runner-controller#791]
**Is your feature request related to a problem? Please describe.**
Our GHE enterprise uses internal certificate and this controller giving error connecting . is there any way to bypass ssl check for testing. 

**Describe the solution you'd like**
How to skip GHE ssl certification or copy internal certificate to controller container path 

**Describe alternatives you've considered**

**Additional context**

**Comment by mumoshu** [comment]
@roshvin I hope the below issue and other issues from folks suffered from the same thing would help :)

https://github.com/actions-runner-controller/actions-runner-controller/issues/712#issuecomment-892242319
