### ISSUE TITLE
Runner configuration is failing

### ISSUE THREAD

**Issue by inidzelsky** [actions-runner-controller/actions-runner-controller#793]
**Describe the bug**
Trying to up organization runner with dind. Runner can't authenticate to github with configuration errors. Everything works good without dind. I tried to change different actions-runner-controller and summerwind/actions-runner-dind versions, but nothing helped. I found out that pod doesn't have connection to the Internet at all (ping does not work)

**Environment**
- actions-runner-controller target revision: actions-runner-controller-0.12.8
- dind image: summerwind/actions-runner-dind:latest
- cert-manager: v1.5.3

<img width="979" alt="Screenshot 2021-09-07 at 16 09 49" src="https://user-images.githubusercontent.com/53613557/132350250-c72469d2-e8f0-4605-8d6a-379d7a2be8eb.png">

Runner spec: 

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
&nbsp;namespace: default
&nbsp;name: github-actions-runner
spec:
&nbsp;template:
&nbsp;&nbsp;spec:
&nbsp;&nbsp;&nbsp;dockerdWithinRunnerContainer: true
&nbsp;&nbsp;&nbsp;image: summerwind/actions-runner-dind:latest
&nbsp;&nbsp;&nbsp;organization: my-organization

**Comment by mumoshu** [comment]
@inidzelsky Hey!

> I found out that pod doesn't have connection to the Internet at all (ping does not work)

This seems to imply that some sort of security is blocking the internet access, or your CNI or service mesh sidecar proxies are doing something wrong.

In other words, technically actions-runner-controller alone can't make it happen alone. It should rather be due to the nature of your cluster.

**Comment by toast-gear** [comment]
We don't do anything to prevent a runner from communicating with the internet, this is a cluster configuration issue. You will need to contact your cluster administrators to find the root cause.
