### ISSUE TITLE
Update documentation about unreleased features

### ISSUE THREAD

**Issue by abatilo** [actions-runner-controller/actions-runner-controller#833]
https://github.blog/changelog/2021-09-20-github-actions-ephemeral-self-hosted-runners-new-webhooks-for-auto-scaling/

Ephemeral workers and `workflow_job` auto scaling have been released so it would be amazing if the documentation could be updated to account for that.

**Comment by pratikbalar** [comment]
+1

**Comment by mumoshu** [comment]
@abatilo @pratikbalar What do you need other than the sections I've added to the doc for v0.20.0 release?

https://github.com/actions-runner-controller/actions-runner-controller/releases/tag/v0.20.0

<img width="921" alt="CleanShot 2021-09-22 at 14 04 02@2x" src="https://user-images.githubusercontent.com/22009/134286285-39b1d9ed-3146-4fd4-860d-ae22f30d7967.png">

https://github.com/actions-runner-controller/actions-runner-controller#ephemeral-runners
https://github.com/actions-runner-controller/actions-runner-controller#example-3-scale-on-each-workflow_job-event

**Comment by pratikbalar** [comment]
Ahh, just checked link in release section @mumoshu  apologies
