### ISSUE TITLE
Is there a way to change dind image to self-hosted?

### ISSUE THREAD

**Issue by nicon89** [actions-runner-controller/actions-runner-controller#846]
**Is your feature request related to a problem? Please describe.**
I can't find a way to change dind image using "kubectl deployment".
I know it's possible using helm deployment in values: image.dindSidecarRepositoryAndTag.
Can you advise?

**Comment by toast-gear** [comment]
https://github.com/actions-runner-controller/actions-runner-controller/blob/40c88eb49086bfee0ae8585d024c9f590a3aeff2/charts/actions-runner-controller/templates/deployment.yaml#L47 just replicate what the Helm chart is doing if you provide that tag, use the `--docker-image` flag

**Comment by nicon89** [comment]
Thank you!
