### ISSUE TITLE
Support mulit-arch images

### ISSUE THREAD

**Issue by xUnholy** [actions-runner-controller/actions-runner-controller#85]
# Description

It would be great to support arm64 architecture using docker buildx.

I am more than happy to assist with this as a core maintainer in https://github.com/raspbernetes/multi-arch-images/

However, if this is something you do not wish to support let me know.

**Comment by xUnholy** [comment]
I did tweak a few things, I ended up hard-coding some to just trial it and get it working but 75% of the work is done in this PR https://github.com/xUnholy/actions-runner-controller/pull/1/files I'll wait to hear if this is a feature worth investing in for others.

**Comment by mumoshu** [comment]
@xUnholy Hey! Thanks for sharing. This sounds like a great addition to the project 😃 

I've reviewed it a bit with [`?w=1`](https://github.com/xUnholy/actions-runner-controller/pull/1/files?w=1) to suppress diff on many indentation changes and it LGTM in general. Probably reverting indentation changes and changing variable names like `TARGETPLATFORM` to just `PLATFORM`(as we don't currently prefix `ARCH` like `TARGETARCH`) then it's more likely to be merged earlier.

@summerwind WDYT?

**Comment by xUnholy** [comment]
Just to clarify `TARGETPLATFORM` is a key word for docker `buildx` functionality, it is something you don't pass in the traditional sense however is from the `--platform` arg of `buildx`.

Indentation isn't an issue, happy to have as many spaces/tabs you guys prefer, my linter saw inconsistency and auto-repaired it so wasn't a conscious effort.

Where I've hard-coded was the runner/Dockerfile although we'd just need to tweak it to be a conditional statement, probably not a lot of effort. I also updated the image you use to  `image: quay.io/brancz/kube-rbac-proxy:v0.6.0` this variant seems more updated and also supports multi-arch already.

**Comment by mumoshu** [comment]
The link in the corresponding PR was wrong. This has been addressed by #86. Thanks again for your contribution @xUnholy 😃
