### ISSUE TITLE
Enable Fetching and Installing Latest Runner Software On Container Start

### ISSUE THREAD

**Issue by toast-gear** [actions-runner-controller/actions-runner-controller#888]
**Current Behaviour**
We provide a few runner images of which only the `latest` tag is continously updated to have the latest runner software in it automatically whilst retaining the same tag. There is no ability to pull in an alternative runner software version in any image.

**Suggestion**
Produce a solution to allow an end user to download and install the latest version of the runner software on container startup and use the baked in version as a fallback should this process fail.

**Rationale**
Containers don't always play with the self-update process, additionally, it's not ideal having to reference a public container (`latest`) from a community maintained open source project to always stay on the latest runner software. By providing an alternative bootstrap process enabled via a feature flag people can mitigate the self-update issues without the need to either constantly sync `latest` to their registry or have to rely on our image.

Furthermore, if you run a custom runner image you currently have to provide some solution for automatically pushing out a new version of your image when our image gets bumped.

Issues to Resolve:
1. If we call the GitHub release API every container restart we'll very quickly consume the 5000 authenticated API calls / hour rate-limit on even semi busy environments. Calls will need to be cached (to a configurable period) probably by sending them through a Go HTTP proxy sidecar implementation instead of going directly to Github.
2. Perhaps in addition we could allow a "pre-install" script to be ran in the container entrypoint a bit like philips-labs does for their user-data https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/templates/user-data.sh#L4. This would enable people to then implement their own solutions to the problem such as syncing the binaries to an S3 bucket and having their containers get the binary from an S3 bucket instead avoiding the rate-limit issue to begin with.

**Comment by toast-gear** [comment]
https://github.com/actions/runner/issues/1396#issuecomment-983783264 this is probably not going to be needed in the new year 🎉

**Comment by mumoshu** [comment]
Great news!
