### ISSUE TITLE
Autoscaling is lacking Actions permission by default

### ISSUE THREAD

**Issue by stackdumper** [actions-runner-controller/actions-runner-controller#90]
### The problem
The `"Create GitHub Apps on your account/organization"` link in the [readme](https://github.com/summerwind/actions-runner-controller#using-github-app) doesn't enable "Actions" permission by default.
```
https://github.com/settings/apps/new?url=http://github.com/summerwind/actions-runner-controller&webhook_active=false&public=false&administration=write
```

This results in `"403 Resource not accessible by integration"` once the autoscaling is enabled because the autoscaler tries to reach out to GitHub Actions API (`https://api.github.com/repos/rotten-tech/fs-api/actions/runs`).
```
2020-08-21T15:43:16.819Z  ERROR  controllers.HorizontalRunnerAutoscaler  Could not compute replicas

{
  "horizontalrunnerautoscaler": "actions-runner-system/actions-runner-actions-runner-deployment-autoscaler",
  "error": "GET https://api.github.com/repos/rotten-tech/fs-api/actions/runs: 403 Resource not accessible by integration []"
}

github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/summerwind/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerReconciler).Reconcile
	/workspace/controllers/horizontalrunnerautoscaler_controller.go:85
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
```

### Possible solutions
1. Enable "Actions" repository permission by default in the "Create GitHub Apps for your account/organization" link.
2. Add a section to the readme that describes the need to add "Actions" permission if autoscaling is enabled. 

**I would be happy to provide a pull request with a resolution of the described problem.**
<br>

---

P.S: Thank you for your work on the actions-runner-controller. You saved me a lot of money after I ran out of free minutes on the 10th day of the month, and allowed me to test my application in the VPC without a need to connect to VPN from GitHub-hosted runners.

**Comment by callum-tait-pbx** [comment]
@stackdumper thanks for posting this, it solved 1 of my issues, I'm currently still struggling with the ASG aspect of this though, can you share your yaml you have deployed for auto scaling to work?

**Comment by callum-tait-pbx** [comment]
I think the below PRs will resolve this issue, it can be closed once they are merged?
https://github.com/summerwind/actions-runner-controller/pull/180
https://github.com/summerwind/actions-runner-controller/pull/180
