### ISSUE TITLE
condense `r.GitHubClient.ListRunners(ctx, enterprise, org, repo)` calls into a single call/cache

### ISSUE THREAD

**Issue by jbkc85** [actions-runner-controller/actions-runner-controller#920]
**Is your feature request related to a problem? Please describe.**
The feature is related to a problem as it comes to GitHub API calls.  There are multiple instances in which the GitHubClient.ListRunners is called and returns potentially 100 runner statuses via the API, but as I can tell none of this is shared and rather than using the same response for checking various runners, the call is made recursively through the looping of each runner.  This means for each runner, the API is hit N*N times depending on various stages of the runner life cycle.

**Describe the solution you'd like**
The solution would be along the lines of storing the runners statuses every minute (perhaps?) or at a various time span that aligns with registration checks, unregistration attempts, etc.  Unless I am misunderstanding the behavior, I do not believe there has to be a specific reason why its called more than once per cycle.

**Describe alternatives you've considered**
N/A

**Additional context**
When running 100+ runners to sustain a workload, this call eventually eats through the API limit and kills all the runners.  I believe it is one of the main culprits.

**Comment by mumoshu** [comment]
@sledigabel Thanks for the compliment!

Yeah, an in-memory time-based cache would work. I believe the most called APIs various flavors of "List Runners" API so the potential implementation of it could be added to:

https://github.com/actions-runner-controller/actions-runner-controller/blob/f7e14e06e87961a67f46e22cc33ba2c707b6e682/github/github.go#L214-L222

**Comment by jbkc85** [comment]
https://github.com/actions-runner-controller/actions-runner-controller/pull/997

I do apologize for this PR likely not being in the contribution feed back...I wanted to share the progress and see what you all thought.

**Comment by jbkc85** [comment]
also a side note here: Why isn't the GitHub API status pulled from GitHub and stored w/in the Runner's CRD?  I can imagine that we only need 1 call to the GitHub API per minute to list all runners, in which will update the `Status:` of an individual runner pod....that will eliminate a *ton* of GitHub Runner API calls.

**Comment by mumoshu** [comment]
> Why isn't the GitHub API status pulled from GitHub and stored w/in the Runner's CRD?

@jbkc85 I believe it's k8s custom controller convention to not use resource status for cache. It's for reflecting the source of truth, not for storing the source data or cache.

**Comment by mumoshu** [comment]
Linking #1101 from @Djiit

**Comment by Djiit** [comment]
Thanks for the quick reply. Can we help on #997 ? Happy to have a sync anytime [when our timezones crosses].

**Comment by mumoshu** [comment]
@Djiit If you could submit a working example of an alternative approach for comparison, that would be great!

I'm currently trying to come up with a more transparent approach than #997, that might work like "cache any HTTP GET requests for up to X seconds", so that we can universally cache any API calls we can cache.

**Comment by sledigabel** [comment]
Hi @mumoshu, that would be far better indeed, but is this possible? IIRC the underlying HTTP calls are obfuscated by the GH client? It would have to be pretty selective too as some calls would prob not benefit from being cached (like registration/deregistration, if it fails it needs to be retried etc).

**Comment by mumoshu** [comment]
@sledigabel I suppose GitHub has properly designed their APIs to use HTTP GET for "read" requests and POST and PUT for other "write" APIs. I remember the registration/deregistration APIs, for example, were using POST and DELETE respectively. I'd definitely avoid caching POST and DELETE APIs!

**Comment by Djiit** [comment]
I can confirm the preferred way would be to use httpcache at the transport level (see [this](https://github.com/google/go-github#conditional-requests)) on the go-github client repo. Just now in our team, @tdelaune did a small experiment and was able to run some test with a small cache added.

**Comment by Djiit** [comment]
If it can help some others: https://github.com/actions-runner-controller/actions-runner-controller/pull/1103

**Comment by Izzette** [comment]
@jbkc85 that sounds really similar to what we saw as well when debugging, ListRunner and IsRunnerBusy polling is eating the quota.

**Comment by jbkc85** [comment]
just for documentation, I have added my code up here: https://github.com/INNOSOLProject/actions-runner-controller/pull/1.  It seems to be working just fine, and is a good MVP going forward I think.

**Comment by toast-gear** [comment]
This can be considered done now that we have implemented caching.
