### ISSUE TITLE
GitHub AE Support

### ISSUE THREAD

**Issue by tashtechs** [actions-runner-controller/actions-runner-controller#930]
Is this compatible with Github AE runners? Can the Github Enterprise variable be set with a github.us URL? or is there other customizations that need to be made?

**Comment by mumoshu** [comment]
@tashtechs I don't have any knowledge or experience on GitHub AE but if it's just a variant of GHES, yes you should be able to use it as we already support GHES https://github.com/actions-runner-controller/actions-runner-controller#github-enterprise-support

**Comment by mumoshu** [comment]
It would be great if you could give it a try and come back with any concrete question (if any)!
