### ISSUE TITLE
The helm command for webhook installation is not working. Fails with - helm upgrade requires 2 arguments. I have tried multiple ways to run this but fails everytime.

### ISSUE THREAD

**Issue by sing011** [actions-runner-controller/actions-runner-controller#935]
Diff versions I have used with the corresponding errors -

1. helm upgrade --install  actions-runner-controller actions-runner-controller/actions-runner-controller \
  githubWebhookServer.enabled=true \
  githubWebhookServer.ports[0].nodePort=33080

Error: "helm upgrade" requires 2 arguments
Usage:  helm upgrade [RELEASE] [CHART] [flags]

2. helm --upgrade install actions-runner-controller/actions-runner-controller \
  githubWebhookServer.enabled=true \
  githubWebhookServer.ports[0].nodePort=33080

Error: unknown command "actions-runner-controller/actions-runner-controller" for "helm"

3. helm upgrade --install actions-runner-controller/actions-runner-controller \
  githubWebhookServer.enabled=true \
  githubWebhookServer.ports[0].nodePort=33080

Error: "helm upgrade" requires 2 arguments
Usage:  helm upgrade [RELEASE] [CHART] [flags]

**Comment by toast-gear** [comment]
the usage says:

```
 Usage: helm upgrade [RELEASE] [CHART] [flags]
```

You aren't giving your install a release name? Try:

```
helm upgrade actions-runner-controller actions-runner-controller/actions-runner-controller --install --set githubWebhookServer.enabled=true --set githubWebhookServer.ports[0].nodePort=33080
```

**Comment by sing011** [comment]
Thanks for the quick response. It worked. Had to add additional flag for namespace to your command.
