### ISSUE TITLE
pods are not starting with latest summerwind/actions-runner:latest image 

### ISSUE THREAD

**Issue by roshvin** [actions-runner-controller/actions-runner-controller#940]
**Describe the bug**
pods are not starting with latest summerwind/actions-runner:latest image 

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

**Expected behavior**

**Screenshots**
Warning  Failed     109s (x4 over 2m32s)  kubelet            Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/manager": stat /manager: no such file or directory: unknown
  Warning  BackOff    70s (x8 over 2m30s)   kubelet            Back-off restarting failed container

 Warning  Failed     83s (x4 over 2m8s)  kubelet            Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/github-webhook-server": stat /github-webhook-server: no such file or directory: unknown

**Environment (please complete the following information):**
 - Controller Version [e.g. 0.14.0]
 - Deployment Method [e.g. Helm and Kustomize ]
 - Helm Chart Version [e.g. 0.14.0, if applicable]

github-actions-runner   github-actions-runner   15              2021-11-11 10:56:17.078305412 +0530 IST deployed        actions-runner-controller-0.14.0        0.20.2

**Additional context**

**Comment by mumoshu** [comment]
@roshvin You seem to be using an incorrect image? You mentioned `summerwind/actions-runner:latest`, but that's for runners, not for actions-runner-controller.

Would you mind trying it with `summerwind/actions-runner-controller:v0.20.3`?

**Comment by roshvin** [comment]
@mumoshu thanks a lot for your quick replay . 
its working with summerwind/actions-runner-controller:v0.20.3 
i was referring to https://github.com/actions-runner-controller/actions-runner-controller/blob/master/charts/actions-runner-controller/values.yaml and got it wrongly.
i normally download and use the image from our image registry.  is there any way i can fine the latest image tag some where so that i can download the latest each time.

**Comment by mumoshu** [comment]
@roshvin I'd say you should refer to the latest release tag listed in https://github.com/actions-runner-controller/actions-runner-controller/releases :)
What else can we help?

**Comment by roshvin** [comment]
@mumoshu Thank you so much for your quick . now i am set  to know the latest tag path and update our GHE infra  based on the release .
