### ISSUE TITLE
Unable to get runners to register using GHES 3.3rc1

### ISSUE THREAD

**Issue by casanova-21** [actions-runner-controller/actions-runner-controller#949]
**Describe the bug**
I'm attempting to deploy this using EKS in AWS and a GHES 3.3rc1 instance. I can see in the actions-runner-controller log that it's unable to update the registration token.

Relevant log output from the actions-runner-controller pod:
`2021-11-15T22:29:03.500Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"Runner","namespace":"default","name":"k8s-runner-deployment-2kxgw-6r6g2","uid":"7d84ab88-c111-459b-abb2-b46350239a9c","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"60543"}, "reason": "FailedUpdateRegistrationToken", "message": "Updating registration token failed"}
2021-11-15T22:34:31.198Z	ERROR	actions-runner-controller.runner	Failed to get new registration token	{"runner": "k8s-runner-deployment-2kxgw-6r6g2", "error": "failed to create registration token: Post \"https://ec2-3-238-43-81.compute-1.amazonaws.com/api/v3/orgs/harkonnens/actions/runners/registration-token\": x509: certificate signed by unknown authority"}
github.com/actions-runner-controller/actions-runner-controller/controllers.(*RunnerReconciler).Reconcile
	/workspace/controllers/runner_controller.go:189
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214`

**Checks**

- [ ] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

1. Launch GHES 3.3.rc1 instance.
2. Create test org in GHES
3. Launch EKS cluster in AWS.
4. Enable Actions in the GHE instance and then create the PAT with the appropriate scope.
5. Install cert-manager in EKS cluster.
6. Create actions-runner-system namespace.
7. Create secret for controller-manager with the PAT value.
8. helm upgrade --install -f values.yml --namespace actions-runner-system --wait actions-runner-controller actions-runner-controller/actions-runner-controller
9. kubectl set env deploy actions-runner-controller -c manager GITHUB_ENTERPRISE_URL=https://<public DNS hostname of the ec2 instance) --namespace actions-runner-system
10. Deploy my runnerdeployment.yml into EKS which has the org in it that I created in step 2.
11. Deploy my horizontalrunnerautoscaler.yml into EKS.
12. Check to see if the runner now appears in the org's Actions settings(it does not).

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version - I'm not sure. I assume it's pulling the latest release(0.15) but possibly not?
 - Deployment Method - Helm
 - Helm Chart Version [e.g. 0.11.0, if applicable]

**Additional context**

**Comment by toast-gear** [comment]
https://github.com/actions-runner-controller/actions-runner-controller/issues/712#issuecomment-892242319

**Comment by casanova-21** [comment]
@toast-gear Thank you for the reply. I did read through the other issues and saw that someone was able to do this but didn't provide any instruction on how exactly it was done. And it's not documented in this repo. What I'm trying to do seems fairly standard in that any customer using GHES and trying to implement this would be doing the same and we would want to have this documented. Can you help me in defining the steps here that need to be done to get the certificate chain added into the controller? I'm happy to get a PR submitted to update the documentation if we can determine what exactly needs to be done.

I also noticed that the documentation in the README.md seems to be incorrect for GHES. It states that the following must be executed to be able to properly point the actions-runner-controller to your GHES instance.
`kubectl set env deploy controller-manager -c manager GITHUB_ENTERPRISE_URL=<GHEC/S URL> --namespace actions-runner-system`

There is no 'controller-manager' deployment and instead the deployment is 'actions-runner-controller'.

**Comment by toast-gear** [comment]
The controller image is based on distroless and the code in written in Go. I assume you just do a custom build of the controller and add CA in a location Go looks for them:

https://stackoverflow.com/questions/40051213/where-is-golang-picking-up-root-cas-from/40051432#40051432

https://stackoverflow.com/questions/52636213/docker-distroless-image-how-to-add-customize-certificate-to-trust-store

**Comment by casanova-21** [comment]
@toast-gear Thanks again for the feedback on this.

So here's what I've tried so far and I'm still having issues with the runners connecting to the GHES instance.

1. Launch GHES 3.3.rc1 instance.
2. Create test org in GHES
3. Launch EKS cluster in AWS.
4. Enable Actions in the GHE instance and then create the PAT with the appropriate scope.
5. Install cert-manager in EKS cluster.
6. Create actions-runner-system namespace.
7. Create secret for controller-manager with the PAT value.
8. I've checked internally here and since I'm using a self-signed certificate for GHES, that certificate is contained in /etc/haproxy. There's ssl.crt and ssl.crt+key. I've taken ssl.crt+key and used 'kubectl create secret from file' to generate a secret called "ghecert" that contains the filename ghe.crt and the contents of ssl.crt+key in the actions-runner-system namespace.
9. I've cloned this actions-runner-controller repo so that I can modify the deployment.yaml as follows:
`       volumeMounts:
        - mountPath: "/etc/actions-runner-controller"
          name: secret
          readOnly: true
        - mountPath: /tmp
          name: tmp
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ghe-cert
          readOnly: true`

and
`      volumes:
      - name: secret
        secret:
          secretName: {{ include "actions-runner-controller.secretName" . }}
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "actions-runner-controller.servingCertName" . }}
      - name: ghe-cert
        secret:
          secretName: ghecert
      - name: tmp
        emptyDir: {}`

10. Deploy the helm chart from my local copy of it. `helm upgrade —install -f values.yml -n actions-runner-system actions-runner-controller ./actions-runner-controller`
11. `kubectl set env deploy -n actions-runner-system actions-runner-controller -c manager GITHUB_ENTERPRISE_URL=https://<hostname of my ec2> --namespace actions-runner-system`
12. Attempt to point Go to the cert dir `kubectl set env deploy -n actions-runner-system actions-runner-controller -c manager SSL_CERT_DIR=/etc/ssl/certs --namespace actions-runner-system`
13. I then deploy the runnerDeployment and HorizontalRunnerAutoscaler.

This is the error I see in the actions-runner-controller manager container:
`2021-11-17T20:01:40.154Z	ERROR	actions-runner-controller.runner	Failed to get new registration token	{"runner": "k8s-runner-deployment-x56pz-d7s89", "error": "failed to create registration token: GET https://<ec2- hostname>/api/v3/orgs/harkonnens/actions/runners/registration-token: 404 Not Found []"}
github.com/actions-runner-controller/actions-runner-controller/controllers.(*RunnerReconciler).Reconcile
	/workspace/controllers/runner_controller.go:286
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214
2021-11-17T20:01:40.154Z	ERROR	controller-runtime.manager.controller.runner-controller	Reconciler error	{"reconciler group": "actions.summerwind.dev", "reconciler kind": "Runner", "name": "k8s-runner-deployment-x56pz-d7s89", "namespace": "default", "error": "failed to create registration token: GET https://<ec2 hostname>/api/v3/orgs/harkonnens/actions/runners/registration-token: 404 Not Found []"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214
2021-11-17T20:01:40.154Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"Runner","namespace":"default","name":"k8s-runner-deployment-x56pz-d7s89","uid":"c4ccac4d-d351-4b7a-abb9-49a4e2c020da","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"47729"}, "reason": "FailedUpdateRegistrationToken", "message": "Updating registration token failed"}`

And in the runner pod logs:
`Github endpoint URL https://<ec2 hostname>/
mv: inter-device move failed: '/runnertmp/bin' to '/runner/bin'; unable to remove target: Directory not empty
mv: inter-device move failed: '/runnertmp/externalstmp' to '/runner/externalstmp'; unable to remove target: Directory not empty
mv: inter-device move failed: '/runnertmp/patched' to '/runner/patched'; unable to remove target: Directory not empty
Configuring the runner.

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

The SSL connection could not be established, see inner exception.
Configuration failed. Retrying`

So obviously the SSL connection is still an issue but I'm not quite sure where I'm going wrong here. I don't know if the ssl.key+crt(contains the cert and the private key) isn't sufficient and I'm needing a bundle instead, or if it's not being mounted and accessed properly on the manager container.

Tagging @exploiz65 to see if they were able to get this working based off [this issue](https://github.com/actions-runner-controller/actions-runner-controller/issues/712#issuecomment-892242319).

**Comment by casanova-21** [comment]
@toast-gear 
The other question I have is whether or not the ca bundle needs to be presented just to the controller or also to the runners. Is the controller natively able to pass the certificates down to the runners when they spawn, or do we have to make that happen?

**Comment by toast-gear** [comment]
The runners will definitely needs the ca-bundle as they make API calls to GHES independent from the controller. I believe the controller would also need the bundle as it communites with GHES to create tokens. Please do test and report back because whilst we probably can't provide a guide as we don't have a GHES environment we can link to dicussions.

The runners are ubunut based so you should be able to test the runner side fairly easily.

**Comment by casanova-21** [comment]
@toast-gear Got this working today with some help from our Actions team. You were indeed correct that both the runners and the controller needed the certs. I'm going to test out the procedure again this afternoon and iron out the steps. What's the best means of getting a guide put together? Do you want me to PR against the README.md or do you want to start a separate document for the GHES implementation?

It required me to edit both the actions-runner-controller/templates/deployment.yaml as well as the runnerdeployment.yml I used. In these, I needed to create volumes and volume-mounts in both of them for the certificate of my GHES appliance which I stored as a secret in the cluster. So there are several steps involved in getting this to work and don't want to bloat that smallish GHES section in the README.md.

**Comment by casanova-21** [comment]
I've got the process written up in a private gist for now which I can share with you or anyone else until we can get it tested out and find a more suitable location for it.

**Comment by toast-gear** [comment]
Awesome news! I think having a write up as a `show and tell` entry in the dicussions will be a good starting point.

**Comment by casanova-21** [comment]
@toast-gear [Done](https://github.com/actions-runner-controller/actions-runner-controller/discussions/957)!

**Comment by toast-gear** [comment]
I'm going to consider this resolved and close the ticket now that we have a guide.
