### ISSUE TITLE
Cannot use runner registration token

### ISSUE THREAD

**Issue by pabrahamusa** [actions-runner-controller/actions-runner-controller#954]
**Describe the bug**
I am using PAT authentication for runner which is very personal. I want to use the github official runner registration token. I tried the token and it failed with github authentication. Is there any way to use tokens instead of PAT?

**To Reproduce**
1. Deploy the actions-runner-controller with runner registration token

**Expected behavior**
I should be able to deploy a  self hosted github runner in k8s with runner registration token

**Environment (please complete the following information):**
 - Controller Version 0.20.2
 - Deployment Method  -  Helm 
 - Helm Chart Version  0.14.0

**Comment by mumoshu** [comment]
@pabrahamusa Hey!

> github official runner registration token

So you're trying to use the runner registration token provided in `add runner` page in GitHub Web UI as the token for actions-runner-controller?
Those are totally different things so it's impossible!

**Comment by pabrahamusa** [comment]
Yes I was trying to use Runner Registration token (from add runner). Thanks for clarifying that it is not going to work. Is there any way to avoid PAT and use some different  tokens without creating a 'application user' ?

**Comment by mumoshu** [comment]
@pabrahamusa Hey! Thanks for confirming.

> Is there any way to avoid PAT and use some different tokens without creating a 'application user' ?

I'd suggest GitHub App. You create an app in GitHub, get app ID and private key of the app, provide those to actions-runner-controller, so that it acts as the app.

**Comment by toast-gear** [comment]
As @mumoshu says having the runner token managed outside of actions-runner-controller isn't supported and isn't a feature, the installation instructions should have the details you need to get up and running!
