### ISSUE TITLE
Connection reset by peer inside dind containers

### ISSUE THREAD

**Issue by NicklasWallgren** [actions-runner-controller/actions-runner-controller#959]
We're encountering connection timeouts with `registry.terraform.io` inside containers running in the dind daemon. It happens every 2-3 requests, and we're not able to reproduce the issue inside the self-hosted runner container itself, or outside of the dind daemon. 

How to reproduce.
```
kubectl get all -n=github-runner
NAME                       READY   STATUS    RESTARTS   AGE
pod/self-hosted-runner-0   2/2     Running   0          32m

/*curl works fine */

kubectl exec -it pod/self-hosted-runner-0 -n=github-runner -c docker sh

/*curl works fine */

docker run -it nginx:latest bash

/*timeout every 2-3 request */

root@5efc834b7220:/$ curl https://registry.terraform.io/.well-known/terraform.json
{"modules.v1":"/v1/modules/","providers.v1":"/v1/providers/"}
root@5efc834b7220:/$ curl https://registry.terraform.io/.well-known/terraform.json
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to registry.terraform.io:443
root@5efc834b7220:/$ curl https://registry.terraform.io/.well-known/terraform.json
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to registry.terraform.io:443
```

```
root@04914f1ebfd5:/# curl https://registry.terraform.io/ -v
*   Trying 151.101.194.49:443...
* Connected to registry.terraform.io (151.101.194.49) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to registry.terraform.io:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to registry.terraform.io:443
```

**Comment by mumoshu** [comment]
@NicklasWallgren Hey! An issue like yours usually happens when you're cluster belongs to a network that supports low MTU only and your dockerd-in-runner-pod's-sidecar and your docker command run in your job needs to respect the correct MTU.

That said, would you mind browsing these issues related to docker MTU setting?

https://github.com/actions-runner-controller/actions-runner-controller/issues?q=label%3A%22docker+mtu+issue%22+is%3Aclosed

**Comment by NicklasWallgren** [comment]
@mumoshu Thanks for the reply.

I tried setting `dockerMTU` for our `RunnerSet` and the `--mtu` option is applied correctly to `dockerd`. But it seems like `docker0` still has a MTU of 1500. Am I missing something?

![image](https://user-images.githubusercontent.com/1784879/143187213-1a92d9f8-ebca-4544-9438-51a6d50cf72c.png)
![image](https://user-images.githubusercontent.com/1784879/143187445-413c63c6-c854-4a6f-912f-4e4b7bae6efe.png)

**Comment by mumoshu** [comment]
@NicklasWallgren Ah, does it work if you add a `MTU=1450` envvar onto your `docker` container in the runner pod?

```
containers:
- name: docker
  env:
  - name: MTU
    value: "1450"
```

https://github.com/actions-runner-controller/actions-runner-controller/issues/393#issuecomment-799151588

https://github.com/actions-runner-controller/actions-runner-controller/blob/eefb48ba3f46f6cb2dfb1696ef44950506630b6f/runner/startup.sh#L25-L29

Ideally `dockerMTU` should translate to `MTU` in the startup.sh, but apparently it doesn't. Perhaps I've done it wrong in https://github.com/actions-runner-controller/actions-runner-controller/pull/421

**Comment by NicklasWallgren** [comment]
The new MTU value seems to take effect, but the request timeouts still occurred. Once I added `hostNetwork: true` it worked. Thanks for the help.

docker network inspect bridge

```
 "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1450"
        },
```

**Comment by mumoshu** [comment]
@NicklasWallgren Glad to hear it worked for you! Thanks for confirming.

Just curious, but how is your flannel configured?
Maybe your flannel is somehow missing a correct MTU setting? I guess- would running `ip addr` on your host (rather than container) reveal it if there's any MTU issue there?

**Comment by NicklasWallgren** [comment]
@mumoshu We're using k3s, and haven't changed the default configuration for flannel.

You can read more about the cause of the issue here.
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/25380

**Comment by mumoshu** [comment]
@NicklasWallgren Thanks! I"m not an expert in this area, but then your issue might be due to that flannel0 requires even lower MTU than 1450(like 1410). You made it work with `hostNetwork: true` and I think that basically means you're bypassing flannel and that's why 1450 worked. I guess, if you set `hostNetwork: true` even the default MTU of 1500 would work.

**Comment by NicklasWallgren** [comment]
@mumoshu You are probably right. I tried with a value of 1200, and even if I couldn't replicate the issue inside a dind-hosted container, the issue still occurred when running Github workflows... Really strange.

I'll continue using `hostNetwork: true` until I can figure it out.

**Comment by mumoshu** [comment]
@NicklasWallgren Thanks for the trial! I just recovered my memory- perhaps you missed this workaround?

https://github.com/actions/runner/issues/775#issuecomment-927826684

AFAIK dockerd's mtu setting takes affect only on the default docker network, where GitHub actions runner uses another docker network for containers run in job steps and service containers.

So, MTU=1450 would fix it only for `docker run` commands written by yourself under `run:` fields in a workflow definition, but won't fix it for docker containers run implicitly by actions.

The workaround shared in https://github.com/actions/runner/issues/775#issuecomment-927826684 fixes it for containers managed by actions too, by patching `docker network create` command.

**Comment by NicklasWallgren** [comment]
@mumoshu Ah, that must the root cause of my issue!
I'll look into the workaround in https://github.com/actions/runner/issues/775#issuecomment-927826684

Thanks for the help.

**Comment by mumoshu** [comment]
> To actually give it a try, you'd need to modify https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/startup.sh and build your own docker sidecar container image, push it to e.g. docker hub, and update the --docker-image flag of actions-runner-controllers' controller-manager to point to your custom image.

Oops sorry this was totally wrong. The `docker create network` replacement needs to reside within the runner container, rather than the dockerd(sidecar) container, because it is run by actions/runner running inside the runner container.

That's configurable via `spec.image` in your runnerdeployment or runnerset spec like:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-dindrunnerdeploy
spec:
  replicas: 2
  template:
    spec:
      image: yourdockerhubaccount/runner:yourtag
```
